### ISSUE TITLE
Running LTRharvest/digest with parallel

### ISSUE THREAD

**Issue by JulieDaz** [genometools/genometools#1000]
Hello, here is my issue. I hope someone will be able to help me! Thanks in advance

## Problem description
I’m running LTR harvest/digest and I faced some issues. 
I have over 200 species so I wanted to run several species at once. To do so I wrote a bash function to use with gnu parallel that allows to run several jobs at the same time. When I checked this morning I realised I had a lot of errors like these:

```
Error: File format problem, trying to open HMM file /tmp/198a084286222afb27419fcb9d8e6170.
Opened /tmp/198a084286222afb27419fcb9d8e6170.h3m, a pressed HMM file; but format of its .h3i file unrecognized

gt ltrdigest: error: HMMER child process terminated with error

Error: Unexpected error 7 in opening hmm file /tmp/198a084286222afb27419fcb9d8e6170.

```

I tried to run one species individually and it runs smoothly and found more data than my first parallel run. I tried again with 2 species running at the same time and got the “Unexpected error 7 in opening hmm file” again for one of the chromosomes. My thought is I can’t run LTRharvest/digest on several species at the same time. Is there a way around that?

## Exact command line call triggering the problem

I think it's this one?
```
gt -j 2 ltrdigest -hmms ../Domains/*.hmm  -outfileprefix LTRh/${file}_LTRdigest -seqfile ${file} -matchdescstart < LTRh/${file}_LTRdigest_sorted.gff3 > LTRh/${file}_LTRdigest.gff3

```

## Example minimal input triggering the problem
Running 2 species at once

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
gt (GenomeTools) 1.6.1

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
I'm using gt on a server so I haven't installed it. But the installation is ok I think as there are no issue with doing one individual run.

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
Ubuntu 20.04.3 LTS (GNU/Linux 5.13.0-27-generic x86_64)

**Comment by satta** [comment]
LTRdigest creates a concatenation of all HMM files is is given via the `-hmms` parameter in `/tmp` and then runs `hmmpress` to prepare it for use with HMMER. If there are multiple parallel tasks that use the same HMMs, they will compete for the same files in the directory, and can mess up the file there by writing into it in random order. So my advice would be  to use different `TMPDIR` environment variables for each run to ensure that each parallel process has its own environment to do that in.
Please also make sure to clear the existing files from `/tmp` (` /tmp/198a084286222afb27419fcb9d8e6170.h3m` and similarly named, it's always a 32-char MD5 hash with `.h3*` suffix) before.

**Comment by JulieDaz** [comment]
Thanks for your comment. I would've thought that it will create unique ids for each run. I'm not familiar with TMPDIR or how to implement it in my script, could you give me an example, please? At the moment I have a first script that ls all my folders, check if some files are there or not, and calls my second script that creates an LTRh folder and runs the gt commands. The first script is the function used with `parallel`

**Comment by satta** [comment]
Well, LTRdigest does not know it's being run multiple times at once, so it has no notion of a 'unique ID'. The fact that the same file is generated is based on the idea of caching: if you rerun your (single) run with the same HMM set but a different sequence, it will reuse these prepared HMMs without having to do that again. So I think there may be two solutions (not tested, just from the top of my head)

* Use your shell's `export` to export a different `TMPDIR` for each run of your GNU parallel run, e.g. with the sequence number ("slot ID") from parallel in the directory name, e.g. create `/tmp/ltr1`, `/tmp/ltr2`, ... and then somehow `export TMPDIR=/tmp/ltr1` to the first process, `export TMPDIR=/tmp/ltr2` to the second, etc. I never used parallel myself, but according to https://www.gnu.org/software/parallel/parallel_cheat.pdf you can use `{%}` to get the number. E.g.
  ```
  parallel -j 3 'export TMPDIR=/tmp/ltr{%}; gt ltrdigest ...' ::: ...
  ```
  This should make sure that each parallel run gets its own temp directory.
* Alternatively, you can clean up the default temp directory (e.g. `/tmp` by removing the old files (see above for the patterns to delete) and then do one run with the HMM set in a non-parallel way but on the same machine and with the user your parallel run will be done. This should create a safe, cached, preprocessed HMM set that is complete and should be used by multiple calls in parallel afterwards.  (Haven't tried this though, just looked at the code from when I wrote it ;))

I have not tried both

**Comment by JulieDaz** [comment]
So I started by doing 1 run at a time, then my supervisor wanted it to be faster so he told me to run several species at once. I tried again to delete the files in /tmp and do a single run, but the 32char string is the same, and the same than in your 1st message. It is overwritten everytime, hence why the parallel doesn't work! 

I'm going to try your 1st suggestion :)

**Comment by satta** [comment]
Closing this as answered, feel free to reopen if you have more questions.
