### ISSUE TITLE
gt gff3 -sortlines fails on particular gff

### ISSUE THREAD

**Issue by cmdcolin** [genometools/genometools#1001]
Hi there
I have had great experience with gt gff3 -sortlines on many files and recommend it for jbrowse users before bgzip and tabix

However, we found a file that had an issue
[wormbase_genes.gff3.gz](https://github.com/genometools/genometools/files/8307818/wormbase_genes.gff3.gz)

This produces a file  with unsorted lines

```
$ gt gff3 -sortlines -tidy wormbase_genes.gff3 > wormbase_genes.sort.gff
/* bunch of output about non-tidy stuff */
$ bgzip wormbase_genes.sort.gff
$ tabix wormbase_genes.sort.gff.gz
[E::hts_idx_push] Unsorted positions on sequence #1: 11638470 followed by 11634613
tbx_index_build failed: wormbase_genes.sort.gff.gz

```

Looks like this when looking at file

```
I	WormBase	intron	11633660	11633701	.	-	.	Parent=mRNA3812
I	WormBase	exon	11633702	11633732	.	-	.	Parent=mRNA3812
I	WormBase	CDS	11633702	11633732	.	-	0	ID=CDS3214;Parent=mRNA3812;Name=W04G5.2a;prediction_status=Confirmed;wormpep=CE40145;protein_id=CAJ85753.1;locus=rab-11.2;uniprot_id=Q1ZXR4
I	WormBase	exon	11638470	11638491	.	-	.	Parent=nc_primary_transcript105
###
I	WormBase	CDS	11634613	11634668	.	+	0	ID=CDS3215;Parent=mRNA3813;Name=W04G5.5;prediction_status=Partially_confirmed;wormpep=CE47779;protein_id=CAB07682.4;uniprot_id=O18170
```

**Comment by cmdcolin** [comment]
using genometools from sudo apt install genometools

```
 gt --version
gt (GenomeTools) 1.6.2
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: cc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
Compile flags: -g -O2 -ffile-prefix-map=.=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3

```

**Comment by satta** [comment]
Could you please try the current git master? This is probably already fixed via https://github.com/genometools/genometools/pull/986 🤔 

If this fixes the issue, time for a new release I guess...

**Comment by cmdcolin** [comment]
I think it did the same thing with current master too, did a make on current master and tried with bin/gt output

**Comment by cmdcolin** [comment]
random note: if it is due to the child features going outside the bounds of the parent, do you think tidy should change the parent to have expanded coordinates to match?

**Comment by satta** [comment]
It could be related to that. We look at root node coordinates to derive overlapping clusters to sort individually and later merge. Let me take a look and do some tests, then get back to you.

As for `tidy` behaviour, I do not think we should have that change the coordinates as the GFF3 spec explicitly states that
> The GFF3 format does not enforce a rule in which features must be wholly contained within the location of their parents, since some elements of the Sequence Ontology (e.g. enhancers in genes) allow for distant cis relationships.

**Comment by cmdcolin** [comment]
personal opinion: the use of enhancers like this in GFF is not a good use of the spec, and luckily not too common in the ecosystem luckily...

**Comment by satta** [comment]
Update: My quick fix, using the maximum span of the whole connected component to determine sortable clusters, didn't help. This makes it quite hard to debug this further. I'll look into this as my time allows it 😬

**Comment by cmdcolin** [comment]
Thanks. Just for the record, a "simple" GNU sort is sufficient for bgzipping and tabixing, but it is such ugly syntax e.g.

    (grep ^"#" in.gff; grep -v ^"#" in.gff | sort -k1,1 -k4,4n) | bgzip > sorted.gff.gz;


It is not fun to type! I would much prefer to recommend gt gff3 -sortlines :)

**Comment by cmdcolin** [comment]
Reference http://www.htslib.org/doc/tabix.html

**Comment by satta** [comment]
So it looks like I was trying to be too clever with my approach of sequentially sorting overlapping clusters of connected components: looks like there is nothing to prevent a child feature beneath a parent feature at the very end of a sequence to refer to a far away location at the beginning of the sequence, making it impossible to safely flush a sorted cluster in the meantime without breaking line-sortedness.

This means that the only boundary allowing us to do that is the sequence boundary, since GenomeTools forces children of a common parent to be located on the same sequence. I have adapted the streaming code accordingly (see the `sortlines2` branch in my repo (https://github.com/satta/genometools) and it now processes your data correctly.

**Comment by cmdcolin** [comment]
awesome :)  thanks for checking into it!
