### ISSUE TITLE
We need to run tirvish two times for a single genome?

### ISSUE THREAD

**Issue by xiekunwhy** [genometools/genometools#1008]
Hi,

We need to run tirvish two times for a single genome (one run for original sequence and an other run for reverse complement sequence)?
I found some describtions here (https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/blob/cc04a2db30c98f21981eb2d90710887be726bfcc/README.md), "Please note, as some tools (HelitronScanner, MiteFinderII, MITE-Tracker, SINE-Finder, TIRvish) do not annotate on both strands, we recommend to run these on the reverse complementary as well".

Best,
Kun

**Comment by satta** [comment]
I haven't looked at it for quite some time, but IIRC you don't need to run it twice. The detection is done on the inverted repeat structure, which is the same on both strands. For strand assignment (i.e. to decide if the original element is on the + or - strand), protein domain matches against a 6-frame translation are used, for which both the original sequence and its reverse complement is considered.
