### ISSUE TITLE
Install error: cairo.h: No such file or directory on RedHat 7

### ISSUE THREAD

**Issue by zhilianghu** [genometools/genometools#1009]
I downloaded `genometools-1.6.2.tar.gz` from http://genometools.org/pub/ to
my computer, a Red Hat Enterprise Linux Server 7.3 (Maipo)  Linux 3.10.0-327.4.5.el7.x86_64
Upon expand and `make`, it proceed to a point when says:
> /path/to/genometools-1.6.2/src/annotationsketch/graphics_cairo_api.h:21:19: fatal error: cairo.h: No such file or directory
> #include <cairo.h>
>                  ^
> compilation terminated.

I googled for helps and found it's mostly on other platforms; didn't find similar posted issues for RH/CentOS.

With some hits from those on Ubuntu systems, I did
> sudo yum install libXt-devel

on my system and it didn't help to resolve the issue.

Any help will be appreciated.
z.

**Comment by satta** [comment]
By default GenomeTools is trying to build with AnnotationSketch enabled, and this needs the Cairo library (I think it's `cairo-devel` on Red Hat, but I'm not certain). If you don't need AnnotationSketch (i.e. you don't want to draw annotation images) then you can just build GenomeTools without support for that:

```
make cleanup
make cairo=no 
make cairo=no install
```
or similarly, just add the `cairo=no` parameter to _all_ `make` calls after running `make cleanup` to reset your build configuration. This should eliminate the dependency on that library.

**Comment by satta** [comment]
Closing this as answered, feel free to reopen if you have more questions.
