### ISSUE TITLE
How to test whether the GenomeTools  library is installed properly

### ISSUE THREAD

**Issue by Wenmj201582** [genometools/genometools#1010]
## Problem description
I have compiled the package on the environment, but I don't know how to test whether the library is installed properly.
![image](https://user-images.githubusercontent.com/77086644/187184511-65632565-f4e7-45f2-bc56-27299de6366d.png)

I found two directories (testdata and TestSuite), which seem to be used for testing. How do I use them?
![image](https://user-images.githubusercontent.com/77086644/187184451-e3eaae63-b561-43da-bd2f-3e58a90aac70.png)

## Exact command line call triggering the problem

```
gt ...
```

**Comment by satta** [comment]
If you want to test the GenomeTools executable `gt`, you can run `make test` repeating all the `make` parameters from your original `make` run. So if you compiled `GenomeTools` with just `make` then use `make test`, if you compiled, for example, with `make cairo=no` then you use `make cairo=no test`.

If you actually want to test the GenomeTools _library_ `libgenometools.so` to use in your own programs, you would need to install the headers and library (`make install` as above and as root), write a small C program that uses it and link against the library. I assume you know how to do that. You can look at https://github.com/genometools/genometools/blob/master/src/examples/noop.c for a small example that just initializes the library, does nothing, and exits.

You can also use the packaged GenomeTools version, which is available for various Linux distributions and Mac OS X. What OS are you on?
