### ISSUE TITLE
After installation, how to use and test whether the function is normal?

### ISSUE THREAD

**Issue by DaShaCHun123** [genometools/genometools#1011]
## Problem description

Can you provide the use method or test case of the software?

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
genometools-1.5.8

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.

make 64bit=no errorcheck=no cairo=no CC=clang CXX=clang++ FC=flang
## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
openEuler release 20.03 (LTS-SP3)

**Comment by DaShaCHun123** [comment]
There is a problem with the compilation result
![image](https://user-images.githubusercontent.com/105276615/191446445-10f8452c-a977-4480-bacd-a8b5dd6be647.png)

**Comment by satta** [comment]
Your error refers to https://github.com/genometools/genometools/issues/941 which has been fixed over 2 years ago. Please use a newer version of GenomeTools that already has this fix. Version 1.5.8 is pretty old, we're at 1.6.2 at the moment.

About your other question: What do you want to do? If you just want to test whether the `gt` executable works, just run `gt -test` (you might want to add the path to the binary, such as `/home/to/genometools-1.6.2/bin/gt -test`) and a set of built-in tests will run. With this executable you can also run all of the GenomeTools tools; see 
http://genometools.org/tools.html.

**Comment by DaShaCHun123** [comment]
Thank you very much. The problem has been solved.
Do you need to set environment variables after installation?

**Comment by satta** [comment]
To get an idea of why tests fail, you need to look at at the output in the files that is referenced in the failing test message, i.e. for 
```
258: gt fastq sample empty file : failed
[ problem: unexpected return code: 2 != 1
in: /opt/to/genometools-1.6.2/testsuite/stest_testsuite/test258 ]
```
you can look at the `stderr_*`/`stdout_*`/... files in `/opt/to/genometools-1.6.2/testsuite/stest_testsuite/test258` to see what the error messages are.

Please note that the tests in the test suite are meant for development and may be affected by some of the environment settings on your machine, as well as the `make` parameters you used.
For example, if you used the
```
make 64bit=no errorcheck=no cairo=no CC=clang CXX=clang++ FC=flang
```
line to build your binaries, then you will need to repeat that line when running the tests:
```
