### ISSUE TITLE
error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]

### ISSUE THREAD

**Issue by ShirelyI** [genometools/genometools#1016]
## Problem description
error while make
![1fb940933bb3ed4ac3b1331dec83abd](https://user-images.githubusercontent.com/103233242/202073669-de83fc25-2af9-443c-ad29-7b1acba303f4.png)

## Exact command line call triggering the problem
make 64bit=yes threads=yes cairo=no -j4
[create obj/gt_config.h]
[compile sqlite3.o]
[compile array.o]
[compile alphabet.o]
[compile array2dim.o]
[compile array2dim_sparse.o]
[compile array3dim.o]
[compile basename.o]
[compile bioseq.o]
[compile bioseq_col.o]
[compile bioseq_iterator.o]
[compile bitbuffer.o]
src/core/bioseq.c: In function 'construct_bioseq_files':
src/core/bioseq.c:121:18: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]
  121 |       if (i > 0) fwrite(buf, 1, i, tmpfile);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/bitbuffer.c: In function 'gt_bitbuffer_FILE_new':
src/core/bitbuffer.c:54:12: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]
   54 |     (void) fwrite(&writtenbits,sizeof writtenbits,(size_t) 1,outfp);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/bitbuffer.c:55:12: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]
   55 |     (void) fwrite(&bitsperentry8,sizeof bitsperentry8,(size_t) 1,outfp);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/bitbuffer.c: In function 'gt_bitbuffer_generic_write_FILE':
src/core/bitbuffer.c:92:14: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]
   92 |       (void) fwrite(&bb->currentbitbuffer,sizeof bb->currentbitbuffer,
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   93 |                     (size_t) 1,bb->fp);
      |                     ~~~~~~~~~~~~~~~~~~
src/core/bitbuffer.c: In function 'gt_bitbuffer_flush':
src/core/bitbuffer.c:230:14: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]
  230 |       (void) fwrite(&bb->currentbitbuffer,
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  231 |                     sizeof bb->currentbitbuffer,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  232 |                     (size_t) 1,bb->fp);
      |                     ~~~~~~~~~~~~~~~~~~
src/core/bitbuffer.c:237:16: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]
  237 |         (void) fwrite(&writtenbits,sizeof writtenbits,(size_t) 1,bb->fp);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[compile bitpackstringop.o]
cc1: all warnings being treated as errors
make: *** [Makefile:823: obj/src/core/bitbuffer.o] Error 1
make: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
make: *** [Makefile:823: obj/src/core/bioseq.o] Error 1

## Example minimal input triggering the problem
make 64bit=yes threads=yes cairo=no -j4

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
1.6.2

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
make 64bit=yes threads=yes cairo=no -j4

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
CentOS Linux release 7.2.1511  x86_64

**Comment by satta** [comment]
Looks like your compiler checks catch more instances of unused results than the ones we used. You can build with `errorcheck=no` to work around this issue while we take a closer look.

**Comment by ShirelyI** [comment]
Hi Sascha Steinbiss,
Thanks for your reply.
I added 'errorcheck=no' to compile and there were some warning messages such as 
![genometools1](https://user-images.githubusercontent.com/103233242/202333399-041a6446-e1ca-46c8-95e7-86b17a2d7c49.png)
![genometools2](https://user-images.githubusercontent.com/103233242/202333412-7b2292dc-380c-4013-92a8-b7ae16701330.png)
Maybe it doesn't matter for it's just warnings not fatal error.
I'll ask you for help if there are wrong messages.
Best wishes.

**Comment by satta** [comment]
Unfortunately, I could not reproduce the issue on CentOS 7.2.1511 using either `CC=gcc` or `CC=clang` (gcc 4.8.5, clang 3.4.2 and make installed via `yum`):

![image](https://user-images.githubusercontent.com/27732/202876817-cad758d9-7d79-48c2-8871-f14158ab3507.png)

Can you share more about the compiler you're using that generates that kind of error?
