### ISSUE TITLE
Assertion error: gt_feature_node_remove_leaf

### ISSUE THREAD

**Issue by haessar** [genometools/genometools#1020]
## Problem description
We have a lua script that utilises a gt.custom_stream_new_unsorted stream to iterate through feature nodes and their children. For the following gene and its mRNA children
![image](https://user-images.githubusercontent.com/11962461/229821419-d7207a97-87a8-4ee9-8640-d31b93ac9a19.png)
where c = mRNA3712 and cur_gene = gene3645, the below "Exact command line call" raises the following assertion error

> Assertion failed: (gt_feature_node_number_of_children(leafn) == 0), function gt_feature_node_remove_leaf, file src/extended/feature_node.c, line 1153.
This is a bug, please report it at
https://github.com/genometools/genometools/issues
Please make sure you are running the latest release which can be found at
http://genometools.org/pub/
You can check your version number with gt -version.
Aborted (core dumped)

It appears that the presence of a second mRNA transcript child of the gene is failing this assertion (because gt_feature_node_number_of_children(leafn) == 1 after mRNA3712 is removed). Is this a correct assumption? If so, is there a reason for this assertion to exist in light of alternative spliced genomes?

## Exact command line call triggering the problem

```
cur_gene:remove_leaf(c)
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
1.6.1

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
No

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
Ubuntu 20.04

**Comment by satta** [comment]
`mRNA3712` is not a leaf; it has a CDS (the one at 383026-383958) as a child. Since `gt_feature_node_remove_leaf()` is meant to remove leaves only, this assertion fails. The correct way to do this is to remove the CDS first, then the mRNA (which is a leaf after removing the CDS).

However, this should not cause an assertion to fail but rather be checked in the Lua bindings and trigger a runtime error. I'll take a look at this.

**Comment by satta** [comment]
I opened a PR to make this case a runtime error. Thanks for noticing and getting in touch!
