### ISSUE TITLE
fatal error: pango/pangocairo.h: No such file or directory

### ISSUE THREAD

**Issue by ruoyu1123** [genometools/genometools#1039]
## Problem description
Many library can not be found in make.

## Exact command line call triggering the problem

```
gt ...
```

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
make -j4

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
ubuntu 20.04

**Comment by satta** [comment]
If you want to build with AnnotationSketch support, you have to install some extra development packages: `libpango1.0-dev` and `libcairo2-dev` (see  https://github.com/genometools/genometools/blob/master/INSTALL#L40).

If you don't need it, use the `cairo=no` make parameter. In that case, run `make cairo=no cleanup` before running `make cairo=no` to start with a clean build environment.

**Comment by ruoyu1123** [comment]
Thanks for your reply. Because we are not root users, there are many problems in install. I have successed to install gt And I have a question that if gt excuted file are linked to a PATH path, it can running normally? Does it must be add the installing path to PATH?

**Comment by satta** [comment]
You can add the `bin` directory of your build to your `PATH`, sure. Alternatively, you should also always be able to run the `gt` executable using the full path, e.g. `/my/build/path/genometools/bin/gt`.

**Comment by ruoyu1123** [comment]
Ok， very thank you. I add the `bin` of build path to `PATH` and successed running it. Previously, I linked `gt` excutable file to my `bin`, but it can not running.
