### ISSUE TITLE
Handling of trans splicing

### ISSUE THREAD

**Issue by standage** [genometools/genometools#225]
The *D. melanogaster* genome has 2 genes with trans splicing annotated. As a result, the exons and CDS segments do not all share the same strand. This does not seem to be a problem for the exon features, since they are distinct from each other, but since the CDS is a multifeature, GenomeTools complains that not all CDS segments have the same strand.

This is a biologically valid, although admittedly rare, case. Perhaps this should generate only a warning and not an error? Will this have unintended consequences elsewhere?

To see the error, try downloading ftp://ftp.ncbi.nih.gov/genomes/Drosophila_melanogaster/RELEASE_5_48/CHR_3/NT_033777.gff and running it through ``gt gff3``.

**Comment by sjackman** [comment]
The definition of a trans-spliced gene in GFF is here: http://sequenceontology.org/so_wiki/index.php/Discontinuous_features
