### ISSUE TITLE
Trying to understand gff3 validator error message.

### ISSUE THREAD

**Issue by yeban** [genometools/genometools#514]
I'm working on exporting GFF3 from a database for a project of mine. After export I use gt to validate the GFF3 file (will subsequently use gt to obtain mRNA, CDS, and protein sequences from the GFF3).

This snippet - https://gist.github.com/hargup/38aeeec264b2e50d405a - passes locally, but fails the online validator at http://genometools.org/cgi-bin/gff3validator.cgi with the error message:

```
GenomeTools error: the child feature with type 'exon' on line 4 in file "/tmp/issue.gff" is not part-of parent feature with type 'mRNA' given on line 3 (according to type checker 'OBO file /home/satta/genometools_for_web/gtdata/obo_files/so.obo')
```

Why would that be?

**Comment by satta** [comment]
Actually, if one only follows the part_of edges from "exon" upwards, one finds that an exon is always part of a "transcript" (a more general term than "mRNA") but not of a literal "mRNA". See MISO: http://www.sequenceontology.org/browser/current_svn/term/SO:0000147.
Hence there is one more layer of generalization/specialization to be resolved there which is not addressed here yet. I have been discussing this with SO devs (http://sourceforge.net/p/song/mailman/message/32592474/) and for the time being, if it causes such problems I would like to deactivate the part_of checking feature from the GFF3 parser until this is sorted out. It seems to be non-trivial. Any comments?

**Comment by satta** [comment]
@yeban Please note that you can also use the speck tool (https://github.com/genometools/genometools/wiki/speck-User-manual) for semantic validation. It is also much more powerful than the `gt gffvalidator` but you need to write a separate specification file describing the structure you expect in your GFF exports. In a data exchange proess, we use this tool to verify that database (Chado) dumps can be imported by the recipient (who expect the GFF to be in this particular format).
You can still use `gt gffvalidator` to check the well-formedness of the GFF3 file format.

**Comment by gordon** [comment]
@satta: I'm confused as to why `gt gff3validator -typecheck so testdata/standard_gene_as_tree.gff3` validates and @yeban's example does not (exon with parent mRNA with parent gene validates, exon with parent mRNA doesn't). Does it makes sense for you given the Sequence Ontology  file or do you think it is a bug in our type checker?

You mean disabling part_of checking completely? We could add an option which enables it separately. But I don't really understand why this would be necessary. Does it mean the GFF3 specification wants something (enforcing part_of relationship) which doesn't make sense with the current Sequence Ontology?

**Comment by satta** [comment]
I don't completely understand why one example works and the other does not (but I haven't debugged it in detail yet). However, it seems that with our approach (following part_of and is_a nodes upwards in the SO graph and checking types along the way) we cannot show that an instance of exon can be part_of an instance of mRNA. So I would say there might be something wrong with our implementation of this enforcement. It could certainly help to look at other  checkers and how they solve this problem.

**Comment by gordon** [comment]
OK, I understand it now that both examples should fail with our implementation. I try to fix the bug.

But that also means that the canonical gene example from the GFF3 specification would not validate with the Sequence Ontology which I find rather odd. Are you aware of any other GFF3 checkers which do the part_of validation?

Given the problematic situation I agree that we should disable the parent-child check. What do you think of just disabling the parent-child check, if `-typecheck` is used and still check that the used SO terms are valid? And adding another option to enable the parent-child check separately? (default: false)

**Comment by gordon** [comment]
The reason that the one example works and the other one doesn't it that in one case "transient part-of edges" are introduced and in the other they are not. The corresponding code was introduced in commit 75fe5ec45e087804eb4b672a5b1021f5f0927b01. I vaguely remember that we had a lengthy discussion about this, but I cannot find it. From the commit logs I can see that I separated is_a edges from part_of edges and introduced the transient part_of edges. I think at the time we came to the conclusion that this was the right approach. Maybe the discussion was on the old Lighthouse issue tracker? @satta: Do you remember this?

**Comment by satta** [comment]
Not really :/

**Comment by satta** [comment]
I'm not really sure what these transient edges mean. Maybe they are cached, derived part_of edges from previous lookups? I think I also need to take a closer look into what is happening there. I remember proposing an approach in the old Lighthouse ticket involving upwards traversal in the SO graph along is_a and part_of edges and comparing types, finally compressing the path at the end by adding derived part_of edges. 
But now I think this approach was wrong from the beginning...

**Comment by gordon** [comment]
It has nothing to do with the result cache, I checked that. Somehow we derived new edges. Let me study the code to see what is really going on there... This is code that really deserved some documentation - lesson learned.

**Comment by gordon** [comment]
I think I understand now what these transient edges mean. Let me give you an example (we are looking at `mRNA` and `exon`, see http://www.sequenceontology.org/browser/current_svn/term/SO:0000234 and http://www.sequenceontology.org/browser/current_svn/term/SO:0000147, respectively):

* `mRNA` is_a `mature_transcript`
* `mature_transcript` is_a `transcript`
* `transcript_region` part_of `transcript`

Therefore (transient edges):

* `transcript_region` part_of `mRNA`
* `transcript_region` part_of `mature_transcript`

If this is correct then `exon` is_a `transcript_region` part_of `mRNA` (that's why the standard gene validates) and that would mean that there is a bug for the example @yeban provided (the transient edge was not introduced).

@satta: What do you think? Does this still make sense or was our old approach flawed from the beginning?

**Comment by satta** [comment]
Well, during my discussions with Chris Mungall he stated that terms like "if X _is_a*_ Y and Z _part_of_ Y, then Z _part_of_ X" would lead to 'all kinds of false conclusions'. I think you were proposing such a case. Please see the email I linked above. However, he might have been talking about the ontology definition itself and how to derive new derived edges in the ontology, but we only want to verify whether instances match the ontology, so it might be a different kind of query.

I must say I didn't fully follow this issue through as there were more urgent issues at hand at that time. What I would propose is to take a look at if and how the GMOD validator checks for proper parent-child terms (http://sourceforge.net/p/gmod/svn/HEAD/tree/gff-validator/trunk/lib/GFF3/Validator.pm) and learn from there how the check is supposed to behave.

**Comment by gordon** [comment]
Yes, that is exactly what I'm proposing and what we have been doing all along. The only problem was that there was a bug in our code that led to @yeban's example failing (see upcoming pull request).

I fixed the bug and now the example works and the standard gene from the GFF3 specification still validates under the SO.

I looked at the GMOD validator and they don't seem to be doing these kind of checks at all. I also looked at the email you mentioned and it couldn't figure out why this would lead to 'all kinds of false conclusions'. It seems to me that this is the right approach, at least for what we are trying to do here.

Therefore, I would like to keep the code as it is (with the bug fix) and see if problems or counter arguments turn up.

**Comment by satta** [comment]
Okay, sure. Makes sense to me as well. Thanks for the PR and the test case!

**Comment by satta** [comment]
I also just updated the online validator, which was still on a quite old version. Now running the latest git master.

**Comment by gordon** [comment]
Thanks for the update @satta!
