### ISSUE TITLE
add padding to sketch

### ISSUE THREAD

**Issue by juanmas07** [genometools/genometools#524]
Some of the titles of the image are splitted. I want to add some padding in order to show them entirely.

This is a screenshot of the issue
![image](https://cloud.githubusercontent.com/assets/2141907/5680598/32a76d2e-97ee-11e4-873f-fbf949f9d442.png)

thank you

**Comment by satta** [comment]
The text in the images is clipped at the sides so I'm afraid that  just adding 'padding' is not possible. What you can do is increase the size of your viewing region by another 50-100bp, and it might be enough to show the rest of the captions.

**Comment by juanmas07** [comment]
@satta that would be nice, which style should I use in order to do that? thank you

**Comment by satta** [comment]
Just keep using whatever style you have used up to now, and adjust your base region at the end, e.g. where you plotted from 2000-2580 before (see example image) you simply plot 2000-2650 and see what happens. Unfortunately there's no way to automatically compensate for what is clipped at the end.

**Comment by juanmas07** [comment]
@satta  I'm trying to add a hidden feature. The problem is that I cannot hide it. I tried with:

  empty = {
    stroke = {red=0.0, green=0.0, blue=0.0, alpha = 0.1},
    fill = {red=0.0, green=0.0, blue=0.0, alpha = 0.1},
    track_title_color = {red=0.0, green=0.0, blue=0.0, alpha = 0.1},
    default_stroke_color = {red=0.0, green=0.0, blue=0.0, alpha = 0.1},
    background_color = {red=0.0, green=0.0, blue=0.0, alpha = 0.1},
    show_block_captions = false,
    show_track_captions = false,
    arrow_width = 0,
    stroke_width = 0,
    bar_height = 0,
    bar_vspace = 0,
    block_caption_font_size = 0, 
  },
but still I can see the feature (dashed in the image)

![image](https://cloud.githubusercontent.com/assets/2141907/5680865/7b5ec794-97f1-11e4-886b-2054d0a307c3.png)

**Comment by standage** [comment]
I think what @satta is suggesting is being explicit with the start and end
coordinates. Rather than plotting an empty feature, try using the *-start* and
*-end *options in *gt sketch*, or just make sure your GFF3 file has a
*##sequence-region* pragma with the extended coordinates.

First approach would be something like *gt sketch -start 1 -end 2800
myimage.png mydata.gff3*. The second approach would be to add a line to
your GFF3 file that looks like *##sequence-region   sequenceid 1 2800*.

Hope this helps.

--
Daniel Standage
Ph.D. Candidate
Computational Genome Science Lab
Indiana University

**Comment by satta** [comment]
That's exactly what I was suggesting. I assumed you knew about using explicit ranges for plotting so I was a bit confused by your use of 'hidden' features.

**Comment by juanmas07** [comment]
thank you @standage.

I was actually using the second approach:

##sequence-region	scaffold07640	1	10000
scaffold07640	.	miRNA	2546	2566	.	-	.	ID=22364_20_tae1
scaffold07640	.	miRNA	2551	2571	.	-	.	ID=42022_25_tae1

but it seems that gt sketch trimms the plot. However using  -start and -end parameters solve the issue.

Thanks again @satta @standage
