### ISSUE TITLE
`gt compreads decompress` output formatting

### ISSUE THREAD

**Issue by gordon** [genometools/genometools#537]
If if I compress the following file ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/HG00096/sequence_read/SRR062634.filt.fastq.gz with

`gt compreads compress -files SRR062634.filt.fastq.gz`

and then decompress with

`gt compreads decompress -file SRR062634.filt.fastq`

the result file `SRR062634.filt.fastq.fastq` is formatted to a width of 80 characters:

```
@0
TGATCATTTGATTAATACTGACATGTAGACAAGAAGAAAAGTATGTTTCATGCTATTTTGAGTAACTTCCATTTAGAAGC
CTACTCCTGAGCACAACATT
+
B5=BD5DAD?:CBDD-DDDDDCDDB+-B:;?A?CCE?;D3A?B?DB??;DDDEEABD+>DAC?A-CD-=D?C5A@::AC-
?AB?=:>CA@##########
@1
AATGTTATTAAAAATGGACACCTTTTTCTCACACATTCAGTTTCATTGTCTCGCACCCCATCGTTTTACTTTTCTTCCTT
CAGAAAATGATAAATGTGGG
+
AAAA?5D?BD==ADBD:DBDDDDD5D=;@>AD-CD?D=C5=@4<7CCAA5?=?>5@BC?*<:=>>:D:B5?B?5?'3::5
?5<:;*97:<A#########
@2
CAGATCAGAATAATTTTTGTGTTATGTACGTGTAAGAAAACATAGCTATTATGATATGGAAACTAGGAGTGAAATATGAG
GAATTTGTGACTTTTCTGAA
+
``` 

http://en.wikipedia.org/wiki/FASTQ_format says:

"The original Sanger FASTQ files also allowed the sequence and quality strings to be wrapped (split over multiple lines), but this is generally discouraged as it can make parsing complicated due to the unfortunate choice of "@" and "+" as markers (these characters can also occur in the quality string)."

That's what the original file looks like:

```
@SRR062634.321 HWI-EAS110_103327062:6:1:1446:951/2
TGATCATTTGATTAATACTGACATGTAGACAAGAAGAAAAGTATGTTTCATGCTATTTTGAGTAACTTCCATTTAGAAGCCTACTCCTGAGCACAACATT
+
B5=BD5DAD?:CBDD-DDDDDCDDB+-B:;?A?CCE?;D3A?B?DB??;DDDEEABD+>DAC?A-CD-=D?C5A@::AC-?AB?=:>CA@##########
@SRR062634.488 HWI-EAS110_103327062:6:1:1503:935/2
AATGTTATTAAAAATGGACACCTTTTTCTCACACATTCAGTTTCATTGTCTCGCACCCCATCGTTTTACTTTTCTTCCTTCAGAAAATGATAAATGTGGG
+
AAAA?5D?BD==ADBD:DBDDDDD5D=;@>AD-CD?D=C5=@4<7CCAA5?=?>5@BC?*<:=>>:D:B5?B?5?'3::5?5<:;*97:<A#########
@SRR062634.849 HWI-EAS110_103327062:6:1:1587:921/2
CAGATCAGAATAATTTTTGTGTTATGTACGTGTAAGAAAACATAGCTATTATGATATGGAAACTAGGAGTGAAATATGAGGAATTTGTGACTTTTCTGAA
+
DFFEBEF?FEGGGBEFDFB3>EE=EEEEEEEECEBDCCD<CEEEDAA=EEB=DEDFEEDF?=EBBEEAEAD@:?-?A5<AC(=?>4>?############
```

What about adding an option -width to `gt compreads decompress` with a default of 0 (no formatting), similar to the one in `gt splitfasta`?

**Comment by Garonenur** [comment]
yes.
will do, and discourage its use if that is the official way of things for fastq

**Comment by gordon** [comment]
Or just do without a `-width` option and do not wrap at all.
