### ISSUE TITLE
`gt compreads decompress -descs` assertion fails

### ISSUE THREAD

**Issue by gordon** [genometools/genometools#538]
If if I compress the file ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data/HG00096/sequence_read/SRR062634.filt.fastq.gz with

`gt compreads compress -descs -files SRR062634.filt.fastq.gz`

and then decompress with

`gt compreads decompress -descs -file SRR062634.filt.fastq`

I get a failed assertion:

```
Assertion failed: (s && length <= s->length), function gt_str_set_length, file src/core/str.c, line 198.
```

I used the current master (2371aa7c4aefc3128bd21d6cbe737725321f5b95).

**Comment by Garonenur** [comment]
I will have a look at that.

**Comment by gordon** [comment]
Thanks!

**Comment by Garonenur** [comment]
I invested some time in it, and because the compression is quite complicated I will not be able to solve this any time soon, as I have other matters that are quit urgent.
How important is this to you? Did you just discover it by chance, or where you planning on using that code productively?

**Comment by gordon** [comment]
Thanks, it is not urgent. I was just playing around with FASTQ compression and wanted to see how good our lossless compression is.

**Comment by Garonenur** [comment]
I wanted to get back to this, but the ftp-servers seem to miss the sequence files now?

**Comment by gordon** [comment]
Argh, link rot. I uploaded the file here: http://genometools.org/pub/testdata/SRR062634.filt.fastq.gz

**Comment by Garonenur** [comment]
nope. their folder structure just doesn't follow their own rules... I found it agair at ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/phase3/data/HG00096/sequence_read/SRR062634.filt.fastq.gz

but thanks for the upload.

**Comment by Garonenur** [comment]
nice. got it running so it won't crash any more, but it starts to screw up the descriptions after the 61827th read in the file. Problem with debugging this things: I don't know if the bug is in encryption or decryption... I will get that little critter.

**Comment by Garonenur** [comment]
@gordon keep me posted if you are doing more tests with this.

**Comment by gordon** [comment]
@Garonenur: Thanks for the fix! I'll keep you updated, if I run into more trouble.
