### ISSUE TITLE
gt_xtmpfp_generic ignores flags?

### ISSUE THREAD

**Issue by Garonenur** [genometools/genometools#541]
https://github.com/genometools/genometools/blob/master/src/core/fa.h#L91

the flags are apparently ignored and TMPFP_DEFAULT_FLAGS is used instead. Is this intended? Why have the argument ```flags``` then?

**Comment by satta** [comment]
Yup, looks like you're right. I don't see why `flags` is not used there... maybe just a small oversight?

**Comment by Garonenur** [comment]
well least surprising behaviour would be to use the ```flags``` or have a function/macro ```gt_xtmpfp_generic(template)``` that uses the ```TMPFP_DEFAULT_FLAGS```.
