### ISSUE TITLE
gt gff3 fails for (what appears to be) a valid tRNA multifeature

### ISSUE THREAD

**Issue by standage** [genometools/genometools#542]
See [this gist](https://gist.github.com/standage/fc0dd17151e97a9dd378): it is taken from *Drosophila* GFF3 data posted on NCBI. The only change I made to it was to add ID/Parent relationship between the gene and tRNA features.

If you try to process this file with `gt gff3`, it complains about not being able to find the parent ID for the second tRNA entry. As far as I can tell, encoding this tRNA as a multifeature is perfectly valid, even if it's less common (especially when the exons provide the same structure).

**Comment by standage** [comment]
If I encode the tRNA as a single feature (and correct the range), `gt gff3` issues no warning or error.

**Comment by gordon** [comment]
I think I recently introduced this regression, thinking it won't happen in practice. Thanks for the report, I'll fix it.
