### ISSUE TITLE
Assertion failed:

### ISSUE THREAD

**Issue by butterflyology** [genometools/genometools#548]
Here is what the issue reported is:

Assertion failed: (gt_feature_node_get_multi_representative(fn->representative) == fn->representative), function gt_feature_node_get_multi_representative, file src/extended/feature_node.c, line 485.
This is a bug, please report it at https://github.com/genometools/genometools/issues.

Please let me know what other information I may provide. 

CH

**Comment by satta** [comment]
Hi,

thanks for your bug report! Could you give some more information about what you were trying to do when this error occurred (e.g. which command you were trying to run, and what data you used)? Also, which GenomeTools version are you using?

Does this error stop occurring if you sanitize your GFF input using `gt gff3 -sort -tidy -retainids gff_file.gff3 > sorted_gff.gff3` before running your command?

Thanks
Sascha

**Comment by gordon** [comment]
If the problem persists, please reopen the bug report with more data.
