### ISSUE TITLE
Make GenomeTools builds reproducible

### ISSUE THREAD

**Issue by satta** [genometools/genometools#549]
Currently the GenomeTools build process is not fully reproducible, i.e. two builds with the same make parameters will most likely result in distribution tarballs with different md5sums. This is because there are some parts of the process which write (overly detailed?) timestamps, i.e. in PDF files and C headers (leading to different binaries!). There are also random seeds in the `gt -help` output, which end up in a packaged manpage. Here's a list of the resulting differences, as seen by Debian: https://reproducible.debian.net/rb-pkg/genometools.html

**Comment by gordon** [comment]
Is that a problem for Debian? Are you working on the issue? I don't mind making the build reproducible, the changing information is not necessary in my opinion.

**Comment by satta** [comment]
It's not an immediate problem per se, but rather a question of code cleanliness and security -- it allows to prove that what is uploaded by a maintainer or compiled by a build farm matches the source code. See Holger Levsen's  FOSDEM talk (https://fosdem.org/2015/schedule/event/stretching_out_for_trustworthy_reproducible_builds/attachments/paper/668/export/events/attachments/stretching_out_for_trustworthy_reproducible_builds/paper/668/2015_01_31_FOSDEM15.pdf). But to be honest, I only want to get the red 'unrep' tag off my Debian package overview ;) 

So it's not urgent. I do not think it's a big thing and I can work on it this weekend maybe.

**Comment by gordon** [comment]
Yes, the seed issue is already solved and my pull request removes `GT_BUILT`. It seems the only thing that is missing are the generated PDF files. This might be a good start: http://superuser.com/questions/130347/how-do-i-produce-bytewise-consistent-documents-with-pdflatex

**Comment by satta** [comment]
Thanks! It might be possible to fix this in Debian only using faketime (http://www.code-wizards.com/projects/libfaketime/) instead of hacking around in all the LaTeX sources (which might break again with the next manual) so I think I might try that.

**Comment by satta** [comment]
The package now builds reproducibly: https://reproducible.debian.net/rb-pkg/unstable/amd64/genometools.html

**Comment by gordon** [comment]
Cool!
