### ISSUE TITLE
Interfeat support for multifeatures

### ISSUE THREAD

**Issue by standage** [genometools/genometools#554]
Consider the following use case. I have a data file with entries like this.

```
chr1     .    EST_match       2500    3050    .       +       .       ID=EST_match4
chr1     .    EST_match       4000    5700    .       +       .       ID=EST_match4
```

I would like to use the interfeat tool and/or visitor to infer `match_gap` features between `EST_match` features. The following does not work.

```
gt interfeat -outside EST_match \
             -inter match_gap \
             annot.gff3
```

I'm guessing this is because the `EST_match` is multifeature, and it's looking at the outer edges of the entire feature instead of the inner edges of individual components.

**Comment by gordon** [comment]
The problem was that this is a top-level multi-feature. With the pull request it works now, please look into the commit for an explanation.

**Comment by standage** [comment]
Awesome. Thanks for the quick response @gordon.
