### ISSUE TITLE
GC-content on windows

### ISSUE THREAD

**Issue by enigene** [genometools/genometools#560]
Hi, I using GenomeTools on windows

```
/cygdrive/c/usr/local/bin/gt (GenomeTools) 1.5.5

Used compiler: cc (GCC) 4.9.2
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -O3
```

and trying to get GC-content for this test set of sequences:
```
>seq1
GGCTTAGAAAAATAGACATTCCAAGATGCCTGAAGTGTTTAAGTGGCTATTGCTAATTGGATGGTGTTGACTGTGGAGGTAAATGGATC
>seq2
TTGAGTCCAGGAGTTTGAGACCAGCCTGGACAACAGGGCAAGACCCCATCTCTAAAAATATAAAATTAGCTGGGCATGGTGTCGTGTGCCTGTGATC
>seq3
TGCACCTGCCGCCGGAGCTCTCTCTGCAAACGTTCTGTGCTGACTTAGGGGAGGCAAAGACACAGAGTTGGAGATC
```
using: `/cygdrive/c/usr/local/bin/gt.exe seq -gc-content test_gc1.fas`

```
showing GC-content for sequence file "test_gc1.fas"
GC-content: 47.06% (AT-content: 51.84%, N-content: 0.00%)
```

then I check this result with simple awk script

`awk '!/[^ACGTN]/{split($0,a,"");for(i in a)b[a[i]]++}END{printf("%.2f%%",(b["G"]+b["C"])/(b["A"]+b["T"]+b["G"]+b["C"])*100)}' test_gc1.fas`

answer is: 48.09%

but on linux

```
/usr/local/bin/gt (GenomeTools) 1.5.5

Used compiler: cc (Ubuntu 4.9.1-16ubuntu6) 4.9.1
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -O3 -Werror
```

using `/usr/local/bin/gt seq -gc-content test_gc1.fas`

```
showing GC-content for sequence file "test_gc1.fas"
GC-content: 48.09% (AT-content: 51.91%, N-content: 0.00%)
```
it's OK

**Comment by satta** [comment]
That's interesting... I will check this on my Windows box when I have some time. Just out of curiosity, which Windows/cygwin version are you running?

**Comment by satta** [comment]
Also, just to make sure... does the result change if you add the `-recreate` option to your  `gt seq` call?

**Comment by enigene** [comment]
Info:
```
uname -a
CYGWIN_NT-6.1 enyoi 1.7.34(0.285/5/3) 2015-02-04 12:12 i686 Cygwin
```
32-bit Windows 7

Result not changed with `-recreate` option and I always delete all the index files via `gt clean`.

**Comment by satta** [comment]
Thank you very much. I will take a look later and let you know what I could find.

**Comment by satta** [comment]
I think this issue is fixed now. I have uploaded new Windows binaries (http://genometools.org/pub/binary_distributions/) and the fix has been merged into the master branch in case you want to build it yourself. Just let me know if there are any more issues. Thanks for reporting this!

**Comment by enigene** [comment]
Built and tested, the results are correct. Thank you!
