### ISSUE TITLE
Improve stdin/stdout support for Lua bindings

### ISSUE THREAD

**Issue by satta** [genometools/genometools#561]
Currently the Lua bindings (in particular the GFF3InStream/OutStream ones) do not support all the features of the C versions. For example, the instream only reads from a file (not from stdin), while the outstream only writes to stdout (not to a file). This leads to the need for workarounds in Lua scripts, such as the use of temporary files in cases where pipes should suffice.
I propose to make the input/output streams more flexible to support all the options available in the C counterparts.

**Comment by gordon** [comment]
Sounds good to me.
