### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by satta** [genometools/genometools#566]
With the recent bug fixes in mind, what do you think about a bugfix release?
What about #538  and #548? Delay until the next version?

**Comment by standage** [comment]
I've seen the assertion message cited in #548 at least a few times, and if I remember correctly it's almost always been a problem with my data. Of course more descriptive diagnostic messages would be preferable, but unless more details are provided there is not much that can be done. I'd suggest that #548 should not delay a bugfix release.

**Comment by gordon** [comment]
@Garonenur doesn't seem to have time for #538 at the moment and for #548 we don't have test data. I would say it's a go for the release!

@standage: If you stumble over data which triggers the assertion, please post it and I will write up a proper error message or fix the bug.

**Comment by standage** [comment]
@gordon Yes, I realized while writing my message that I should have been better at taking notes and sharing. I will certainly do so if I encounter the error again!

**Comment by gordon** [comment]
Thanks for you help! If an assertion fails, that's always a bug. If a problem in your data triggers it it's a "missing error message" bug ;-)

**Comment by satta** [comment]
OK, I will prepare the changelog and do the release later then. Thanks!

**Comment by Garonenur** [comment]
I will get to that bug #538 after May I think so go on.

**Comment by satta** [comment]
Done.

**Comment by gordon** [comment]
Thanks @satta!
