### ISSUE TITLE
GtSplitter

### ISSUE THREAD

**Issue by Garonenur** [genometools/genometools#591]
I was checking out our two tokenizer/splitter classes and would like to ask if it would be possible to enhance the GtSplitter class.
As the GtTokenizer works on files, not strings, which is inconvenient if you have very long lines in a file and just want to extract one of the first tokens from each line.
What I would like to change on GtSplitter is the handling of "empty" tokens, if the delimiter is ' ' and the input contains long stretches of those it would be nice if it skipped those empty results and returns the next non empty string.

**Comment by satta** [comment]
Sure. One could implement an additional `gt_splitter_split()` variation or alternatively pass a switch to the GtSplitter constructor for the multi/single delimiter behaviour? I think I would prefer the second approach...

**Comment by Garonenur** [comment]
I am just implementing the first approach, I really dislike functions with boolean flags doing different things. That is a code smell and goes against "one function does one thing".
Thing is: this function can return 0 tokens, as an empty string would not yield anything. But it realy works better for space separated files.

**Comment by satta** [comment]
The `split` function would still do one thing, i.e. split a string. It would also keep its signature. But it would to its job slightly differently as its splitter object would be of a different kind, created with a different constructor (it doesn't need a boolean parameter, it might as well a different constructor function altogether!).
Anyway, this is a detail issue and both approaches can be justified ;)

**Comment by satta** [comment]
The requested behaviour has been implemented in #590; closing this issue.
