### ISSUE TITLE
seqtranslate: Specify frame

### ISSUE THREAD

**Issue by sjackman** [genometools/genometools#595]
`seqtranslate` does six-frame translation. It would be useful to specify only the first frame `(1+)`. I'm using  this sed script:

```sh
gt seqtranslate -reverse no -fastawidth 0 \
|sed -n '/ (1+)$/{s/ (1+)$//;p;n;p;n;n;n;n;}'
```

Outputting the longest ORF of the six-frame translation would also be a very useful feature.

**Comment by standage** [comment]
:+1:

**Comment by Garonenur** [comment]
hmm. I think I had this "longest ORF" problem once but I have to check how I got around that...

**Comment by satta** [comment]
The `gt orffinder` tool delivers longest ORFs in all six frames given a sequence, a GFF and a feature type to search in.For instance, to search in a whole sequence just cover the whols sequence with a 'chromosome' or simply 'region' feature and use `gt orffinder`.

e.g. for U89959_genomic.fas (in the `testdata` directory):
```
##gff-version 3
##sequence-region gi|1877523|gb|U89959.1| 1 106973
gi|1877523|gb|U89959.1|	.	region	1	106973	.	?	.
```
results in

```
$ gt orffinder -seqfile testdata/U89959_genomic.fas -matchdescstart -types region -- test.gff3
##gff-version   3
##sequence-region   gi|1877523|gb|U89959.1| 1 106973
gi|1877523|gb|U89959.1|	.	region	1	106973	.	?	.	ID=region1
gi|1877523|gb|U89959.1|	GenomeTools	reading_frame	11309	13438	.	-	.	Parent=region1;frame=1
gi|1877523|gb|U89959.1|	GenomeTools	reading_frame	16013	16750	.	+	.	Parent=region1;frame=1
gi|1877523|gb|U89959.1|	GenomeTools	reading_frame	43327	44295	.	+	.	Parent=region1;frame=0
gi|1877523|gb|U89959.1|	GenomeTools	reading_frame	59619	60818	.	+	.	Parent=region1;frame=2
gi|1877523|gb|U89959.1|	GenomeTools	reading_frame	91768	92847	.	-	.	Parent=region1;frame=2
gi|1877523|gb|U89959.1|	GenomeTools	reading_frame	101037	102365	.	-	.	Parent=region1;frame=0
###
```

**Comment by sjackman** [comment]
Thanks for the detailed response, Sascha. I'm feeling increasingly embarrassed how many features I've asked for are already implemented and documented.
