### ISSUE TITLE
extractfeat: option to add coordinates to defline

### ISSUE THREAD

**Issue by yeban** [genometools/genometools#597]
Came up in #592.

**Comment by sjackman** [comment]
:+1:

**Comment by sjackman** [comment]
`-seqid` is a nice feature. Could it also include the coordinates of the feature, and possibly the orientation? i.e.
```
>gene_1 [seqid 1:501-1000]
```

**Comment by gordon** [comment]
Anyone interested in sending a pull request for that? Should be quite easy to implement.
