### ISSUE TITLE
gt_xtmpfp_generic_func ignores template

### ISSUE THREAD

**Issue by Garonenur** [genometools/genometools#599]
the problem sits in https://github.com/genometools/genometools/blob/master/src/core/fa.c#L355 where the template is overwritten by the path to the tmp-directory.

I am not sure if this is as intended and the template GtStr is only meant to be used as a way to find the files later, but I expected the template, if a string was given there, to be used.

**Comment by satta** [comment]
This looks like a typo bug. The braces don't look right. I think lines 337 and 338 should be swapped.

**Comment by Garonenur** [comment]
ok - this would result in tmp-files created in the CWD not in some tmp-folder, And I don't think that is intended either :)
I think there needs to be a temporary GtStr in there to handle the concatenation of the strings and then set the given template at the end, so the caller gets the filename for further uses.

**Comment by satta** [comment]
Only in CWD when no other tempdir works. I think the idea is that when there is a template string, it should be used, otherwise the function tries to find a usable temp location, using CWD as last resort.

**Comment by satta** [comment]
Oops... this code seems to have been correct indeed in its original form!
If you want the template to be used, you need to set `TMPFP_USETEMPLATE`, otherwise the string passed to the `gt_xtmpfp_*` will only be used to return the filename assigned using the default template.

**Comment by Garonenur** [comment]
wow - I can't remember in which context I found this bug. :D
