### ISSUE TITLE
dupfeat: has no effect

### ISSUE THREAD

**Issue by sjackman** [genometools/genometools#600]
`gt dupfeat` has no effect or I misunderstand its purpose. In the following example I expect the mRNA feature to be duplicated to create a new feature identical to the mRNA feature, but with type exon. The output however is identical to the input.

```
❯❯❯ gt dupfeat -source mRNA -dest exon test.gff >out.gff
❯❯❯ diff -s test.gff out.gff
Files test.gff and out.gff are identical
```

### test.gff
```
##gff-version   3
##sequence-region   6 61475 61912
6	maker	gene	61475	61912	.	+	.	ID=gene1
6	maker	mRNA	61475	61912	18.2	+	.	Parent=gene1
###
```

**Comment by sjackman** [comment]
If I disable this test [`if (node != fn) {`](https://github.com/genometools/genometools/blob/master/src/extended/dup_feature_visitor.c#L84) it works as I expect. What's the purpose of this test?

### out.gff
```
##gff-version   3
##sequence-region   6 61475 61912
6	maker	gene	61475	61912	.	+	.	ID=gene1
6	maker	mRNA	61475	61912	18.2	+	.	Parent=gene1
6	maker	exon	61475	61912	18.2	+	.	Parent=gene1
###
```

**Comment by sjackman** [comment]
I'd like for the newly-created `exon` feature to be a child of the `mRNA` feature. Is there a way to accomplish that?

**Comment by sjackman** [comment]
The real issue I'm working attempting to fix is that Prokka outputs genes with a `gene` feature and `CDS` feature but no `mRNA` feature. I'd like to add the `mRNA` feature for downstream tools. See https://github.com/tseemann/prokka/issues/110

I hacked up the following sed script to make this happen.
```sh
	gsed -E '/\tCDS\t/{ \
			s/CDS/mRNA/;p; \
			s/mRNA/CDS/;s/Parent=[^;]*;//;s/ID=/Parent=/;}; \
```

**Comment by satta** [comment]
I'd have to look up what `gt dupfeat` does but I have a script for adding mRNA features: https://gist.github.com/satta/432035142884804566a8

**Comment by sjackman** [comment]
Cool. Thanks!

**Comment by gordon** [comment]
@sjackman: You are right, the check is indeed wrong. I just made a pull request which fixes that. For more complex scenarios like the one you described scripts like the one @satta posted are the way to go, though.

**Comment by sjackman** [comment]
Thanks, Gordon.
