### ISSUE TITLE
gt seqfilter multiple instanzes with stdin

### ISSUE THREAD

**Issue by Garonenur** [genometools/genometools#606]
I have multiple ```GtEncseqs``` in one folder and I wanted to use ```gt seqorder``` to shuffle them, pipe this to ```gt seqfilter``` to only get the first X entries.
But, as ```gt seqfilter``` creates a new ```GtEncseq``` object from ```stdin``` and names it "stdin" this does not work if I want to do this in parallel with multiple inputs.

there should be a way to name implicitly created ```GtEncseq``` files.

**Comment by Garonenur** [comment]
the previous issue was #368

**Comment by satta** [comment]
One could include the PID in the name of the file to make it unique for a given process.

**Comment by Garonenur** [comment]
that would be easiest. right.

**Comment by satta** [comment]
Just thought about it and that would make things more difficult on Windows. I think I will rather use a random number instead.
