### ISSUE TITLE
gt extractfeat merge multiline CDS features

### ISSUE THREAD

**Issue by sjackman** [genometools/genometools#608]
CDS features are often multiline. That is, one GFF record is represented with multiple lines, which is shown by the multiple lines having the same ID. It would be very helpful for `gt extractfeat` to output one FASTA record per GFF record, rather than one FASTA record per GFF line. This would be particularly useful with `-translate`.

For example the following four-line GFF record should output a single FASTA record.
```
12  ctg123 . CDS             1201  1500  .  +  0  ID=cds00001;Parent=mRNA00001;Name=edenprotein.1
13  ctg123 . CDS             3000  3902  .  +  0  ID=cds00001;Parent=mRNA00001;Name=edenprotein.1
14  ctg123 . CDS             5000  5500  .  +  0  ID=cds00001;Parent=mRNA00001;Name=edenprotein.1
15  ctg123 . CDS             7000  7600  .  +  0  ID=cds00001;Parent=mRNA00001;Name=edenprotein.1
```

See http://www.sequenceontology.org/gff3.shtml

**Comment by sjackman** [comment]
Contrast the above CDS feature with the exon features, which each have a different ID, and so are four different GFF records.

```
 8  ctg123 . exon            1050  1500  .  +  .  ID=exon00002;Parent=mRNA00001,mRNA00002
 9  ctg123 . exon            3000  3902  .  +  .  ID=exon00003;Parent=mRNA00001,mRNA00003
10  ctg123 . exon            5000  5500  .  +  .  ID=exon00004;Parent=mRNA00001,mRNA00002,mRNA00003
11  ctg123 . exon            7000  9000  .  +  .  ID=exon00005;Parent=mRNA00001,mRNA00002,mRNA00003
```

**Comment by satta** [comment]
Have you tried the `-join` option for `gt seqextract`? It joins (concatenates) the sequences of all children of a given type who share a parent.
In the case of your exon features, the parents are listed explicitly. For your CDS case (which we call a _multifeature_), the common parent would be a _pseudofeature_ (which is purely virtual and not processed but acts as a common handle for all children with the same ID). 

More on this mechanism can be found in the GenomeTools paper http://doi.ieeecomputersociety.org/10.1109/TCBB.2013.68

**Comment by sjackman** [comment]
Works like a charm! Thanks again, Sascha. It could be useful for `-join` to take three options.

+ `-join no` do not join any features
+ `-join multi` join features that share an ID
+ `-join yes` join features that share a Parent

**Comment by sjackman** [comment]
#icanhazpdf ? http://doi.ieeecomputersociety.org/10.1109/TCBB.2013.68
