### ISSUE TITLE
1.5.6 release?

### ISSUE THREAD

**Issue by sjackman** [genometools/genometools#609]
I'd appreciate a stable release that includes the fixes to #581 and #593.

**Comment by satta** [comment]
Fine with me. What do the others think?

**Comment by standage** [comment]
:+1:

**Comment by satta** [comment]
If there are no arguments against it I will prepare a bugfix release as soon as #612 and #611 are merged.

**Comment by gordon** [comment]
Let me run it through all cross-compilers I have to check that they produce no warnings.

**Comment by gordon** [comment]
With #613 everything is clear!

**Comment by satta** [comment]
great, thanks!

**Comment by satta** [comment]
Done. Linux/Darwin binaries built, Windows ones to follow later, as well as Debian packages.

**Comment by gordon** [comment]
Thanks @satta!

**Comment by satta** [comment]
No problem. BTW, I have a Debian Vagrant box set up with all the cross-compilers installed, so I could do this myself next time ;)

**Comment by sjackman** [comment]
Thanks! I've updated the [Homebrew-science formula](https://github.com/Homebrew/homebrew-science/pull/2436).
