### ISSUE TITLE
gff3 -addintrons: Inherit Name

### ISSUE THREAD

**Issue by sjackman** [genometools/genometools#616]
It would be helpful for the newly-created intron features to inherit the `Name` from their parent.

**Comment by sjackman** [comment]
More generally, a command that would add to all child features the specified attribute of its parent (if it doesn't already have one) would be very helpful. I'm thinking particularly of `Name` here.

**Comment by satta** [comment]
Something like this: https://gist.github.com/satta/e4edeb36fbd52e9e4875 ?
```
[satta@tortuga:~gt] ◇ cat test.gff3                                             [master] [0]
##gff-version   3
##sequence-region   chr1 147971134 148468994
chr1	ENCODE	gene	147971134	147975692	.	-	.	ID=gene1;name2=VPS72;Name=RP11-68I18.8-005
chr1	ENCODE	exon	147971134	147971499	.	-	.	Parent=gene1
chr1	ENCODE	exon	147975554	147975692	.	-	.	Parent=gene1
###
chr1	ENCODE	gene	147971134	147975694	.	-	.	ID=gene2;Name=RP11-68I18.8-007;name2=VPS72
chr1	ENCODE	exon	147971134	147971169	.	-	.	Parent=gene2
chr1	ENCODE	exon	147971347	147971499	.	-	.	Parent=gene2
chr1	ENCODE	exon	147975673	147975694	.	-	.	Parent=gene2
[satta@tortuga:~gt] ◇ gt bequeath.lua Name < test.gff3                          [master] [0]
##gff-version   3
##sequence-region   chr1 147971134 148468994
chr1	ENCODE	gene	147971134	147975692	.	-	.	ID=gene1;name2=VPS72;Name=RP11-68I18.8-005
chr1	ENCODE	exon	147971134	147971499	.	-	.	Parent=gene1;Name=RP11-68I18.8-005
chr1	ENCODE	exon	147975554	147975692	.	-	.	Parent=gene1;Name=RP11-68I18.8-005
###
chr1	ENCODE	gene	147971134	147975694	.	-	.	ID=gene2;Name=RP11-68I18.8-007;name2=VPS72
chr1	ENCODE	exon	147971134	147971169	.	-	.	Parent=gene2;Name=RP11-68I18.8-007
chr1	ENCODE	exon	147971347	147971499	.	-	.	Parent=gene2;Name=RP11-68I18.8-007
chr1	ENCODE	exon	147975673	147975694	.	-	.	Parent=gene2;Name=RP11-68I18.8-007
###
```

**Comment by sjackman** [comment]
Yep, works like a charm. Thanks, Sascha!

Is there a mechanism to include useful Lua scripts like `bequeath` in the `genometools` distribution?

**Comment by satta** [comment]
Not really. I'm also not sure such scripts should go into the distribution directly, maybe a separate repo. On the user side, one might think about a `GT_USER_SCRIPTS_PATH` directory that gets searched for `<cmdname>.lua` files to execute when `gt <cmdname>` is called and there is no built-in tool with that name. If there are name clashes, the user tool should win (otherwise version updates could silently break user workflows by overriding tool names).
Any comments?

**Comment by Garonenur** [comment]
what was the advantage to run the lua-scripts with gt rather than lua standalone?

**Comment by satta** [comment]
Running them via the embedded interpreter in `gt` gives the script access to the GenomeTools bindings, which are the point here. We do not build a module to load the GenomeTools API into a 'regular' Lua session.

**Comment by sjackman** [comment]
> On the user side, one might think about a GT_USER_SCRIPTS_PATH directory that gets searched for <cmdname>.lua files to execute when gt <cmdname> is called and there is no built-in tool with that name.

One convention that's used by `git` is to use put the executable user script in the `PATH`, name the script `gt-COMMAND`, and have `gt COMMAND` simply run the `gt-COMMAND` that's found in the `PATH.

**Comment by sjackman** [comment]
I do like the idea of collecting this scripts somewhere in GitHub, either in this repository or a separate one.

**Comment by satta** [comment]
The git way of doing this indeed makes sense. One can then run a user script directly using `gt-<script>` but also using `gt script`. Does anyone have a comment on that?
As for a separate repo for such scripts, I have started doing this in my github account for more specific tasks (e.g. https://github.com/satta/gt-gff3-converters) but we could also collect them somewhere. @gordon Do you think we should do this in a repo inside the genometools organization?

**Comment by Garonenur** [comment]
I second the idea to have a 'useful user scripts' repository within the genometools organization. It would keep things clean in genometools, but allow users to share their scripts. There should be some guideline how this would be organized, though.

**Comment by gordon** [comment]
Creating a new repository `gtscripts` or something like that in the genometools organization seems like a good idea. It's just a matter of writing a README.md. I would also add a LICENSE file for the scripts and a list of AUTHORS. We could initially just dump them into the main directory and then categorize later, if we have more scripts. I think it would be a good idea to start of with a test suite, though. At least one input and output file for each script to make sure we don't end up with a bunch of broken scripts later on. It also gives users a better idea what the scripts are actually doing.

**Comment by satta** [comment]
To keep things simple we could just have a single directory in the repo with scripts named as described above. I can prepare a template script for your usual GFF/sequence-processing stuff. 
See https://github.com/satta/gt-userscripts for a start.

**Comment by gordon** [comment]
@satta: Looks good to me! Do you want to add it to the genometools organization and we take it from there with our usual pull request workflow?

**Comment by satta** [comment]
Yep, done!

**Comment by gordon** [comment]
Great, thanks! I'll send a pull request for the LICENSE file.

**Comment by sjackman** [comment]
Back to the original topic, should the intron feature inherit the `Name` of its parent, or shall we close this issue as `wontfix`?

**Comment by satta** [comment]
IMHO this is too specific to do in every use of the GtAddIntronsStream. I'd rather see this part of a separate tool. Any other opinions?

**Comment by gordon** [comment]
Seems to be too specific to me, too.

**Comment by sjackman** [comment]
Fair enough.
