### ISSUE TITLE
gt_str_length assertion failed

### ISSUE THREAD

**Issue by esrice** [genometools/genometools#623]
Received this error in 1.5.6:

esrice@edser2 final $ gt
Assertion failed: (gt_str_length(path)), function gt_get_gtdata_path, file src/core/gtdatapath.c, line 48.
This is a bug, please report it at
https://github.com/genometools/genometools/issues
Please make sure you are running the latest release which can be found at
http://genometools.org/pub/
You can check your version number with `gt -version`.
Aborted (core dumped)

I compiled with `make 64bit=yes`

**Comment by satta** [comment]
Hi, thanks for your report! I will look into this but will need some additional information to locate the issue.
Where did you install the `gt` executable? It needs the `gtdata` subdirectory in a specific location, e.g. in the same directory as `gt` itself, or in `/usr/share/genometools`. What is the content of your `$PATH` environment variable? And last but not least, what platform are you running (Linux/Mac OS X/...)?

**Comment by esrice** [comment]
Oh, I installed everything locally and then used a symbolic link to get the
executable in my bin. When I use the full path it works. Thanks!

--
Edward Stallknecht Rice
Ph.D. student, Paleogenomics Lab
Department of Biomolecular Engineering
University of California, Santa Cruz
My website <http://users.soe.ucsc.edu/~esrice/> | Lab website
<http://pgl.soe.ucsc.edu/>

**Comment by satta** [comment]
Great to hear that! However, this should not trigger an assertion so I'll still treat this as a bug to be looked at. Thanks!
