### ISSUE TITLE
gt_error_is_set assertion failed

### ISSUE THREAD

**Issue by esrice** [genometools/genometools#626]
Received this error:

esrice@edser2 final $ ~/software/genometools-1.5.6/bin/gt merge -retainids yes -tidy yes predictions.sorted.gff3 ../../repeats/repeats.gff3 > predictions.merged.gff3
Assertion failed: (!err || !gt_error_is_set(err)), function gt_node_stream_next, file src/extended/node_stream.c, line 89.

**Comment by satta** [comment]
Hi,

thanks for the bug report! Could you probably tell us a bit more about your input file(s)? Would it be possible to isolate a small case triggering the error to make available to us for debugging?

Thanks
Sascha

**Comment by esrice** [comment]
Sure, here are small subsets of the input files and the command and output:

esrice@edser2 final $ ~/software/genometools-1.5.6/bin/gt merge -retainids
yes -tidy yes file1.gff3 file2.gff3 > merged.gff3
Assertion failed: (!err || !gt_error_is_set(err)), function
gt_node_stream_next, file src/extended/node_stream.c, line 89.


--
Edward Stallknecht Rice
Ph.D. candidate, Paleogenomics Lab
Department of Biomolecular Engineering
University of California, Santa Cruz
My website <http://users.soe.ucsc.edu/~esrice/> | Lab website
<http://pgl.soe.ucsc.edu/>


On Tue, Jul 14, 2015 at 11:05 AM, Sascha Steinbiss <notifications@github.com

**Comment by satta** [comment]
Hmm... where are these exactly? I can't see any link or attachment.

**Comment by esrice** [comment]
Oops, Github must not take email attachments. If you give me your email
address I'll forward them.

**Comment by satta** [comment]
Sure, just send them to sascha<at>steinbiss.name. Thanks!
