### ISSUE TITLE
Problem with ReadJoiner outputting incorrect data

### ISSUE THREAD

**Issue by deprekate** [genometools/genometools#631]
In a previous issue thread sample test data was given, and the output from ReadJoiner was shown.  However the output data was incorrect.  It appears ReadJoiner can/will assign a single read to multiple contigs.  This should not happen. 

The test input file was:
```
>1
acgtacgtacgtagc
>2 test
acgatcgatc
>test2
cgtagcatagcgatatgactta
```

And the output (which is incorrect) from ReadJoiner is:
```
>contig_0 length=31 depth=2 0E-->2E
acgtacgtacgtagcatagcgatatgactta
>contig_1 length=29 depth=2 1B-->2E
gatcgatcgtagcatagcgatatgactta
```
___________________________
What happens is the read "test2" is used to build both contigs.  Below is the alignment. 
```
contig_0     acgtacgtacgtagcatagcgatatgactta
1            acgtacgtacgtagc
test2                 cgtagcatagcgatatgactta


contig_1     gatcgatcgtagcatagcgatatgactta
2 (rev)      gatcgatcgt
test2               cgtagcatagcgatatgactta
```

___________________________
The correct output should be "Contig_0" and the singlet sequence ">2".

**Comment by deprekate** [comment]
To show you how completely unusable this error make ReadJoiner, here is a test set of 16S reads, I tried to assemble.
```
$ ls -l 16S.fna
-rw-r--r-- 1 nobody nobody 9168021 Jul 16 17:20 16S.fna

$ head -n 2 16S.fna
>N00405:164:AG482:1:1101:14451:1860
CGTGCCAGCAGCCGCGGTAATACAGAGGGTGCAAACGTTGCTCGGATTTACTGGGCGTAAAGCGCGTGTAGGCGGACTCGCAACTCGGTTGTGAAATCCCTGGGCTCAACCTAGGAACTGCATCCGAAACTGCTTGTCTTGAGTAATGGAGAGGGTGGCGGAATTCCCGGTGTAGAGGTGAAATTCGTAGATATCGGGAGGAACATCAGTGGCGAAGGCGGCCACCTGGACATTTACTGACGCTGAGACGC

$ cat run.sh 
#!/bin/bash
~/opt/gt-1.5.6-Linux_x86_64-64bit-complete/bin/gt readjoiner prefilter -readset test -db 16S.fna
~/opt/gt-1.5.6-Linux_x86_64-64bit-complete/bin/gt readjoiner overlap -readset test -l 2
~/opt/gt-1.5.6-Linux_x86_64-64bit-complete/bin/gt readjoiner assembly -readset test -lengthcutoff 1 -depthcutoff 1

$ ls -l test.contigs.fas 
-rw-rw-r-- 1 nobody nobody 89910267756 Jul 17 18:39 test.contigs.fas
```
**In case you do not see the problem, a 9MB file of reads became a 90GB contig file!**

**Comment by ggonnella** [comment]
Hi, sorry for the late answer. The behavior of Readjoiner you pointed out is on purpose and won't be changed. The original usage case of Readjoiner is genome assembly, not 16S assembly, although it has been used by third-party for this. In this case putting the same read into several contigs, when it is not clear to which one it belong to (i.e. on junction nodes) is legitimate and done also by other string graph based assembler, to which we compared in our paper.
