### ISSUE TITLE
gt extractfeat -translate: Support non-standard genetic codes

### ISSUE THREAD

**Issue by sjackman** [genometools/genometools#638]
See http://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi

**Comment by satta** [comment]
The GtTranslator class used for protein translation actually accepts a GtTransTable, which supports the NCBI defined codes:
https://github.com/genometools/genometools/blob/master/src/core/trans_table_api.h

All that remains is finding a way to get and pass through the choice of table from the user to the translator in a generic way (I could imagine this does not only affect `gt extractfeat`!)

**Comment by sjackman** [comment]
I'd suggest calling this option `gcode` or `genetic-code` after the `tbl2asn` parameter: http://www.ncbi.nlm.nih.gov/genbank/tbl2asn2/

**Comment by standage** [comment]
The answer to most bioinformatics problems: https://www.biostars.org/p/7126/#7136
