### ISSUE TITLE
current master is not scan-build clean

### ISSUE THREAD

**Issue by Garonenur** [genometools/genometools#643]
I dropped splint, because that software got old, but scan-build is pretty current and it finds this error within our master:
```
src/match/seed-extend.c:534:25: warning: Dereference of null pointer (loaded from variable 'perc_mat_history')
      *perc_mat_history = 0; /* case to be implemented */
       ~~~~~~~~~~~~~~~~ ^
```

**Comment by Garonenur** [comment]
but, I have to admit, this function never gets called with a NULL pointer, it always gets a parameter in the form ```&something``` which can afaik not be NULL.

**Comment by satta** [comment]
In this case, an assertion checking for `!=NULL` right in front of the dereferencing line can probably help scan-build recognize that fact.

**Comment by satta** [comment]
Just merged your PR. I guess this can now be closed?

**Comment by Garonenur** [comment]
Yep. Forgot to put the keyword in the commit
