### ISSUE TITLE
Issues with 'ID' description

### ISSUE THREAD

**Issue by magaliruffier** [genometools/genometools#659]
Hi,

We have a GFF3 file containing repeats. They do not have 'ID' fields, as we do not have unique ids, but they have 'description' fields.
For some of those, the description is a string 'ID'.
As far as I am aware, none of this is against GFF3 specifications.
When running gt gff3 with the -retainids option however, the 'ID' description is picked up as an 'ID' with no value and added to the start of the attributes fields.
Is this meant to be or could it be updated to only use 'ID' if it is before the '='?

Thanks,
Magali

**Comment by gordon** [comment]
Could you post an example please?

**Comment by satta** [comment]
I think missing IDs are generally treated as empty when `-retainids` is used.
```
$ cat test.gff3
##gff-version	3
##sequence-region chr123 1 100
chr123	.	gene	1	100	.	+	.	Name=test;description=ID
$ gt gff3 -retainids test.gff3
##gff-version   3
##sequence-region   chr123 1 100
chr123	.	gene	1	100	.	+	.	ID=;Name=test;description=ID
###
```
Should we only have `-retainids` add IDs if they existed in the original annotation?

**Comment by magaliruffier** [comment]
It only seems to happen if there is a 'ID' field
```bash
##gff-version 3
#!genome-build OGE Oryza_brachyantha.v1.4b
1       .       repeat  142     1482    .       -       .       assembly_name=Oryza_brachyantha.v1.4b;description=Gran3_OA_ABa0059I14_367
1       .       repeat  6924    6984    .       +       .       assembly_name=Oryza_brachyantha.v1.4b;description=ID
1       .       repeat  8711    8843    .       +       .       assembly_name=ID;description=Dust
```
```bash
##gff-version   3
#!genome-build OGE Oryza_brachyantha.v1.4b
##sequence-region   1 142 8843
1       .       repeat  142     1482    .       -       .       assembly_name=Oryza_brachyantha.v1.4b;description=Gran3_OA_ABa0059I14_367
1       .       repeat  6924    6984    .       +       .       ID=;assembly_name=Oryza_brachyantha.v1.4b;description=ID
###
1       .       repeat  8711    8843    .       +       .       ID=description;assembly_name=ID;description=Dust
###
```

It then uses anything that is after the 'ID' as the value

**Comment by satta** [comment]
I just had a look, turned out it was a sneaky bug in the attribute data store. The terminal value in a GtTagValueMap can actually also be found as a tag with empty string value, which leads to an artificial empty ID attribute when there is another attribute with the value 'ID'. I have fixed this in an upcoming PR.

**Comment by gordon** [comment]
Thanks @satta for fixing it so quickly! Looks like a sneaky bug indeed.

**Comment by satta** [comment]
@magaliruffier This problem should now be fixed:
```bash
$ gt gff3 -retainids test.gff3 | diff - test.gff3
warning: seqid "1" on line 3 in file "test.gff3" has not been previously introduced with a "##sequence-region" line, create such a line automatically
1c1
< ##gff-version   3
---
> ##gff-version	3
3d2
< ##sequence-region   1 142 8843
```
Now there are no more attribute differences.

**Comment by magaliruffier** [comment]
Thanks for the quick fix, it is all working fine for me now
