### ISSUE TITLE
Valgrind reports

### ISSUE THREAD

**Issue by standage** [genometools/genometools#666]
It has become increasingly difficult to do memory debugging for my software that links to libgenometools on any system newer than Ubuntu 12.04. On Ubuntu 14.xx, Debian Jessie, and the latest Fedoras, running valgrind will generate a ton of error messages. For the most part these look like they are related to very core system functions like malloc and stuff like that.

Are there really widespread issues with memory management that are pervasive across different Linux distributions? Or are these false positives?

Either way, I've tried creating suppressions files (they're massive and I don't have time to manually inspect them) but it never seems to be a comprehensive solution.

I know GenomeTools has its own init and clean functions, which IIRC do some memory auditing. Is all the GT memory debugging included in the library or do you ever use external tools like Valgrind?

**Comment by satta** [comment]
I use Valgrind all the time after doing code modifications to check for memory problems. In fact, you can run the testsuite with the memcheck parameter and it will wrap all test in Valgrind calls. AFAICS the code in libgenometools should be clean in that regard. This is not necessarily true for external code, such as some Cairo functions called by AnnotationSketch, which are not clean and can cause memory errors.

When run on binaries with debugging symbols, Valgrind can give you a call trace of the offending situation, which makes it possible to find out whether it is GenomeTools code or external code that is causing the problem (i.e. whether the leak or invalid access is a result of something GenomeTools is responsible for) or not.

If you could provide some of the Valgrind logs, I could take a look and tell you more.

**Comment by gordon** [comment]
I use Valgrind a lot to test GenomeTools. You can call `testsuite.rb` with option `-memcheck` to activate it. You you can call `make memcheck=yes test`. The only problems we had are with external libraries (cairo).

So it seems to me that there is some problem with your setup.

**Comment by gordon** [comment]
;-) @satta was a few seconds faster.

**Comment by standage** [comment]
I'll post a link to some Valgrind reports in a moment. I did create
suppressions files in the past for pango (related to cairo, correct?) which
I still use for CI on Ubuntu 12.04, but it just seems much more problematic
on 14.04 and other new distros.

More soon...

**Comment by standage** [comment]
Here is some valgrind output from Debian Jessie with `--leak-check=full --show-reachable=yes --gen-supressions=all`.

https://gist.github.com/standage/f7013bd225607acc4d49

**Comment by gordon** [comment]
Do you call `gt_lib_clean()` at the end of your program?

**Comment by standage** [comment]
Yes indeed.

**Comment by standage** [comment]
No, I don't use any of those libraries from my code, only when calling the AnnotationSketch API.

After a few minor fixes to my code (it's been a long time since I've done much testing in `cairo=no` mode), I can confirm that the problem goes away when we drop cairo: Valgrind reports no possible leaks. Go back to regular mode: hundreds of warnings again.

**Comment by satta** [comment]
Well, I assume this points towards GenomeTools not being the main source of the problem here... as I said there are a few issues with these libraries not releasing their static data, etc. Your dump also shows that none of the issues are a result of anything being allocated on GenomeTools' behalf (no `gt_` prefixed functions in the allocation call stack) so I'm afraid there;s not much we can do to help. I would just add the suppressions and/or disable Cairo support for debugging unless you need it.
Does anyone have any other suggestions?

**Comment by gordon** [comment]
I'm afraid, there is not much we can do. Cairo and dependencies are a moving target. If you find problems with libgenometools itself we'll fix it, of course. Can we close the issue?

**Comment by standage** [comment]
Sure. I just ran the test suite with `memcheck=yes` in Ubuntu 14.04 and got the same types of mem leaks. So I guess I just need to spend some more time creating comprehensive suppressions files if I want to do memory debugging on Ubuntu > 12, Debian, or Fedora.
