### ISSUE TITLE
boolean operator precedence issue in compilation

### ISSUE THREAD

**Issue by satta** [genometools/genometools#673]
Here's a compilation issue I found in one of my automated Docker builds (https://hub.docker.com/r/satta/annot-nf/builds/bk7rj366vmtyz7dzxasnwmm/) which compiles GenomeTools as one of its components:
```
src/tools/gt_linspace_align.c: In function 'alignment_with_affine_gap_costs':
src/tools/gt_linspace_align.c:667:61: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses] 
  if (!gt_str_array_size(arguments->diagonalbonds) > 0)
```

**Comment by AnnSeidel** [comment]
I have just made a pull request containing a fix for this issue. 
If you need the fix before it is live replace

<pre><code>!gt_str_array_size(arguments->diagonalbonds) > 0
</code></pre>

with 
<pre><code>gt_str_array_size(arguments->diagonalbonds) == 0
</code></pre>

**Comment by satta** [comment]
Great, thanks! Merged.

**Comment by Garonenur** [comment]
Thanks @AnnSeidel!

if you write
```
fixes #NUMBER
```
in to your commit message, Github will automaticaly close the corresponding issue.
