### ISSUE TITLE
LTRGigest Assertion failed

### ISSUE THREAD

**Issue by jdaron** [genometools/genometools#681]
Hello, 

I am a new user of ltrHarvest and ltrDigest. I used ltrDigest on the chromosome 1 of the Arabidopsis genome as a test, and I got the following error message.
```
Assertion failed: (rval == 0), function gt_ltrdigest_pdom_visitor_feature_node, file src/ltr/ltrdigest_pdom_visitor.c, line 863.
This is a bug, please report it at
https://github.com/genometools/genometools/issues
Please make sure you are running the latest release which can be found at
http://genometools.org/pub/
You can check your version number with `gt -version`.
Abort trap: 6
```
The command line I used are the following: 
```
gt suffixerator -db Chr_1.fas -indexname Chr_1.fas.fsa -tis -suf -lcp -des -ssp -sds -dna
gt ltrharvest -index Chr_1.fas.fsa -mintsd 4 -maxtsd 5 -motif TGCA -motifmis 2 -gff3 chr1LtrH
gt -j 2 ltrdigest -pptlen 10 30 -pbsoffset 0 3 -trnas tRNA.fna -hmms Pfam-A.hmm -outfileprefix mygenome-ltrs chr1LtrH.sorted.gff3 Chr_1.fas.fsa > ltrs_after_ltrdigest.gff3
```
The version of gt is: 
```
gt (GenomeTools) 1.5.7
Copyright (c) 2003-2015 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2015 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: Apple LLVM version 7.0.0 (clang-700.1.76)
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -O3 -m64 -Werror
```
Thanks for helping me to solve the problem.
Josquin

**Comment by satta** [comment]
Hi Josquin, thanks for your report. I will try to reproduce your issue and then get back to you. The calls look OK to me, let me try to find out more.

**Comment by jdaron** [comment]
Thanks, I checked an it seams it is the -hmms option that create the bug, because ltrdigest is running fine without it.

**Comment by satta** [comment]
Yes, it looks like it. Since using the whole of Pfam as a set of domains to search for, your command might create a lot of output files, one per found domain. I had to increase the number of allowed open files with ulimit before I got it to finish (which it did, successfully). That was obviously a different error message, but might be worth trying just to pin down the problem.

**Comment by satta** [comment]
I took another look at the source and the code the line referenced fails if there are too many file descriptors open in the system, which suggests that your problem indeed relates to this issue. Did increasing the number of file descriptors solve your problem? E.g.:

    sysctl -w kern.maxfiles=20480

**Comment by satta** [comment]
I have added a proper error message:
```
$ gt -j 2 ltrdigest -pptlen 10 30 -pbsoffset 0 3 -trnas tRNA.fna -hmms Pfam-A.hmm -outfileprefix mygenome-ltrs chr1LtrH.sorted.gff3 Chr_1.fas.fsa > ltrs_after_ltrdigest.gff3
could not create pipe, please check for number of allowed file descriptors: Too many open files
```
Please let me know if changing the maxfiles setting fixed things for you.

**Comment by satta** [comment]
I have just pushed #702 which addresses this issue by only keeping a constant amount of files open per LTRdigest run. This should fix this problem in general.
