### ISSUE TITLE
1.5.7 does not compile on OSX

### ISSUE THREAD

**Issue by JohnLonginotto** [genometools/genometools#683]
Get the error:

    mac850:genometools-1.5.7 2 John$ make
    ls: 2/src/match/*.c: No such file or directory
    ls: 2/src/match/*.c: No such file or directory
    find: 2: No such file or directory
    [compile sqlite3.o]
    clang: error: no such file or directory: '2/src'
    clang: error: no such file or directory: '2/obj'
    clang: error: no such file or directory: '2/src/external/zlib-1.2.8'
    clang: error: no such file or directory: '2/src/external/md5-1.1.2/src'
    clang: error: no such file or directory: '2/src/external/lua-5.1.5/src'
    clang: error: no such file or directory: '2/src/external/luafilesystem-1.5.0/src'
    clang: error: no such file or directory: '2/src/external/lpeg-0.10.2'
    clang: error: no such file or directory: '2/src/external/expat-2.0.1/lib'
    clang: error: no such file or directory: '2/src/external/bzip2-1.0.6'
    clang: error: no such file or directory: '2/src/external/samtools-0.1.18'
    clang: error: no such file or directory: '2/src/external/sqlite-3.8.7.1'
    clang: error: no such file or directory: '2/src/external/tre/include/tre'
    clang: error: no such file or directory: '2/src/external/sqlite-3.8.7.1'
    make: *** [obj/src/external/sqlite-3.8.7.1/sqlite3.o] Error 1

This happens whether i install the extra dependancies via brew or not. 1.5.6 however compiles without issue. I'm running Yosemite 10.10.5. Also, separate point, the INSTALL file for 1.5.7 has a little typo:

    - 64bit=no         to compile a 32-bit version
    - 32bit=yes        to compile a 32-bit version

**Comment by satta** [comment]
Hi John, thanks for your report. 

It appears to me that the name of your current working directory is interesting... is there a space in the directory name, e.g. `genometools-1.5.7 2`? I get the same errors you do when I try to build in a directory with such a name. GenomeTools builds well after I remove the space from the directory name.

About the INSTALL file: indeed both parameters build a 32-bit version, so IMHO the lines are correct. If `64bit=no` then 32 bit is implicitly chosen, this is also the case with `32bit=yes`.

**Comment by JohnLonginotto** [comment]
Ah yes, you're absolutely right, its the space in the directory name that causes it. I'm a bit embarrassed that I didn't see that before ;)
And again you are absolutely right about the INSTALL file, i didn't see the no/yes. If the two are mutually exclusive though, perhaps a --32bit is all thats needed?

**Comment by satta** [comment]
Good to hear we found the problem and it now works for you.
About the compile flags, we would like to continue supporting legacy behaviour which also uses the `64bit` make flag. I think that is a minor point though that could also be addressed by better wording in the INSTALL file. I'll keep this on my agenda -- thanks!
