### ISSUE TITLE
spaces in GFF version string

### ISSUE THREAD

**Issue by satta** [genometools/genometools#685]
GenomeTools outputs three spaces between the `##gff-version` directive and the version number, see:
https://github.com/genometools/genometools/blob/master/src/extended/gff3_visitor.c#L76

While the spec does not define the spaces between the directive and the value, some tools are restrictive about this, e.g. Bioconductor’s makeTxDbFromGFF produces as a warning message:
```
Warning message:
In .local(con, format, text, ...) :
  gff-version directive indicates version is   3, not 3
```
Is there a specific reason why three spaces were chosen?

**Comment by gordon** [comment]
That how the examples were in an early version of the GFF3 specification (see commit 52cb554e0052c064125423f8aad77e8b01b229ca). I'm OK with changing it to one space, our parser can handle both cases.

**Comment by Garonenur** [comment]
those 3 spaces from the example were probably a result of some right aligned printing of the version number? And not due to fixed 3 spaces.

**Comment by satta** [comment]
OK, so we can make that change. We will just have to adjust the test data because the reference output (getting `diff`ed) has three spaces...

**Comment by gordon** [comment]
@Garonenur: I think there was no special reason for. I just put it in there to have the exact same output like the example files in the spec at the time.

@satta: Yes, there will be many files to change in testdata...

**Comment by satta** [comment]
I will work on the change to one space.

**Comment by standage** [comment]
As a side note, is there any public forum for commenting on the GFF3 spec? I know SO used to keep a bug tracker for term requests at SourceForge (looks like it's [on GitHub now](https://github.com/The-Sequence-Ontology/SO-Ontologies/issues), thank goodness). Is there anything similar for GFF3? An update to the spec clarifying these kinds of things would be nice: should `##gff-version` and `3` be separated by exactly one space, or exactly one tab, or 1 or more whitespace characters, or something else?

**Comment by standage** [comment]
GenomeTools strikes a very good balance between strictly enforcing the spec and handling ambiguous cases. Most GFF3 processing software is half-baked: the author sees a few GFF3 files, they treat certain conventions as gospel truth, and then throw errors like what's above. On one hand making the spec more specific could help, but on the other hand we don't want the spec to get too cluttered or pedantic. This is a tough social optimization problem.

**Comment by gordon** [comment]
I don't know of any public forum for commenting on the GFF3 spec. Having the spec in Markdown format in a git repository on GitHub would be great. That would allow to have a discussion place (issue tracker) and pull requests for changes. It would also provide a history of changes. For example, now the spec has examples of the form `##gff-version 3.2.1` where 2 is a major and 1 a minor revision number. But it totally unclear to me how that got into the spec and what it means practically. E.g., how are we supposed to deal with different version numbers when working with multiple GFF3 files at the same time?

I'm glad you see it that way. When I started writing the GFF3 parser for GenomeTools it was too strict. That approach clashed with reality and I had to loosen it up a little :smile: Now my approach is to be somewhat flexible on the input side but very strict on the output side.

Concerning the social optimization problem: I think the problems with many specifications is that they come without a reference implementation. Unfortunately, it's much easier to write something in a spec than actually implementing it. But only with the actual implementation it becomes clear which parts are good and which ones are too complicated. For example, the multi-line features in GFF3 caused me a lot of pain to implement and it would be possible to do without them. IMHO most successful projects always have both: a good spec and a good reference implementation. A spec without an implementation easily leads to feature creep. An implementation without a spec makes it very hard for other implementers and usually has many unintended corner cases.

**Comment by satta** [comment]
I would probably make sense to discuss approaches to handle version differences in another ticket. Should we close this one?

BTW, I agree that being tolerant (`-tidy`) on the input side but strict on the output side is a good idea. 
Sometimes I am tempted to even take this further, i.e. to just drop input features with invalid parent references instead of bailing out hard and stopping processing (this happens from time to time for me as the storage backend I work with does not propagate parent deletion to the children).

**Comment by satta** [comment]
About the GFF3 spec development, the most 'public' forum I can think of if probably the SO wiki. They seem to have some content dedicated to GFF3 development (http://www.sequenceontology.org/so_wiki/index.php?search=gff3). At least that's where I could discuss some points of the spec with the developers (for me that was http://www.sequenceontology.org/so_wiki/index.php/TEs_in_the_spec)

**Comment by gordon** [comment]
Yes, let's close this.

**Comment by satta** [comment]
FYI, in the meantime a GitHub repo with the official specifications has been set up: https://github.com/The-Sequence-Ontology/Specifications
