### ISSUE TITLE
MinGW builds on Travis

### ISSUE THREAD

**Issue by gordon** [genometools/genometools#692]
I'm trying to setup automatic MinGW build on Traivs: https://github.com/gordon/genometools/commit/582e363c9e2d67fb981a351341a50e9e1057f47a, but the test fail: https://travis-ci.org/gordon/genometools/builds/92092376

The problem seems to be that the SYSTEM=Windows environment variable is not passed through to   `scripts/travis_test.rb`. I'm wondering if `env = {}` in the scripts resets the complete environment. But if it does, that it is weird that the tests with `cairo=no` build correctly.

@Garonenur: Do you have any idea how to fix this problem? It would be really cool to have the MinGW builds run automatically.

**Comment by Garonenur** [comment]
`cairo=no` is the default now, I think. I pulled your branch, and will test this.

**Comment by Garonenur** [comment]
it says in the terminal output of travis: `export SYSTEM=Windows` so this should be all right. the `env = {}` is only set in some cases, which we should adjust, if you only want to test compilation on windows.

**Comment by Garonenur** [comment]
I testet, with irb:
```
irb(main):006:0> IO.popen([ {'foo' => 'bar'}, 'env', {:err=>[:child, :out]}]) do |io|
irb(main):007:1* while line = io.gets
irb(main):008:2> print line
irb(main):009:2> end
irb(main):010:1> end
```
which prints out the usual environment variables, which in your case would contain `SYSTEM=Windows` and also `foo=bar` at the end. So the problem doesn't seem to be the ruby handling of the environment.

**Comment by satta** [comment]
I just took a quick look, but isn't `SYSTEM` overwritten in the Makefile anyway:
```
SYSTEM:=$(shell uname -s)
```
(https://github.com/gordon/genometools/blob/wincompile/Makefile#L84)

**Comment by Garonenur** [comment]
then a simple `SYSTEM?=$(shell uname -s)` could fix it?

**Comment by satta** [comment]
That's what I would try...

**Comment by Garonenur** [comment]
will do.

**Comment by Garonenur** [comment]
I have tested that, now it still fails, but with different errors: https://travis-ci.org/Garonenur/genometools/jobs/92737634 @gordon, please have a look at it. I created a PR for your branch, so you can pull my changes and work from there. I will be able to maybe look at it again end of the week.

**Comment by satta** [comment]
Looking at:
```
bin/gt: 1: bin/gt: MZ����@���: not found
bin/gt: 3: bin/gt: Syntax error: ")" unexpected
```
obviously the Linux based Travis boxes can't execute Windows binaries ;)

**Comment by Garonenur** [comment]
well thats stupid (of me) I tried to run `gt -test` with them as with the other "only compile" tests but obviously this won't work. But the compilation was a success, so I just change the travis-script and this should be done.

**Comment by gordon** [comment]
Thanks @Garonenur for fixing this! Weird that `scripts/build_windows.sh` worked despite the overwriting of `SYSTEM` in the Makefile.
