### ISSUE TITLE
gff3validator 

### ISSUE THREAD

**Issue by 52teth** [genometools/genometools#700]
**when I run gt sketch use the following cmd：**
```
 gt sketch -addintrons -flattenfiles -width 2000 /GTPlot/png/g005440.2.png   /GTPlot/gtf/g005440.2.gff3 
```
**the folowing error occours:**
```
/genometools/1.5.7/bin/gt sketch: error: CDS feature on line 5 in file "/GTPlot/gtf/g005440.2.gff3" has the wrong phase . (should be 0)
```
**Here is the "/GTPlot/gtf/g005440.2.gff3" file:**
```
##gff-version 3.2.1
##sequence-region   1  308637  312423
1	Cufflinks	gene	308637	312423	.	+	.	ID=t01g005440.2
1	Cufflinks	mRNA	308637	312423	.	+	.	ID=t01g005440.2.new1;Parent=t01g005440.2
1	Cufflinks	CDS	308637	309207	.	+	.	Parent=t01g005440.2.new1
1	Cufflinks	CDS	310220	310362	.	+	.	Parent=t01g005440.2.new1
1	Cufflinks	CDS	310724	310908	.	+	.	Parent=t01g005440.2.new1
1	Cufflinks	CDS	311118	311208	.	+	.	Parent=t01g005440.2.new1
1	Cufflinks	CDS	311352	311685	.	+	.	Parent=t01g005440.2.new1
1	Cufflinks	CDS	311834	311891	.	+	.	Parent=t01g005440.2.new1
1	Cufflinks	CDS	312006	312423	.	+	.	Parent=t01g005440.2.new1
1	Cufflinks	mRNA	308844	312423	.	+	.	ID=t01g005440.2.new3;Parent=t01g005440.2
1	Cufflinks	CDS	308844	309207	.	+	.	Parent=t01g005440.2.new3
1	Cufflinks	CDS	310220	310362	.	+	.	Parent=t01g005440.2.new3
1	Cufflinks	CDS	310820	310908	.	+	.	Parent=t01g005440.2.new3
1	Cufflinks	CDS	311118	311208	.	+	.	Parent=t01g005440.2.new3
1	Cufflinks	CDS	311352	311685	.	+	.	Parent=t01g005440.2.new3
1	Cufflinks	CDS	311834	311891	.	+	.	Parent=t01g005440.2.new3
1	Cufflinks	CDS	312006	312423	.	+	.	Parent=t01g005440.2.new3
...
```
**What can I do with this problem?**
**Thanks for any adviceO(∩_∩)O~**

**Comment by satta** [comment]
Your GFF3 is missing phase information for your CDS features, which is mandatory as per the GFF3 specification:
> CDS features MUST have have a defined phase field. Otherwise it is not possible to infer the correct polypeptides corresponding to partially annotated genes. 

You can simply add these by using the `-tidy` option for `gt gff3` as follows:
```
gf gff3 -tidy -retainids -sort GTPlot/gtf/g005440.2.gff3 >  GTPlot/gtf/g005440.2.clean.gff3
```
and then use the new file `g005440.2.clean.gff3` for sketching.

**Comment by 52teth** [comment]
thanks a lot @satta ;-)
I have installed the genometools in from http://genometools.org/pub/, and there is no "gf" tools in my genomeTools. So should I  install the genometools again from github?

**Comment by satta** [comment]
Oops, I meant `gt` of course! Sorry for the typo.

**Comment by 52teth** [comment]
I'll have a try.
Thanks a lot @satta ~\(≧▽≦)/~

**Comment by 52teth** [comment]
It works well. Thanks againO(_)O @satta
