### ISSUE TITLE
How to set style file for genome mode comparision from two samples?

### ISSUE THREAD

**Issue by 52teth** [genometools/genometools#701]
I have got two set of genome annotiation stored in two gff3 files. Now I want to see the difference between the gff3 files by gt sketch tool. But the current ‘gt sketch’  can only set the same style for each feature. So I wonder if there is a simple way to plot by by changing the  style file (eg. setting different colors for exon from two files)?

Thanks for any replyO(∩_∩)O

**Comment by standage** [comment]
You may consider taking a look at the ParsEval tool that comes with the
AEGeAn Toolkit (http://standage.github.io/AEGeAn).
On Sat, Nov 28, 2015 at 4:05 AM 52teth <notifications@github.com> wrote:

> I have got two set of genome annotiation stored in two gff3 files. Now I
> want to see the difference between the gff3 files by gt sketch tool. But
> the current ‘gt sketch’ can only set the same style for each feature. So I
> wonder if there is a simple way to plot by by changing the style file (eg.
> setting different colors for exon from two files)?
>
> Thanks for any replyO(∩_∩)O
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genometools/genometools/issues/701>.
>
-- 
Daniel Standage
Ph.D. Candidate
Computational Genome Science Lab
Indiana University

**Comment by 52teth** [comment]
Ok! I'll have a try. Thanks very much!

**Comment by satta** [comment]
Yes, I also think ParsEval does what you want. I'm also using it for something like this.

BTW, you can assign separate colours for features from each file like this:
```Lua
  exon = {
    -- Color definitions
    stroke             = {red=0.0, green=0.0, blue=0.0, alpha = 1.0},
    stroke_marked      = {red=1.0, green=0.0, blue=0.0},
    fill               = function (fn)
                           if fn:get_filename() == 'testdata/eden.gff3' then
                             return {red=0.9, green=0.1, blue=0.1}  -- red
                           else
                             return {red=0.1, green=0.9, blue=0.1}  -- green
                           end
                         end,
    style              = "box",
    -- Collapsing options
    collapse_to_parent = true,
    split_lines        = true,
    -- Caption options
    max_capt_show_width= nil,
    -- Display this track only if the viewport is not wider than this
    -- number of nucleotides. Set to 0 to disable type track.
    max_show_width     = nil,
  },
```

For example, running
```
gt sketch -flattenfiles -force -style perfile.style out.png testdata/eden.gff3 testdata/eden_only_annotation.gff3
```

from the GenomeTools directory with a changed style file in `perfile.style` results delivers the following:

![out](https://cloud.githubusercontent.com/assets/27732/11452239/f670977e-95d8-11e5-8843-0f02de45534f.png)

**Comment by 52teth** [comment]
@satta You were terrific! That is just what I want😍

**Comment by satta** [comment]
Glad to be of help :)

**Comment by satta** [comment]
BTW, feel free to close this issue when you think your question has been addressed.
