### ISSUE TITLE
How to plot a fusion gene located in two chromosome by genometools?

### ISSUE THREAD

**Issue by 52teth** [genometools/genometools#705]
I have tried to use genometools to plot two genes from a chromosome, I turned out pretty good. Now I wonder if I can use genometools to plot a gene located in two different chromosomes, just like fusion genes?
And how to plot?
Thanks for your time and Look forward to any adviceO(∩_∩)O

**Comment by satta** [comment]
I am afraid this is not directly possible. AnnotationSketch only plots loci on the same chromosome per diagram.
If you want to prepare a figure for a paper etc. and you need to create such plots of only one fused locus (or just a few), you can generate separate plots for each region on the different chromosomes in SVG format and then edit them later to arrange the fused counterparts in whatever way you want. I've done something like that before using Inkscape.
