### ISSUE TITLE
LTRdigest does not appear to be chaining domain matches

### ISSUE THREAD

**Issue by sestaton** [genometools/genometools#706]
My understanding is that LTRdigest should be chaining split overlapping domain matches together. From the LTRdigest paper under the section "Protein domain detection" it says, "In the case of
frame shifts, it is possible to obtain multiple partial hits per protein domain occurring in different reading frames. If more than one hit per domain model is found in a candidate, individual hits are combined using a chaining algorithm.." Though, I am not clear why I am seeing predictions such as the one below: 

    Contig57_HLAC-254L24    LTRharvest      repeat_region   60096   68658   .       +       .       ID=repeat_region4
    Contig57_HLAC-254L24    LTRharvest      target_site_duplication 60096   60100   .       +       .       Parent=repeat_region4
    Contig57_HLAC-254L24    LTRharvest      inverted_repeat 60101   60102   .       +       .       Parent=repeat_region4
    Contig57_HLAC-254L24    LTRharvest      LTR_retrotransposon     60101   68653   .       +       .       ID=LTR_retrotransposon4;Parent=repeat_region4;ltr_similarity=99.35;seq_number=0
    Contig57_HLAC-254L24    LTRharvest      long_terminal_repeat    60101   61950   .       +       .       Parent=LTR_retrotransposon4
    Contig57_HLAC-254L24    LTRdigest       protein_match   62716   62977   5.7e-11 +       .       Parent=LTR_retrotransposon4;name=Retrotrans_gag;reading_frame=2
    Contig57_HLAC-254L24    LTRdigest       protein_match   64173   64419   3.9e-11 +       .       Parent=LTR_retrotransposon4;name=RVT_1;reading_frame=1
    Contig57_HLAC-254L24    LTRdigest       protein_match   64384   64654   2.7e-17 +       .       Parent=LTR_retrotransposon4;name=RVT_1;reading_frame=2
    Contig57_HLAC-254L24    LTRdigest       protein_match   65706   66042   2.6e-13 +       .       Parent=LTR_retrotransposon4;name=rve;reading_frame=1
    Contig57_HLAC-254L24    LTRdigest       RR_tract        66789   66796   .       +       .       Parent=LTR_retrotransposon4
    Contig57_HLAC-254L24    LTRharvest      long_terminal_repeat    66803   68653   .       +       .       Parent=LTR_retrotransposon4
    Contig57_HLAC-254L24    LTRharvest      inverted_repeat 61949   61950   .       +       .       Parent=repeat_region4
    Contig57_HLAC-254L24    LTRharvest      inverted_repeat 66803   66804   .       +       .       Parent=repeat_region4
    Contig57_HLAC-254L24    LTRharvest      inverted_repeat 68652   68653   .       +       .       Parent=repeat_region4
    Contig57_HLAC-254L24    LTRharvest      target_site_duplication 68654   68658   .       +       .       Parent=repeat_region4

I would expect the two RVT_1 matches in this element to be chained together. Some of these cases can be filtered with the domain match cutoff method and e-value threshold, but in this example, these appear to be very strong matches that would not be filtered by a sensible threshold. Is there a reason why they are split?

**Comment by satta** [comment]
Chaining here does not mean that hit features are _merged_ into one feature, it only means that if there are multiple HMMER hits for the same model  that are colinear, i.e. in the same order on the model and the sequence, then a combination of those will be picked that is 'best' in terms of distance to or overlap with each other as well as the sum of the lengths of the hits. This is to find the best set of matches in situations with multiple frameshifts and/or nested insertions to be able to create a good protein sequence for clustering.
In your case, the situation is as expected in my opinion: the feature contains a chain of two hits to RVT_1 on different reading frames, as they would be created if there was a frame shift in the sequence coding for the RVT domain (see figure below, +0/+1/+2 are reading frames). They overlap slightly as HMMER hits are not always very accurate down to a single nucleotide.

![screen shot 2015-12-03 at 09 52 48](https://cloud.githubusercontent.com/assets/27732/11557276/c501e606-99a3-11e5-91f6-66c26e6fdb52.png)

I hope that explains what the chaining means in this context, let me know if you have more questions.

**Comment by sestaton** [comment]
Thanks for the thorough response, that does clarify how the chaining works. In terms of extracting the domain sequences, does LTRdigest write a separate sequence for each hit (one for each match in the chain of best hits), or would the hits be merged to extract one RVT_1 sequence as in the example above? If so, it seems like this would only make sense for overlapping hits as merging non-overlapping hits might result in merging multiple domains.

**Comment by sestaton** [comment]
Last question on the subject, before you answer. Would the same rules apply to the domain finding of the `gt tirvish` command?

**Comment by satta** [comment]
@sestaton: With regard to your first question: IIRC when you use the `-aaout` option in LTRdigest then you will get a concatenation of both translated fragments for the RVT_1 model for this candidate.
It does not try to resolve overlaps and gaps, but still I would consider the result suitable for clustering.

Second question: TIRvish uses the same component for pHMM matching and chaining as LTRdigest, so the behaviour is the same. Btw, it's nice to see you are actually using TIRvish as it is currently not really promoted ;) I would be happy to hear if you find it useful for your purposes.

**Comment by sestaton** [comment]
Thanks for the response, and I will be happy to provide feedback on TIRvish.
