### ISSUE TITLE
Error in make 

### ISSUE THREAD

**Issue by sajanraju** [genometools/genometools#707]
HI,

I am getting an error when I am trying to run the "make"  ( ver 1.5.7) command in linux

[compile extract_feature_stream.o]
src/extended/extract_feature_stream.c:58:2: error: no newline at end of file
make: *** [obj/src/extended/extract_feature_stream.o] Error 1

How can I solve this? any help would be appreciable.

Thanks

**Comment by satta** [comment]
Interesting that your compiler would complain about this... Can you try compiling with the `errorcheck=no` parameter, i.e.:
```
make errorcheck=no
```
This should tell the compiler to treat this as a warning rather than as an error and allow your build to continue.

**Comment by sajanraju** [comment]
Hey..
Thank you. it worked. :)

**Comment by satta** [comment]
Sure, glad to be of help. Just out of curiosity, could you let me know your compiler and distribution to get an idea of whether this may also affect others? Thanks!

**Comment by sajanraju** [comment]
$cat /proc/version
Linux version 2.6.18-371.3.1.el5 (mockbuild@builder10.centos.org) 
(gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)) #1 SMP Thu Dec 5 12:47:02 EST 2013

is this what you were asking for?

**Comment by satta** [comment]
I can see that this is a CentOS system, so you can get the exact version with
```
cat /etc/centos-release
```
and the compiler version with
```
gcc -v
```

**Comment by sajanraju** [comment]
[sraju@mars ~]$ cat /etc/centos-release
cat: /etc/centos-release: No such file or directory

[sraju@mars ~]$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/u                                                              sr/share/info --enable-shared --enable-threads=posix --enable-checking=release -                                                              -with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-                                                              libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable                                                              -java-awt=gtk --disable-dssi --disable-plugin --with-java-home=/usr/lib/jvm/java                                                              -1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=x86_64-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-55)

[sraju@mars ~]$ cat /etc/redhat-release
CentOS release 5.10 (Final)
[sraju@mars ~]$

**Comment by satta** [comment]
Thanks! These seem to be pretty dated so that may be why we didn't run into this case before.
