### ISSUE TITLE
Building without Cairo?

### ISSUE THREAD

**Issue by peterjc** [genometools/genometools#708]
I would like to just use the Python API for https://github.com/sanger-pathogens/gff3toembl but do not need any of the graphical functionality in genometools.

I read the README and skimmed the make file, but it was not obvious is you can build gt without Cairo (which I'm guessing is only used in AnnotationSketch?).

**Comment by satta** [comment]
Indeed it is only used in AnnotationSketch. You can build a GenomeTools version without Cairo by appending `cairo=no` to the make call. Please remember to run `make cleanup` first if you have already tried a build with a different parameter set.

**Comment by peterjc** [comment]
Now you've pointed that out, I can see it in the README. Opps. Thanks!
