### ISSUE TITLE
Python wrapper does not expose __version__

### ISSUE THREAD

**Issue by peterjc** [genometools/genometools#712]
Following Python convention, I would expect this to print the genometools Python wrapper version number:

```
$ python2.7 -c "import gt; print(gt.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'
```

Ideally the version string contents should follow PEP693 http://legacy.python.org/dev/peps/pep-0396/ so I would have expected:

```
$ python2.7 -c "import gt; print(gt.__version__)"
1.5.7
```

**Comment by satta** [comment]
Thanks for the info! I wrote the bindings when Python was fairly new to me so I wasn't too familiar with all the PEPs... I will add this to the module and probably also push some of my Python 3 work later (after running autopep8 as well).

**Comment by peterjc** [comment]
Excellent news - Python 3 support would be great for https://github.com/sanger-pathogens/gff3toembl/issues/40 - thanks!

**Comment by satta** [comment]
OK. Be aware, I only got the tests (which could use some extending as well) to pass on both 2.7 and 3.5, not tried running gff3toembl with the new version.

**Comment by peterjc** [comment]
Lovely - I'll have to try this for my next ENA submission, thank you :+1:
