### ISSUE TITLE
Linesort option fails if second column has a space in it

### ISSUE THREAD

**Issue by cmdcolin** [genometools/genometools#716]
I was testing out the "gt gff3 -linesort" option and it was failing with this error

    Assertion failed: (p1s != 0), function gt_linesorted_gff3_cmp, file src/extended/gff3_linesorted_out_stream.c, line 96.
    This is a bug, please report it at
    https://github.com/genometools/genometools/issues
    Please make sure you are running the latest release which can be found at
    http://genometools.org/pub/
    You can check your version number with `gt -version`.
    Abort trap: 6

When I checked out the GFF3 it looked like it was caused when the second column had a spaces in it(at least, when I replaced instances of "Curated Genomic" in second column with "Curated_Genomic", the error went away). Maybe either -tidy could fix that up, or the linesort option could handle it?

Tested with 1.5.6 and 1.5.7 and latest unstable.

Thanks for the great tool :)!

**Comment by satta** [comment]
Confirmed, whitespace in these fields was not expected but should be handled correctly. Thanks for reporting this! 
I have a fix ready and will open a PR later, when I have had the time to add some tests.
