### ISSUE TITLE
ltrharvest function gt_evalxdroparbitscoresextend bug

### ISSUE THREAD

**Issue by blauga** [genometools/genometools#720]
Hello,

I'm doing some testing with ltrharvest from genometools 1.5.7 using the rice chr1 sequence found below.

ftp://ftp.plantbiology.msu.edu/pub/data/Eukaryotic_Projects/o_sativa/annotation_dbs/pseudomolecules/version_7.0/chr01.dir/Chr1.seq

For testing, I'm following example 3.1 from the ltrharvest user manual.

http://www.zbh.uni-hamburg.de/fileadmin/gi/LTRharvest/ltrharvestman.pdf

Here is my suffixerator command, which completed without error.

<pre><code>$ gt suffixerator -db Chr1.seq -indexname Chr1.fsa -tis -suf -lcp -des -ssp -sds -dna</code></pre>

...and my ltrharvest command that is generating an error. The error message indicates that this is a bug, but I'm new to the tool so I may be missing something simple.

<pre><code>$ gt ltrharvest -index Chr1.fsa
# args=-index Chr1.fsa
# predictions are reported in the following way
# s(ret) e(ret) l(ret) s(lLTR) e(lLTR) l(lLTR) s(rLTR) e(rLTR) l(rLTR) sim(LTRs) seq-nr 
# where:
# s = starting position
# e = ending position
# l = length
# ret = LTR-retrotransposon
# lLTR = left LTR
# rLTR = right LTR
# sim = similarity
# seq-nr = sequence number
Assertion failed: (ulen != 0 && vlen != 0), function gt_evalxdroparbitscoresextend, file src/match/xdrop.c, line 250.
This is a bug, please report it at https://github.com/genometools/genometools/issues.</code></pre>

**Comment by stefan-kurtz** [comment]
Since the last release of gt I have fixed some issues in the file 
containing the assertion which failed.
So please try the current unstable version of genometools, available at

http://www.genometools.org/pub/genometools-unstable.tar.gz

If the problem still persists, please contact me again. Bye, Stefan


On 01/04/2016 10:23 PM, blauga wrote:
>
> Hello,
>
> I'm doing some testing with ltrharvest from genometools 157 using the 
> rice chr1 sequence found below
>
> ftp://ftpplantbiologymsuedu/pub/data/Eukaryotic_Projects/o_sativa/annotation_dbs/pseudomolecules/version_70/chr01dir/Chr1seq
>
> For testing, I'm following example 31 from the ltrharvest user manual
>
> http://wwwzbhuni-hamburgde/fileadmin/gi/LTRharvest/ltrharvestmanpdf
>
> Here is my suffixerator command, which completed without error or output
>
> $ gt suffixerator -db Chr1seq -indexname Chr1fsa -tis -suf -lcp -des 
> -ssp -sds -dna
>
> and my ltrharvest command that is generating an error The error 
> message indicates that this is a bug, but I'm new to the tool so may 
> be missing something simple
>
> $ gt ltrharvest -index Chr1fsa
>
>
>   args=-index Chr1fsa
>
>
>   predictions are reported in the following way
>
>
>   s(ret) e(ret) l(ret) s(lLTR) e(lLTR) l(lLTR) s(rLTR) e(rLTR) l(rLTR)
>   sim(LTRs) seq-nr
>
>
>   where:
>
>
>   s = starting position
>
>
>   e = ending position
>
>
>   l = length
>
>
>   ret = LTR-retrotransposon
>
>
>   lLTR = left LTR
>
>
>   rLTR = right LTR
>
>
>   sim = similarity
>
>
>   seq-nr = sequence number
>
> Assertion failed: (ulen != 0 && vlen != 0), function 
> gt_evalxdroparbitscoresextend, file src/match/xdropc, line 250
> This is a bug, please report it at 
> https://githubcom/genometools/genometools/issues
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/genometools/genometools/issues/720>.
>


-- 
Prof. Dr. Stefan Kurtz
Zentrum fuer Bioinformatik
Universitaet Hamburg
Bundesstrasse 43
20146 Hamburg
Germany

Email:  kurtz@zbh.uni-hamburg.de
URL:    http://www.zbh.uni-hamburg.de/kurtz
Phone:  +49 (40) 42838 7311
FAX:    +49 (40) 42838 7312

**Comment by blauga** [comment]
Stefan, thanks for your time. The issue is indeed fixed in the unstable version.
