### ISSUE TITLE
1.5.8 release?

### ISSUE THREAD

**Issue by standage** [genometools/genometools#721]
Several features have been modified/fixed since 1.5.7. In particular, the spacing of the version number in the `gff-version` pragma is something I'm eager to resolve with a stable release. Some of AEGeAn's functional tests rely on diffs that fail with the new behavior. I don't want to handle this until 1.5.8 is stable.

If the 1.5.8 release isn't already scheduled, consider this a request! :-)

**Comment by satta** [comment]
OK with me, any comments?

**Comment by gordon** [comment]
Fine with me. Since we already had bug reports for problems which were already fixed in the meantime we should push this out.

**Comment by satta** [comment]
OK. Are there any additions to the CHANGELOG? I have added some but don't have a complete picture of what happened in the commits concerning linear space alignments...

**Comment by satta** [comment]
Ok, now just waiting for #725 to come through and then I will wrap up the release tonight.

**Comment by gordon** [comment]
Great, thanks @satta!

**Comment by satta** [comment]
Tag is pushed and tarballs/binaries on http://genometools.org/pub updated. As usual, Windows binaries and Debian packages will follow soon.

**Comment by standage** [comment]
![image](https://cloud.githubusercontent.com/assets/566823/12182831/c31e520e-b558-11e5-8053-c7a4e4f7d805.png)

**Comment by satta** [comment]
Excellent!
