### ISSUE TITLE
Typo on http://genometools.org/license.html

### ISSUE THREAD

**Issue by teythoon** [genometools/genometools#741]
The page reads "We chose one of the most simple and free licenses, the ICS license.", which imho should be "ISC license"

**Comment by gordon** [comment]
You are correct, thanks for pointing that out!

**Comment by teythoon** [comment]
LICENSE also contains the typo.

**Comment by gordon** [comment]
Fixed it, too. Thanks! Please feel free to send us pull requests, http://genometools.org/contract.html describes our development process.

**Comment by teythoon** [comment]
Sure, and I have ;).  I just wasn't sure how the website is developed.

**Comment by gordon** [comment]
Yes, I took note of that ;)

FYI: The website lives in `www/` with parts being written manually (like the license.html file) and parts being generated with `make docs`. @satta or I have to push changes to the server.
