### ISSUE TITLE
use of ENV['PATH'] in python_tests_runnable?

### ISSUE THREAD

**Issue by stefan-kurtz** [genometools/genometools#750]
I run tests with a minimum environment setting only one env variable (see below). So in particular,
PATH is not defined, but this is now  required to test whether python is available. 
This causes an erro, see belowr. I think we need to check ENV.has_key?("PATH") before accessing
ENV["PATH"]. What's the option?

roma [1162] cd testsuite/
roma [1163] env -i GT_MEM_BOOKKEEPING=on ./testsuite.rb -threads 2 -keywords gt_encseq
which: no makeblastdb in ((null))
which: no blastn in ((null))
which: no blastp in ((null))
./testsuite.rb:131:in `python_tests_runnable?': undefined method `split' for nil:NilClass (NoMethodError)
        from ./testsuite.rb:198:in `<main>'

**Comment by satta** [comment]
Closed via #751

**Comment by Garonenur** [comment]
we might want to remove the remaining 'which' uses within the tests also.

**Comment by satta** [comment]
```
[satta@tortuga:~gt/testsuite] $ git grep which 
gt_condenseq_include.rb:makeblastdb = system("which makeblastdb")
gt_condenseq_include.rb:blastn      = system("which blastn")
gt_condenseq_include.rb:blastp      = system("which blastp")
```

I think in these cases it is not a problem because the code there checks the resulting status code only. So if there is no `$PATH` then I guess this is just a regular failure and handled as such. The buggy code  Stefan found always assumed a `$PATH` is set.
