### ISSUE TITLE
broken 32-bit build

### ISSUE THREAD

**Issue by gordon** [genometools/genometools#754]
@teythoon: PR #749 breaks building the 32-bit version with `make 32bit=yes`:

```
[link libgenometools.so]
/usr/bin/ld: cannot find -lpango-1.0
/usr/bin/ld: cannot find -lgobject-2.0
/usr/bin/ld: cannot find -lglib-2.0
/usr/bin/ld: cannot find -lcairo
/usr/bin/ld: cannot find -lpangocairo-1.0
/usr/bin/ld: cannot find -lpango-1.0
/usr/bin/ld: cannot find -lcairo
/usr/bin/ld: cannot find -lgobject-2.0
/usr/bin/ld: cannot find -lglib-2.0
collect2: error: ld returned 1 exit status
make: *** [lib/libgenometools.so] Error 1
```

**Comment by teythoon** [comment]
No, that wasn't me.  I checked out the revision before my changes, and it fails with the same error for me.  To fix that, either install the 32-bit versions of the gnome libraries, build with cairo=no, or fix the auto detection of cairo to notice that the 32-bit versions of said libraries are missing.  Of course a proper build system could have done that for you... ;)

**Comment by gordon** [comment]
I took a wrong turn when investigating the reason for the broken GenomeThreader build (see #755).
