### ISSUE TITLE
Superfluous index files in testdata

### ISSUE THREAD

**Issue by stefan-kurtz** [genometools/genometools#765]
I think that the following files do not belong into the testdata directory, as they are platform dependent. I do not see where they are used and It seems that they have accidentially
be added after creating some index files in the testdata dir. Any opions?

foo.32.des
foo.32.esq
foo.32.sds
foo.32.ver0.al1
foo.32.ver0.esq
foo.64.des
foo.64.esq
foo.64.sds
foo.64.ver0.al1
foo.64.ver0.esq

**Comment by satta** [comment]
No, I think they are used as example data to check that the correct 32-bit/64-bit properties are reported by `gt encseq info`, see https://github.com/genometools/genometools/blob/master/testsuite/gt_encseq_include.rb#L337 ff.

**Comment by stefan-kurtz** [comment]
I just checked whether the same index works on a mac and I was surprised 
that it does.
So is the encseq encoding portable (at least on systems with the same 
endianess and the binaries
with the same pointer word sizes)?

If so, then having the files in testdata makes sense.

Bye, Stefan

On 03/11/2016 05:49 PM, Sascha Steinbiss wrote:
>
> No, I think they are used as example data to check that the correct 
> 32-bit/64-bit properties are reported by |gt encseq info|, see 
> https://github.com/genometools/genometools/blob/master/testsuite/gt_encseq_include.rb#L337 
> ff.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/genometools/genometools/issues/765#issuecomment-195447575>.
>


-- 
Prof. Dr. Stefan Kurtz
Zentrum fuer Bioinformatik
Universitaet Hamburg
Bundesstrasse 43
20146 Hamburg
Germany

Email:  kurtz@zbh.uni-hamburg.de
URL:    http://www.zbh.uni-hamburg.de/kurtz
Phone:  +49 (40) 42838 7311
FAX:    +49 (40) 42838 7312

**Comment by satta** [comment]
Well, these tests just check a few header fields. I wouldn't count on it for the whole file... I guess one would have to dive into the exact format(s) again to check portability in detail.

**Comment by satta** [comment]
So do we want to keep these tests or remove them? They might fail on other archs but so will others, definitely...

**Comment by Garonenur** [comment]
I vote for keeping them. The probability for other archs were these tests fail seems pretty low if they didn't fail until now.

**Comment by gordon** [comment]
I would also keep them.

**Comment by satta** [comment]
Agreed. So I guess we can close this ticket?
