### ISSUE TITLE
Path to Pango and Cairo headers

### ISSUE THREAD

**Issue by AragornSteiger** [genometools/genometools#773]
I have been trying to link the genometools build to my installs of Pango and Cairo. I have tried using the gcc environment variables, and the -I option on the make command line and none seem to work, I always wind up with the following:

src/annotationsketch/graphics_cairo.c:29:30: error: pango/pangocairo.h: No such file or directory

I have verified that the header exists in the directory I am trying to link. Please, if someone could assist, what is the best method to achieve this?

Thank you!
Aragorn.

**Comment by satta** [comment]
Hi Aragorn,

thanks for your request. Could you please let me know a bot more about what GenomeTools version you are running? What operating system are you on and how did you install the Pango/Cairo libraries? Did you also install the development headers and the pkg-config tool?

Cheers
Sascha

**Comment by bretonics** [comment]
I get the same error by just typying `make` for version 1.5.8.

Linux CentOS 7 and installed `yum install cairo-devel`.

**Comment by satta** [comment]
Hi Andres and Aragorn,

I was just able to reproduce this on a CentOS 7 Vagrant box. Thanks for pointing me towards an affected distribution.
It appears that on RedHat-like systems you will also need to install `pango-devel`, i.e. `yum install pango-devel`. This is different from Debian based systems where the headers are assigned to packages differently.
After installing the package I had no trouble compiling the rest of 1.5.8. Just let me know if there are any more questions.

Cheers
Sascha

**Comment by satta** [comment]
Ah btw @AragornSteiger  I just noticed that you were trying to link to your _own_ copies of the Pango and Cairo libs... You can add the necessary `-I` entries to the `CFLAGS` environment variable and the necessary `-L` entries to the `LDFLAGS` environment variable before using `make` and they will be considered. Sorry this isn't documented in detail but we just assumed that pkg-config is used to determine the install location of these libraries. 
Please try modifying above environment variables and let me know if it helped.

**Comment by bretonics** [comment]
Great! Thanks @satta, after installing the `pango-devel` package, the program compiled without errors. Ran `make test` and pretty much everything passed, except for test numbers 457,458, 1613 and a few others a could not catch.

Everything seems to have installed properly and working.

**Comment by satta** [comment]
Great to hear that. I will close this ticket for now -- @AragornSteiger please feel free to reopen if my suggestion didn't fix building for you.

**Comment by sghignone** [comment]
I'm experiencing the same issue trying to install v.1.5.9 on Ubuntu 16.04.6 LTS, with libcairo2-dev libraries already at newest version (1.14.6-1). I had to complile using `make threads=yes  cairo=no`

**Comment by satta** [comment]
@sghignone did you also install the `libpango1.0-dev` package? That contains the required `pangocairo.h` header.

**Comment by sghignone** [comment]
Oh Thanks Sasha! I didn't check that one! it worked.

**Comment by satta** [comment]
Nice to hear that!
