### ISSUE TITLE
gtdoc.lua question

### ISSUE THREAD

**Issue by Garonenur** [genometools/genometools#784]
while working on the gtdoc-code to use it to get the api of some of my code into my thesis I encountered this:
[gtdata/modules/docvisitorlatex.lua#125](https://github.com/genometools/genometools/blob/ac478f2af062c65a1e04d31b8be70871375cdf9f/gtdata/modules/gtdoclib/docvisitorlatex.lua#L125)
and I am wondering if this line is correct? because it sets name to ```nil``` or ```false``` which would not work well if given to the markdown latex template. Shouldn't it say: ```name = desc.name```? If I am wrong, maybe someone tell me what this is about.

**Comment by satta** [comment]
Uh, it's been a while since I looked at this and I guess you're right. At least this is now it's done in `docvisitorhtml.lua`.

**Comment by Garonenur** [comment]
I'll fix that. It does not concern me directly as c-functions always have a return value (well, void sometimes) but I was puzzled by it.
