### ISSUE TITLE
gff3_to_gtf doesn't work

### ISSUE THREAD

**Issue by Mrwow** [genometools/genometools#786]
I want to transfer parse GFF3 file and show them as GTF file, but it doesn't work. The GFF3 file comes from LTRharvest and LTRdigest.

`gt gff3_to_gtf harvest_pig_sorted.gff3 -o test `

**Comment by satta** [comment]
Hmmm, may I ask what kind of output you are expecting? Does the file only contain LTR element annotations? The GTF format (http://mblab.wustl.edu/GTF22.html) -- which is meant for genes -- does not really specify how non-gene features such as LTR retrotransposons should be represented. I would go as far as saying that such elements are not really supported by this format. Indeed, running `gt gtf_to_gff3` on LTRharvest/LTRdigest output warns about skipped features:
```
$ gt gff3_to_gtf ltrs_after_ltrdigest.gff3 > out.gtf
warning: skipping GFF3 feature of type "repeat_region" (from line 3 in file "ltrs_after_ltrdigest.gff3")
warning: skipping GFF3 feature of type "target_site_duplication" (from line 4 in file "ltrs_after_ltrdigest.gff3")
warning: skipping GFF3 feature of type "inverted_repeat" (from line 5 in file "ltrs_after_ltrdigest.gff3")
warning: skipping GFF3 feature of type "LTR_retrotransposon" (from line 6 in file "ltrs_after_ltrdigest.gff3")
warning: skipping GFF3 feature of type "long_terminal_repeat" (from line 7 in file "ltrs_after_ltrdigest.gff3")
warning: skipping GFF3 feature of type "long_terminal_repeat" (from line 8 in file "ltrs_after_ltrdigest.gff3")
warning: skipping GFF3 feature of type "inverted_repeat" (from line 9 in file "ltrs_after_ltrdigest.gff3")
...
```
and results in an empty GTF file:
```
$ wc -l out.gtf
       0 out.gtf
```
which is what I would expect.

IMHO GTF is not really the right format for this kind of data. Note that if there _are_ genes in the input file, they will indeed be converted to GTF.

**Comment by Mrwow** [comment]
OK, I got it !  I thought it was  a bug before. Now, I'm clearer about the command  and GFF3. Thanks a lot !

**Comment by Garonenur** [comment]
@Mrwow if that solves your problem, you are free to close the issue yourself - it gives us a clear signal, that we did everything we could to help ;)
