### ISSUE TITLE
Possible error in phase calculation when a CDS segment is 1bp long

### ISSUE THREAD

**Issue by lucventurini** [genometools/genometools#793]
#It seems that GenomeTools is treating 1bp CDS exons in the wrong way when calculating the phase, by considering them as length 2 instead of 1. 

Prologue: to calculate phases in a tool I am working on, I am using the following function:
```
def __calculate_phases(coding, previous):

    # Previous indicates whether the record began with a phase different from 0
    # for incomplete gene models
    total_cds_length = -previous

    __calculated_phases = []
    for cds_segment in coding:
        length = cds_segment[1][1] - cds_segment[1][0] + 1
        phase = (3 - (total_cds_length % 3)) % 3
        total_cds_length += length
        __calculated_phases.append(phase)

    return total_cds_length, __calculated_phases
```
I am not sure it is correct as I have not been able to find the relevant corresponding section in the GenomeTools codebase. 

In my case, I have the following GFF entry:

```
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	gene	40282	46004	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960;Name=TRIAE_CS42_5DL_TGACv1_434051_AA1427960;biotype=protein_coding;confidence=High
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	mRNA	40282	46004	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960;Name=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2;aed=0.0;note=TRIAE_CS42_5DL_TGACv1_434051_AA1427960;confidence=High;has_start=True;has_stop=True;original_stop=True;protein_rank=P1;transcript_rank=T2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	40282	40933	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon1;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	three_prime_UTR	40282	40720	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.three_prime_UTR1;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	40721	40933	.	-	0	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS1;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	41018	41111	.	-	1	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS2;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	41018	41111	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon2;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	41227	41468	.	-	0	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS3;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	41227	41468	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon3;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	41673	41831	.	-	0	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS4;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	41673	41831	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon4;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	41946	42820	.	-	2	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS5;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	41946	42820	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon5;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	42905	42913	.	-	2	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS6;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	42905	42913	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon6;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	45373	45496	.	-	0	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS7;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	45373	45496	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon7;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	45600	45651	.	-	1	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS8;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	45600	45651	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon8;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	45726	45726	.	-	2	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS9;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	45726	45726	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon9;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	CDS	45875	45893	.	-	0	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.CDS10;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	exon	45875	46004	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.exon10;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
Triticum_aestivum_CS42_TGACv1_scaffold_434051_5DL	TGACv1	five_prime_UTR	45894	46004	.	-	.	ID=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2.five_prime_UTR1;Parent=TRIAE_CS42_5DL_TGACv1_434051_AA1427960.2
```

The gt gff3 tool (latest release, version 1.5.8, linux x86_64 binaries) complains that the phase is incorrect for this entry, with the following error:

```
warning: CDS feature on line 19 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 17 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 15 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 13 in file "stdin" has the wrong phase 2 -> correcting it to 1
warning: CDS feature on line 11 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 9 in file "stdin" has the wrong phase 0 -> correcting it to 2
warning: CDS feature on line 7 in file "stdin" has the wrong phase 1 -> correcting it to 0
warning: CDS feature on line 6 in file "stdin" has the wrong phase 0 -> correcting it to 2
```

The complaints begin after line 21, ie an exon/CDS line with length 1 (45276 .. 45276). 
This seems wrong to me, for the following reasons:

1- If I have understood the method of calculation right, the phase should be calculated by taking the modulo 3 of the amount of sequence already met before encountering the current CDS segment; see the code at the beginning of the issue report.

   My function agrees with the phases present in the input GFF record I pasted in the comment, but not with GenomeTools; it reports the total CDS length as being 1788 ie a number divisible by 3.

2 - I can obtain the same results as GenomeTools in terms of phases by adding 2 instead of 1 to the total_cds_length variable when encountering the 1-bp exon:

```
def __calculate_phases(coding, previous):
    # Previous indicates whether the record began with a phase different from 0
    # for incomplete gene models

    total_cds_length = -previous

    __calculated_phases = []
    for cds_segment in coding:
        length = cds_segment[1][1] - cds_segment[1][0] + 1
        # This agrees with GenomeTools
        if length == 1:
             length += 1
        phase = (3 - (total_cds_length % 3)) % 3
        total_cds_length += length
        __calculated_phases.append(phase)

    return total_cds_length, __calculated_phases
```

The result in this case will agree with GenomeTools regarding the phases, *but the total CDS length will be incorrect (1789, and 1789 % 3 == 1)*. This seems quite wrong.

**Comment by satta** [comment]
The corresponding code in GenomeTools is here, but slightly different: https://github.com/genometools/genometools/blob/master/src/extended/cds_check_visitor.c#L39

I can take a look at the exact case here later next week, when I have some more time. Does the problem also occur in features on the forward strand?

**Comment by lucventurini** [comment]
Apparently not; this mock GFF:

```
#gff-version	3
Chr1	foo	gene	101	1000	.	+	.	ID=gene1;
Chr1	foo	mRNA	100	1000	.	+	.	ID=transcript1;Parent=gene1;
Chr1	foo	exon	101	300	.	+	.	Parent=transcript1;
Chr1	foo	CDS	101	300	.	+	0	Parent=transcript1;
Chr1	foo	exon	400	400	.	+	.	Parent=transcript1;
Chr1	foo	CDS	400	400	.	+	1	Parent=transcript1;
Chr1	foo	exon	501	650	.	+	.	Parent=transcript1;
Chr1	foo	CDS	501	650	.	+	0	Parent=transcript1;
Chr1	foo	exon	801	1000	.	+	.	Parent=transcript1;
Chr1	foo	CDS	801	1000	.	+	0	Parent=transcript1;
```

has the correct phases assigned, both according to GenomeTools and to my function above.

By the way, thank you for directing me to the relevant code section in your code base, verifying that I have been able to replicate the correct phase function is relieving!

**Comment by satta** [comment]
I have been able to locate the issue here. The phase checking code does not always deliver correct results when CDS features are shorter than the amount of bases to skip due to the phase, cf. this line:
```C
correct_phase = (3 - (current_length - current_phase) % 3) % 3;
``` 
If `current_length` is 1 but the `current_phase` is 2, the result will be wrong. Indeed it is a better idea here to use cumulative transcript lengths for phase determination instead of doing this for each CDS separately. I have addressed this in #808, and I hope this fixes the problem for good.
@gordon as the original author: do you agree?

**Comment by lucventurini** [comment]
Fantastic, if this snippet functions I can be quite relieved for future projects!

**Comment by satta** [comment]
It does work in the case you describe (short CDS in a relative transcript position > 3) but to solve this generically I just noticed that it's not that simple... for example, how to handle the case when the first CDS is 1bp and the phase is 2 -- this wouldn't work with this solution either.

Going back to the spec, I notice it says that:

> The phase is one of the integers 0, 1, or 2, indicating the number of bases that should be removed from the beginning of this feature to reach the first base of the next codon. In other words, a phase of "0" indicates that the next codon begins at the first base of the region described by the current line, a phase of "1" indicates that the next codon begins at the second base of this region, and a phase of "2" indicates that the codon begins at the third base of this region. 

It does not really define how to handle cases where the 'region' is indeed shorter than the phase... do we always want to carry over the 'rest' of the phase in this case?

**Comment by lucventurini** [comment]
I think I would want to, although you are right in indicating that the specification is not clear enough. My hunch is that the best way to go about it is to always consider the cumulative length, so in your case a CDS of 1 bp and a phase of 2 mean that the transcript is truncated and it should really start either 2 bps downstream (so in the next exon) or 1 bp upstream. This leaves the total length of the CDS as a multiple of 3. In curated references such as human this should *not* happen at all, because the genome is complete, but it can definitely happen in draft genomes where the scaffold boundaries fall within genes.

For example, the case you describe might well happen if the scaffold breaks right inside a coding exon.

If you relook at the python snippet that I included in the comment upstream, that's exactly the meaning of the "previous" variable - it's the initial phase, as derived from the GFF file.

**Comment by satta** [comment]
Unfortunately we always treat coordinates as unsigned so we can't use your trick of starting with a negative value ;)
I will see if I can make the code cope with cases where the first CDS already needs to carry over a phase to the next CDS.

**Comment by lucventurini** [comment]
There is a simple alternative to the negative value ... complement the phase! If it's zero it stays as zero, if it's 1 it becomes 2, and if it is two it becomes one. Then the case becomes identical.

**Comment by satta** [comment]
Reopening until the corner case is fixed as well.

**Comment by satta** [comment]
Thanks -- I have addressed that case and also added a bunch of tests to the testsuite. I have also raised https://github.com/The-Sequence-Ontology/Specifications/issues/2 to discuss this case.
