### ISSUE TITLE
error during compilation

### ISSUE THREAD

**Issue by jvollme** [genometools/genometools#799]
Hello,
I am trying to install genometools v.1.5.8 on a server running "Red Hat Enterprise Linux Server release 7.2 (Maipo)" with gcc version 4.8.5.
I've tried compiling from source using the following command:
`make -j4  cairo=no`
but get the following error message:

>  lib/libgenometools.a(gt_lua.o): In function `gt_lua_open_lib':
>  /home/jov14/src/genometools-1.5.8/src/gtlua/gt_lua.c:39: undefined reference to 
>  gt_lua_open_annotationsketch'
>  collect2: error: ld returned 1 exit status
> make: *** [bin/gt] Error 1
> make: *** Waiting for unfinished jobs....

I've seen that for other compilation issues on this site, it was possible to just ignore error messages using the `error=no` flag, but I am not sure if this is advisable for every case.
What can I do to fix this, or is it safe to just ignore this error message?

**Comment by satta** [comment]
Hi John,

thanks for getting in touch. Unfortunately this is a compilation error and cannot be ignored, as no `gt` executable will be produced.
I am curious... did you start a build without `cairo=no` first and then added this parameter in a second try? If so, please run `make cleanup` and try again (with `cairo=no`). In general, it is always a good idea to try a `make cleanup` ;)

Please let me know if that helped.
Cheers
Sascha

**Comment by jvollme** [comment]
> did you start a build without cairo=no first and then added this parameter in a second try?

Actually, yes, that is exactly what happened. I  now did a `make cleanup` and now it compiles without errors.
Thanks for the help!
