### ISSUE TITLE
Extend lua API: count children of the specified type

### ISSUE THREAD

**Issue by standage** [genometools/genometools#802]
I'm writing some spec files for gt speck, and a common task I encounter is counting a node's children of a given type. There already exist functions to count all children, and to test whether a child of a certain type exists. But if I simply need the count (for example, to compare the number of exons the the number of introns) I find myself using iterators and counters, and/or building lists. The spec files would be much clearer and more concise if there were a simple function to compute and report the counts directly.

**Comment by satta** [comment]
Thanks for the PR! However, this would also have been possible using the speck-specific API additions in `gtdata/spec/speclib.lua`, namely the `count()` aggregator function and the `FeatureNode:children_of_type()` and `FeatureNode:children_of_supertype()` iterators. It should be possible to do something like:

```
print(count(fn:children_of_type('CDS')))
```

which would give you the number of CDS children reachable from `fn`, or
```
print(count(fn:children_of_supertype('transcript')))
```
the number of transcripts (mRNA, rRNA, tRNA, ...) in `fn`.

Sorry these are not in the C API (yet?), but I had to implement them quickly when I needed them and at first I thought they might be most useful in speck.

**Comment by standage** [comment]
Awesome, and thanks for the pointer!

This PR required 10-15 minutes start to finish, so no love lost should we decide to nuke it. And I'm neutral on whether we need this convenience functionality in the C API.
