### ISSUE TITLE
speck: Access sequence from region nodes

### ISSUE THREAD

**Issue by standage** [genometools/genometools#804]
The gt speck docs describe how to process sequence nodes, as well as how to extract sequence data from an external file using the global `region_mapping` variable. I'm struggling to figure out how to access sequence data while processing region nodes. Is this possible?

**Comment by standage** [comment]
> Inline sequences (##FASTA directive) in GFF3 files are not supported,
> separate files with sequences are needed.

Wait, so `describe.sequence` should handle Fasta sequences provided by `-seqfile`?

**Comment by standage** [comment]
Perhaps this is a case where the documentation needs to be updated, because it indeed looks like `describe.sequence` handles inline sequences. Or perhaps I simply misunderstood the intent of the docs.

In any case, I'm still curious about how to access sequence data (from the external Fasta file) while processing region nodes.

**Comment by satta** [comment]
You are right, this is a bit of a vaguely described case. Let's first look at the role of `describe.sequence`
`describe.sequence` indeed is meant to handle GtSequenceNodes, i.e. inline sequences. That is, it is possible to get their sequence using their `get_sequence()` method and use it in your aspect expectations. However (and this is what the quoted part of the documentation is referring to) the inline sequence nodes can not be used to extract feature sequences based on them. The reason for this is that the sequences used for extraction need to be indexed and region-mapped. This can not be expected when streaming them as nodes, which requires the sequence to be provided out of band. That is, if you want to extract sequences for features using `extract_sequence()` or  `extract_and_translate_sequence()` you will need a separate sequence file. (The indexing will be done automatically on first accessing them). To split inline sequences from annotations, you can use `gt inlineseq_split`.

This brings us to the next question, extraction of sequences for region nodes. IIRC at the moment the `extract_sequence` methods are only defined on GtFeatureNodes. Indeed I can't see any way to access the sequence referred to by a region node using the Lua API. What would you expect for those anyway? The whole sequence or only the substring specified by the coordinates in the region node? I'd be happy to discuss improvements!

**Comment by standage** [comment]
> What would you expect for those anyway? The whole sequence
> or only the substring specified by the coordinates in the region node?

I think both could be useful, but at the very least the whole sequence. It should be easy to extract the subsequence in Lua if needed.

**Comment by standage** [comment]
Currently there is no way to enforce constraints on the region nodes relative to the corresponding sequence. What if the specified region is longer than the sequence? What if for some cases you want to enforce that the region is the entire sequence? In the examples you show how to enforce that the sequence-region start == 1, but there's currently no way to fully enforce these example constraints.

**Comment by satta** [comment]
I think for this to be possible we would need a more generic sequence access interface available in the API than just regionmapping + `extract_sequence()` which always needs a specific feature to extract sequence for. What one would want here would probably be something like being able to query the supplied sequence set for a seqid, then get the corresponding sequence length and relate it to the interval given in the region node. I'd have to check how difficult that would be to implement and/or to expose to the Lua API.

Again, this would be rather difficult to do for inline sequences -- in sorted annotation streams, for example, they are delivered at the end, while region nodes are delivered at the beginning of the stream. Making these available as indexed sequences would require two passes over the stream, which means having to keep it in memory. Also, all sorts of issues like two different sequences with the same ID could occur in the GFF inline sequence and the out of band `-seqfile`/`-seqfiles`/`-encseq`.

**Comment by standage** [comment]
> Again, this would be rather difficult to do for inline sequences.

I certainly am not a fan of inline sequences, and never use them. Given the constraints of streaming processing I think it's completely reasonably that region and feature nodes only have access to external sequences.

> What one would want here would probably be something like being able to query the supplied sequence set for a seqid, then get the corresponding sequence length and relate it to the interval given in the region node.

Yeah, what I have in mind only requires meta-information about the sequence (its length), not the sequence itself. But one could imagine situations where the sequence itself would be useful. I would propose that the entire sequence be accessible by seqid, with optional subsequence extraction by specifying a range (from a region node, a feature node, or a long range object).

**Comment by satta** [comment]
>> Again, this would be rather difficult to do for inline sequences.
>
> I certainly am not a fan of inline sequences, and never use them. Given the constraints of streaming processing I think it's completely reasonable that region and feature nodes only have access to external sequences.

OK, agreed.

>>What one would want here would probably be something like being able to query the supplied sequence set for a seqid, then get the corresponding sequence length and relate it to the interval given in the region node.
>
>Yeah, what I have in mind only requires meta-information about the sequence (its length), not the sequence itself. But one could imagine situations where the sequence itself would be useful. I would propose that the entire sequence be accessible by seqid, with optional subsequence extraction by specifying a range (from a region node, a feature node, or a long range object).

True. I'll see what I can do when I find some time (not before tomorrow...)

**Comment by satta** [comment]
I've filed #805 which implements the region mapping API. That should make it possible to access the sequence. See `src/gtlua/region_mapping_lua.h` for more details.

**Comment by standage** [comment]
Fixed by #805.
