### ISSUE TITLE
1.5.9 release?

### ISSUE THREAD

**Issue by satta** [genometools/genometools#810]
We should plan for a new release, there's been a bunch of bugfixes and feature additions. Certainly we want #793 in, do we also want to wait for #806 to be looked at?

**Comment by Garonenur** [comment]
:+1:

**Comment by Garonenur** [comment]
someone needs to ping @ggonnella to have a look at #806.

**Comment by gordon** [comment]
On 07/01/2016 03:36 PM, Sascha Steinbiss wrote:
> We should plan for a new release, there's been a bunch of bugfixes and feature additions. Certainly we want #793 in, do we also want to wait for #806 to be looked at?
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/genometools/genometools/issues/810
> 

I'm fine with a new release soon.

**Comment by satta** [comment]
Btw, should we prepare the release? It looks like #806 is at least partially solved?

**Comment by standage** [comment]
:+1:

**Comment by Garonenur** [comment]
yes.

**Comment by gordon** [comment]
Sound good!

**Comment by satta** [comment]
Done.
