### ISSUE TITLE
Have 'gt speck' return non-zero status in case of failures or runtime errors

### ISSUE THREAD

**Issue by standage** [genometools/genometools#811]
I don't know whether this would be better as default behavior or as an option, but having `gt speck` return a non-zero status on failure/error would be helpful for integrating into shell-based and Makefile-based workflows.

**Comment by satta** [comment]
Well, would probably the `-failhard` option also work in these cases? It stops evaluation and fails with a nonzero status if there is a runtime error. If not, it would also be easy to add a new option that does the same even for a validation failure.

**Comment by standage** [comment]
Hmm, let me think about this.

The `-failhard` option is probably what I want in terms of runtime errors. But for validation errors, I think it would be more helpful to have them all accumulate and produce the final report (to show the extent of the error(s)) instead of nuking it immediately.

**Comment by satta** [comment]
OK, done :)
