### ISSUE TITLE
Failing MD5 test

### ISSUE THREAD

**Issue by satta** [genometools/genometools#815]
## Problem description

Travis fails test 1068 with seed 1209700457

```
FAILING test, output of testsuite/stest_testsuite/test1068/stderr_1
/home/travis/build/genometools/genometools/bin/gt: error: could not execute script ...ls/genometools/src/external/md5-1.1.2/tests/test.lua:78: assertion failed!
FAILING test, output of stest_error
Test 1068 'MD5 library': failed:
unexpected return code: 1 != 0:
/home/travis/build/genometools/genometools/testsuite/stest.rb:286:in `run'
/home/travis/build/genometools/genometools/testsuite/stest.rb:449:in `run'
testsuite.rb:98:in `run_test'
/home/travis/build/genometools/genometools/testsuite/gt_scripts_include.rb:137:in `block in <top (required)>'
/home/travis/build/genometools/genometools/testsuite/stest.rb:176:in `block in test'
/home/travis/build/genometools/genometools/testsuite/stest.rb:165:in `fork'
/home/travis/build/genometools/genometools/testsuite/stest.rb:165:in `test'
/home/travis/build/genometools/genometools/testsuite/stest.rb:120:in `process'
/home/travis/build/genometools/genometools/testsuite/stest.rb:34:in `block (2 levels) in run'
     [ problem: unexpected return code: 1 != 0
       in: /home/travis/build/genometools/genometools/testsuite/stest_testsuite/test1068 ]
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

1.5.9, latest git (bbd497d)

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.

`amalgamation=yes`

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Travis Linux test VM

**Comment by satta** [comment]
It also fails with `seed=653443494`.

**Comment by Garonenur** [comment]
Well, it does not fail on my machine for those seeds. The debugging is going to be tricky.

**Comment by satta** [comment]
Yep, same for me. I also can't really see how the seed would be influencing the result; there's no randomness involved in that test. It would be great to have the test output...

**Comment by satta** [comment]
I've done a quick:
```
#!/bin/bash

while true; do
    cd testsuite && ./testsuite.rb -select 1060..1070 -threads 3
    [ $? -gt 0 ] && break
    cd ..
done
```

and I got the following:
```
cat /Users/ss34/develop/genometools/testsuite/stest_testsuite/test1068/stderr_1
/Users/ss34/develop/genometools/testsuite/../bin/gt: error: could not execute script .../testsuite/..//src/external/md5-1.1.2/tests/test.lua:78: assertion failed!
```

Maybe that helps...

**Comment by Garonenur** [comment]
```while ./testsuite.rb -name 'MD5 library'; do :; done ```
and some waiting later:
```
seed=117823445
1068: MD5 library                                                 : failed
     [ problem: unexpected return code: 1 != 0
       in: /home/dirk/Repositories/genometools/testsuite/stest_testsuite/test1068 ]
```

BUT:
```
./testsuite.rb -name 'MD5 library' -seed 117823445                        [md5_bug_815] 12:05:59
seed=117823445
1068: MD5 library                                                 : ok
```

**Comment by satta** [comment]
Line 78 in `src/external/md5-1.1.2/tests/test.lua` is:
```Lua
assert(md5.crypt('a', 'a') ~= md5.crypt('a', 'b'))
```

Looking at the implementation of `crypt` it says that:
```Lua
/**
*  Encrypts a string. Uses the hash function md5 in CFB (Cipher-feedback
*  mode).
*  @param message: arbitrary binary string to be encrypted.
*  @param key: arbitrary binary string to be used as a key.
*  @param [seed]: optional arbitrary binary string to be used as a seed.
*  if no seed is provided, the function uses the result of
*  <code>time()</code> as a seed.  
*  @return  The cyphertext (as a binary string).
*/
```

As there is no seed provided in the test case, it's using `time()` as the seed, which might explain the nondeterminism. It seems the problem is with this implementation.

**Comment by satta** [comment]
https://github.com/keplerproject/md5/commit/00becfaa301b951496f3efd9721525606239338a might be relevant.

**Comment by Garonenur** [comment]
I am currently testing the most resent lua-md5 version, but it seems that there are some errors. I might change the way it is compiled? But yeah, I included it by using submodules from git, so I will inform you if I get it to compile and we can discuss if we want to use it this way. Otherwise we just fix the md5 we ship (which is suboptimal).

**Comment by Garonenur** [comment]
I am running into problems with some ```require``` stuff for the tests, if anyone wants to check it out see here: [md5_bug_815](Garonenur/genometools/tree/md5_bug_815)
right now, if anyone pulls from there, you need to run ```git submodule update``` to check out the md5-submodule.

**Comment by satta** [comment]
IMHO it would be essential to have the submodule sync happen automatically, this might otherwise put off contributors. Also, are the contents of this submodule included when building a source distribution (`make srcdist`) or when downloading a tarball from here on GitHub? If not then I'm not sure this is a good way to go.

I'll look at the failing test when I have some free time, no problem.

**Comment by satta** [comment]
FYI @Garonenur I have addressed the issues in my branch https://github.com/satta/genometools/tree/md5_bug_815 -- the cause was that in more recent Lua libraries it's the `require` caller's responsibility to bind the library functions to a module table in their namespace, while in the older versions the `require`  call directly pushes a name into the current namespace. I have adjusted the code accordingly.

**Comment by Garonenur** [comment]
so. Getting travis to work would be no problem, as we can run ```git submodule ...``` there. But right now GitHubs download does not support submodules. We use ```git archive``` to create the ```srcdist``` and this does not support submodules, can be done, there are scripts for that.

I would say it does not make me happy. I will include the current lua-md5 lib directly as we did before, even though I think there should be more elegant ways without maintaining our own copy of everything, but I already had to change small stuff within the md5-code to make it work with our setup, and that was not something I would create a PR for the original repo.

**Comment by gordon** [comment]
We copied the code into the repository for all the other external sources, why not also do it here?
I know submodules are conceptionally cleaner, but it seems to me that in practice the current solution is easier to work with.

**Comment by Garonenur** [comment]
you are right. but having all external sources linked to their own repositories would help with any bug fixing done in them.
Every time we fix clang-warnings or other small stuff in any of our external sources someone should create a pr for those changes to the original repo. That would be much easier if it were just something one could do from within GT.
