### ISSUE TITLE
gff3validator segmentation fault

### ISSUE THREAD

**Issue by RvV1979** [genometools/genometools#825]
## Problem description
I am trying to validate a GFF fiormatted file but I get a segmentation fault error. First I thought it was a memory issue but after trimming down the file the error remains... 

## Exact command line call triggering the problem
```
$ gt gff3validator scf00001.txt 
Segmentation fault (core dumped)
```
See attached file for a minimal input triggering the problem

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
```
$ gt -version
gt (GenomeTools) 1.5.6
```

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
compiled from source without additional parameters
[scf00001.txt](https://github.com/genometools/genometools/files/409124/scf00001.txt)

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
This happens on Ubuntu as well as on OSX 10.11.6.

**Comment by satta** [comment]
Hi Robin, thanks for the bug report. I can confirm this is still an issue on 1.5.10.

**Comment by RvV1979** [comment]
Thanks, Sascha & Gordon!
I was using it for validation so getting appropriate error messages is
perfect.
