### ISSUE TITLE
Travis Mac OS X tests?

### ISSUE THREAD

**Issue by satta** [genometools/genometools#830]
This is more of a public discussion about the test suite -- do we want to have Travis also run builds and tests on Mac OS X machines? I enabled OSX tests recently and after some adjustments to the test driver (https://github.com/genometools/genometools/compare/master...satta:osx_test) it seems to work well: https://travis-ci.org/satta/genometools/builds/156211407

However, this considerably increases the total test run time as the OSX runs tend to be slower than the Linux counterparts. Any opinions?

**Comment by Garonenur** [comment]
Like I asked about adding appvoyer for windows testing I am for testing on other OSes. It might be necessary to reorganize the test matrix to reduce the number of instances overall? For example I am not sure if we have to run the testsuite with and without amalgamation - those should only be compilation tests. All tests should run with amalgamation for fastest execution.

**Comment by satta** [comment]
Agreed. I can take a look at how to craft the matrix definition to limit the combinations.

**Comment by satta** [comment]
How about https://travis-ci.org/satta/genometools/builds/157320994 -- this runs the tests only on Linux with a reduced set of combinations.

**Comment by Garonenur** [comment]
I think this should be all right. Question is: could compiling on a different system break some tests? Possible but unlikely.
Maybe there could be a "full" test configuration we run just for releases, but for now I think it would be nice to have compilation tests for windows and mac added.

**Comment by satta** [comment]
TBH I have no idea how Windows would work, haven't looked at Appveyor so I don't know if it can handle Makefiles or only Visual Studio projects etc. I can get a pull request going for the Mac tests though.
