### ISSUE TITLE
gt sketch test fails

### ISSUE THREAD

**Issue by Garonenur** [genometools/genometools#837]
## Problem description

one gt sketch test fails with incorrect output, diff fails.

## Exact command line call triggering the problem

```
./testsuite.rb -testdata /home/dirk/Repositories/genometools/testdata -bin /home/dirk/Repositories/genometools/bin -cur /home/dirk/Repositories/genometools \
          -gtruby /home/dirk/Repositories/genometools/gtruby -nordb \
          -select 1381
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

```
bin/gt (GenomeTools) 1.5.10
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Compile flags: -fstrict-aliasing -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -Qunused-arguments -Wno-parentheses -Werror
```

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.

```
CFLAGS+=-fstrict-aliasing assert=no amalgamation=yes 64bit=yes CC='ccache clang' -j4 cairo=yes
```

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
ubuntu 16.04.1 LTS

**Comment by satta** [comment]
Is this the 'narrow image' test?
```
1381: gt sketch -showrecmaps (narrow image)                       : ok
```
It succeeds for me, but since this is supposed to test line breaking in narrow images it depends on the default font of the system involved. I'll try to get a Xenial64 Vagrant box going and reproduce.

**Comment by satta** [comment]
Yes, the captions with this font and text lengths are just aligned in a way that exceeds the tolerance for the expected layout:
![out](https://cloud.githubusercontent.com/assets/27732/18611026/24a9a64c-7d25-11e6-8283-f8dfb742a61e.png)
![out2](https://cloud.githubusercontent.com/assets/27732/18611027/2883f7a4-7d25-11e6-98e6-f306b3f96fa2.png)

I'll change the text lengths to be a bit more forgiving.
