### ISSUE TITLE
gt extractfeat is not working for me

### ISSUE THREAD

**Issue by rajultayal** [genometools/genometools#843]
I want to extract the chromosome location from gff file using the 'gt extract' tool. However, the tool returns with the following error message: gff file is not sorted; although i sorted the gff using "gt gff3 sort" . Th gff file to be sorted is [ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/331/145/GCF_000331145.1_ASM33114v1/GCF_000331145.1_ASM33114v1_genomic.gff.gz](url)

**Comment by satta** [comment]
I can indeed reproduce this. Strange... 

```
$   gzcat GCF_000331145.1_ASM33114v1_genomic.gff.gz | gt gff3 -sort -retainids -tidy > GCF_000331145.1_ASM33114v1_genomic.sorted.gff3
$   gt extractfeat -type CDS -join -translate -seqfile GCF_000331145.1_ASM33114v1_genomic.fna.gz --matchdescstart < GCF_000331145.1_ASM33114v1_genomic.sorted.gff3
[...]
>CDS_2377 (joined) (translated)
MDTPPLHIAMFPWFAMGHLTPFLHLSNKLAQRGHKISFFIPKKTQTKLQHLNLHPHLITFFTINVPHVDGLPYGAETTSDVPFSLFPLIATAMDQTDKDIELLLKELKPQIVFFDFQHWLPNLTKKHGIKSLQYLIWNPISTAYLGTGPRQSQGRELNEVDLMKPPSGFPDTCINLHSHELRFLVSSRKLEFGSGILLYDRVDLGARLADVIAFKGCKEIDGPYVEYLGSVFGKSVLLSGPILPEPPMSTLEEKWVSWLNGFKQGSVVYCAYGSESALEHNQFKELLLGLELTGFPFLAALKPPVGFESIEEALPQGFNERVKGRGIAYGGWVQQQLILGHTSIGCFITHCGAASITEGLVNTCQLVLLPRLGSDHIMNARMMSAKLKVGVEIEKGEEDGLFTKESVCKAVNIVMDEENELGREVRANHAKLRNFLLCNNLESSSVDSFCQELYDLL*
>CDS_2378 (joined) (translated)
MEAPPLHLAMFPWLAMGHFTPYLHLSNKLAKRGHKISFFIPKNTLNKLQHLNLNPHLITFVPITVPHVDGLPHDAETASDVPFSLLPLIATAMDETKKEIELLLKELKPQIVFFDFQYWVPNLTKKLGIKSVQYWIASPYSISYFFHGPRQSLGKELTVDDLKKPPSGYPDSSIKLHSHELQFLASSRKLVFGSGVLLYDRLHFGTSLADAIGFKGCKEIDGPYAQYLGTVYGKPSLLSGPLLPESPLTTLDEKWVSWLKGFKHGSVVYCAYGSEGPLQENQFKELLLGLELTGFPFVAALKPPVGFESIEEALPQGFNERVKGRGIVYGGWVQQQLILEHPSVGCFITHCGAASITEALVNTCQLVLLPRVGVDHIMNARMMSTKLKVGVEVEKGDEDGLFTKESVCNAVNIVMDEGNEIGREVKANHIQLRKFLLSENLESSCVDNFCQKLRHLL*
gt extractfeat: error: the file stdin is not sorted (example: line 51179 and 0)
$

**Comment by rajultayal** [comment]
### Dear satta thanks for trying 
I am not sure how it worked but after these 2 command it gave me the output

gt gff3 -sortlines yes -retainids yes -tidy yes -fixregionboundaries yes -addids GCF_000331145.1_ASM33114v1_genomic.gff > GCF_000331145.1_ASM33114v1_genomic.sortd.gff

gt extractfeat -type CDS -translate yes -seqid yes -coords yes -retainids yes -matchdescstart -seqfile GCF_000331145.1_ASM33114v1_genomic.fna.gz GCF_000331145.1_ASM33114v1_genomic.sortd.gff > testoutput.txt
