### ISSUE TITLE
readjoiner overlap: error: cannot compute enhanced suffix array

### ISSUE THREAD

**Issue by felipelouza** [genometools/genometools#845]
## Problem description
gt -j 1 readjoiner overlap fails with **small values** of minlen (this problem doesn't happen when minlen>10)

## Exact command line call triggering the problem

```
env GT_MEM_BOOKKEEPING=on GT_ENV_OPTIONS='-spacepeak -showtime' /home/readjoiner/bin/gt -j 1 readjoiner overlap -readset /mnt/data/readset.reads.100000.fasta -l 5
```
**output:**

\# gt readjoiner overlap (version 1.2)
\# number of reads in filtered readset = 99745
\# TIME to collect initial prefixes 0.02
\# TIME to sort initial prefixes 0.03
\# TIME to remove duplicates 0.00
\# TIME to accumulate counts 1.55
\# TIME to compute partial sums 0.00
\# TIME cleaning up 0.00
\# TIME overall 1.61
\# space peak in megabytes: 1.68 (in 1769 events)
\# mmap space peak in megabytes: 2.34
\# combined space peak in megabytes: 4.02

**problem:**

```
/home/readjoiner/bin/gt readjoiner overlap: error: cannot compute enhanced suffix array in at mos
t 8103808 bytes
```

I used the following command to prefiltering:

```
/home/readjoiner/bin/gt readjoiner prefilter -readset /mnt/data/readset.reads.100000.fasta --db /mnt/data/reads.100000.fasta -maxlow 1280 -lowqual 0
```
\# gt readjoiner prefilter (version 1.2)
\# number of reads in complete readset = 100000
\# low-quality reads = 0
\# contained reads = 255
\# number of reads in filtered readset = 99745
\# space peak in megabytes: 3.93 (in 827 events)
\# mmap space peak in megabytes: 0.00
\# combined space peak in megabytes: 3.93

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

/home/readjoiner/bin/gt (GenomeTools) 1.5.10
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: cc (Debian 4.9.2-10) 4.9.2
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -Werror

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.

make prefix=/home/readjoiner 64bit=yes threads=yes cairo=no install

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

The machine has ~380 GiB of RAM.

Thank you!

**Comment by ggonnella** [comment]
You can try to use the `-memlimit` or `-parts` options.

**Comment by felipelouza** [comment]
It works! Thank you.
I would suggest to add this info in the manual PDF.
