### ISSUE TITLE
installation problem in OSX

### ISSUE THREAD

**Issue by tmargus** [genometools/genometools#848]
Hi,

I run to installation problem in OSX when compiling  Genometools.  It complained about  `Undefined symbols for architecture x86_64:`

### Exact command line call triggering the problem
```
make cairo=no
```

### output with error message

```
.....
[compile gt_wtree.o]
[compile gt_wtree_bench.o]
[link gt]
Undefined symbols for architecture x86_64:
  "_gt_lua_open_annotationsketch", referenced from:
      _gt_lua_open_lib in libgenometools.a(gt_lua.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/gt] Error 1
```

###  GenomeTools version 
last stable    __genometools-1.5.9.tar.gz__

### OS and environment
Mac OS X  v10.11.6
Xcodec v 8.1    
command line tools are up to date

some more
```
make cairo=no -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
```
and

```
cc -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Any ideas what to do.

Cheers,
Tonu

**Comment by satta** [comment]
Did you try a build without `cairo=no` first, then canceled it and added `cairo=no` afterwards? This may have resulted in such a situation.
Could you try doing a `make cleanup` and then running `make cairo=no` again?

**Comment by tmargus** [comment]
That was the case. Now it compiles.
Thanks!

**Comment by satta** [comment]
Always glad to help!
