### ISSUE TITLE
question: is there a simple way to transmute gff3 annotation when reverse complement a sequence?

### ISSUE THREAD

**Issue by tmargus** [genometools/genometools#849]
Hi,
It could be simple question here. I googled but didn't find a good working solution.
Is there a simple way to reverse complement annotation?  I mean annotation - CDS, exons, etc ... what is marked in "+" stand will be swapped to "-" strand with positions corrected according to reverse complemented sequence. 
Tonu

**Comment by satta** [comment]
Well, there's no readymade tool in GenomeTools for that, but it should be doable to write a small tool in Lua to do that. You'll need to know the length of all the sequences involved though so you can properly calculate reverse coordinates.

**Comment by satta** [comment]
Something like this may help:
```Lua

--[[
  Copyright (c) 2017 Sascha Steinbiss <sascha@steinbiss.name>

  Permission to use, copy, modify, and distribute this software for any
  purpose with or without fee is hereby granted, provided that the above
  copyright notice and this permission notice appear in all copies.

  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
]]

require 'gtlua'

-- Set this to the lengths of each sequence in the input GFF3
seqlengths = {ctg123 = 1497228}

function usage()
  io.stderr:write(string.format("Usage: %s input_gff\n", arg[0]))
  io.stderr:write("Reverse complement annotations.\n")
  os.exit(1)
end

function visitor_stream_new(instream, vis)
  -- make simple visitor stream, just applies given visitor to every node
  local visitor_stream = gt.custom_stream_new_unsorted()
  visitor_stream.instream = instream
  visitor_stream.vis = vis
  function visitor_stream:next_tree()
    local node = self.instream:next_tree()
    if node then
      node:accept(self.vis)
    end
    return node
  end
  return visitor_stream
end

seen ={}
function mark_as_seen(node)
  seen[tostring(node)] = node
end

function has_been_seen(node)
  return seen[tostring(node)] == node
end

function revcomp(seqid, rng)
  if not seqlengths[seqid] then
    error("cannot reverse features on sequence " .. seqid .. ", length unknown")
  end
  return gt.range_new(seqlengths[seqid] - rng:get_end(),
                      seqlengths[seqid] - rng:get_start())
end

function invert(n)
  if not has_been_seen(n) then
    local r = n:get_range()
    n:set_range(revcomp(n:get_seqid(), r))
    if n:get_strand() == "-" then
      n:set_strand("+")
    elseif n:get_strand() == "+" then
      n:set_strand("-")
    end
    mark_as_seen(n)
  end
end

rv = gt.custom_visitor_new()
function rv:visit_feature(fn)
  for n in fn:children() do
    invert(n)
  end
  return fn
end

instream = gt.gff3_in_stream_new_sorted()
vis_stream = visitor_stream_new(instream, rv)
out_stream = gt.gff3_out_stream_new(vis_stream)

local gn = out_stream:next_tree()
while (gn) do
  gn = out_stream:next_tree()
end
```

with probably some off-by-one adjustment necessary, this is just a quick and dirty draft.

Then you can just:
```
gt revcomp.lua < testdata/eden.gff3
```

**Comment by tmargus** [comment]
hi satta,
thanks for the script. it works perfectly fine with example data but give an error with yeast Saccharomyces cerevisiae chr I.
I used:
[SacCer3.R64-1-1.88.chrI.gff3.gz](http://bit.ly/2mVRSF4)
changed  the line 20  of `revcompl.lua`  to adjust chromosome name and length
`seqlengths = {I = 230218}`

and run 

`gt revcompl.lua <  SacCer3.R64-1-1.88.chrI.gff3 `

and get an error message:
`gt: error: could not execute script revcompl.lua:88: revcompl.lua:37: revcompl.lua:57: bad argument #1 to 'range_new' (must be > 0)`

**Comment by satta** [comment]
That's what I meant with 'off-by-one adjustment' -- one might need to add a `+1` at some point. For example, I think one would need to use
```
return gt.range_new(seqlengths[seqid] - rng:get_end() + 1,
                    seqlengths[seqid] - rng:get_start())
```
in the function `revcomp()` as otherwise you would get coordinates with start position 0, while GFF3 is 1-based. You might need to check and fix these as I didn't test this code thoroughly.

**Comment by tmargus** [comment]
ok! i get it. it worked for most of chromosomes but interestingly chrIX, X,XII and XV give another error.  for example [chrX](http://bit.do/dkn6P)
`seqlengths = { X = 745751 }`
returns error
`gt: error: could not execute script ../revcompl.lua:93: ../revcompl.lua:41: ../revcompl.lua:62: bad argument #1 to 'range_new' (must be <= endpos)`
Does it mean that some feature is out of range?

**Comment by tmargus** [comment]
The part of gff3 (ChrX) what leads to error belongs to the gene YJL041W
```
###
X	SGD	gene	365784	368373	.	+	.	ID=gene:YJL041W;Name=NSP1;biotype=protein_coding;description=FG-nucleoporin component of central core of the nuclear pore complex%3B also part of the nuclear pore complex (NPC) nuclear basket%3B contributes directly to nucleocytoplasmic transport and maintenance of the NPC permeability barrier%3B found in stable complex with Nup82p%2C Gle2p and two other FG-nucleoporins (Nup159p and Nup116p)%3B also found in stable complex with Nic96p and two other FG-nucleoproteins (Nup49p and Nup57p) [Source:SGD%3BAcc:S000003577];gene_id=YJL041W;logic_name=sgd
X	SGD	mRNA	365784	368373	.	+	.	ID=transcript:YJL041W;Parent=gene:YJL041W;Name=NSP1;biotype=protein_coding;transcript_id=YJL041W
X	SGD	exon	365784	365784	.	+	.	Parent=transcript:YJL041W;Name=YJL041W.1;constitutive=1;ensembl_end_phase=1;ensembl_phase=0;exon_id=YJL041W.1;rank=1
X	SGD	CDS	365784	365784	.	+	0	ID=CDS:YJL041W;Parent=transcript:YJL041W;protein_id=YJL041W
X	SGD	exon	365903	368373	.	+	.	Parent=transcript:YJL041W;Name=YJL041W.2;constitutive=1;ensembl_end_phase=1;ensembl_phase=2;exon_id=YJL041W.2;rank=2
X	SGD	CDS	365903	368373	.	+	2	ID=CDS:YJL041W;Parent=transcript:YJL041W;protein_id=YJL041W
###
```

**Comment by lassancejm** [comment]
This code does exactly what I am looking for, but I would like to keep the ids intact.
Is there a way to retain the original ids? 
Thanks!

**Comment by satta** [comment]
It should be enough to set the environment variable `GT_RETAINIDS` to `yes`:
```
$ GT_RETAINIDS=yes gt revcomp.lua < ...
```

**Comment by sanyalab** [comment]
Hello,

Is this script implemented as part of genometools? I have a requirement for exactly this, but cannot find in the current release of genometools. Please advice.

Thanks
Abhijit

**Comment by fishman311** [comment]
Hello,

IN your test data ,The CDs position is forward, from small to large, my CDs position is reverse, from large to small, so it is wrong after conversion, how should I modify, thank you!

Before the change
![image](https://user-images.githubusercontent.com/112450800/187330580-a90e74fc-b62a-471c-bd1f-cb16a29119aa.png)

The modified
![image](https://user-images.githubusercontent.com/112450800/187330787-d693113b-9c57-42d1-9238-2df8e9a380e2.png)
