### ISSUE TITLE
Tirvish giving error

### ISSUE THREAD

**Issue by rimjhimroy** [genometools/genometools#862]
Hello,

I am trying to run gt tirvish with my sequences. I have 3203 scaffolds in a fasta file named as Ch1 - Ch3203.

It gives me the error:

warning: terminal_inverted_repeat_element (generated, line 0) is too short to be translated (0 nt), skipped domain search
gt tirvish: error: query seqid 'Ch1' could match more than one sequence description

Exact command line call triggering the problem:

```
gt suffixerator -db allo.fasta -indexname Tirlist -tis -suf -lcp -des -ssp -dna -mirrored
gt tirvish -index Tirlist -hmms TEs.hmm -mintirlen 20 -mintirdist 100  1> out.txt
```
It is giving a gff output [out.txt](https://github.com/genometools/genometools/files/1056278/out.txt) but it is empty.

GenomeTools version: 1.5.10

GenomeTools compiled with make cairo=no

Operating system: Mac OS X, OS version 10.12.4 and platform x86_64

**Comment by satta** [comment]
Hi,

```
gt tirvish: error: query seqid 'Ch1' could match more than one sequence description
```
This is the interesting line: it says that trying to map GFF3 sequence IDs to sequences in the sequence index, there are ambiguous matches with the default matching strategy, e.g. seqid `Ch1` could match `Ch1` but also `Ch10`, `Ch123` or `Ch1001`. We have some options in other tools to counter that, e.g. to require exact matches. However, the Tirvish tool was never fully completed or released, so such features are probably missing. In any way I would advise against using it in production unless you are happy to double-check your results!

That being said, I guess that a quick workaround for your problem would be to just make sure that the sequence IDs in your input set are substring-free, e.g. `Ch0001`, `Ch0002`, ..., `Ch3203`. so no ID occurs as a substring of another.
