### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by rob123king** [genometools/genometools#868]
## Problem description
I do this:
PATH=$PATH:/home/data/rking/gt-1.5.5-Linux_x86_64-64bit-complete/bin
export LD_LIBRARY_PATH=/home/data/rking/gt-1.5.5-Linux_x86_64-64bit-complete/gtpython

Then test it
python setup.py test

but get this error
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/tmp/easy_install-OwJhcK/mock-2.0.0/pbr-3.0.1-py2.6.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/tmp/easy_install-OwJhcK/mock-2.0.0/pbr-3.0.1-py2.6.egg/pbr/util.py", line 251, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/tmp/easy_install-OwJhcK/mock-2.0.0/pbr-3.0.1-py2.6.egg/pbr/util.py", line 434, in setup_cfg_to_setup_kwargs
    if pkg_resources.evaluate_marker('(%s)' % env_marker):
AttributeError: 'module' object has no attribute 'evaluate_marker'
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-OwJhcK/mock-2.0.0/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'

Any ideas?
Python 2.6.6 used

## Exact command line call triggering the problem

```
gt ...
```

**Comment by rob123king** [comment]
gt (GenomeTools) 1.5.5
Copyright (c) 2003-2015 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2015 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -O3 -m32 -m64 -Werror

**Comment by Garonenur** [comment]
As you have closed this issue, could you also provide the solution? This might help other users who encounter similar problems, also we could adjust our README if this is something we could prevent by better documentation.

**Comment by satta** [comment]
It looks like the problem was rather with the mock library than with GenomeTools? At least that's what the error message seems to suggest...

**Comment by rob123king** [comment]
It was using genometools from script gff3toembl so wasn't really a
genometools issue but a https://github.com/sanger-pathogens/gff3toembl
issue so clsoed it realising I had placed it at wrong tool.

On Sun, Jun 18, 2017 at 11:37 AM, Sascha Steinbiss <notifications@github.com
