### ISSUE TITLE
bed to gff3

### ISSUE THREAD

**Issue by immuno549** [genometools/genometools#879]
## Problem description
Program seems to only print the gff3 file in terminal instead of creating an output file. 

## Exact command line call triggering the problem

```
gt ...Usage: /Users/immuno569/Downloads/gt-1.5.10-Darwin_i386-64bit/bin/gt bed_to_gff3 [BED_file]
Macintosh-4:~ Immuno569$ /Users/Immuno569/Downloads/gt-1.5.10-Darwin_i386-64bit/bin/gt bed_to_gff3 /Users/Immuno569/Downloads/hglft_genome_mm9_VJkl.bed -o Lambda-force yes 
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

gt-1.5.10-Darwin_i386-64bit
## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Mac OSX

**Comment by standage** [comment]
Hmm. So it's not creating a file called `Lambda-force`? I understand that `-force yes` is a separate flag, but without the space there the output file would be interpreted as `Lambda-force`.

Which by the way sounds like a band of villains from a James Bond movie, but probably not what was intended. :-)

**Comment by immuno549** [comment]
Hey 
Thanks for the quick replay. I may be copied and pasted the wrong line. I have tried a bunch of variations. I typed in this: 
Macintosh-4:Downloads Immuno569$ /Users/Immuno569/Downloads/gt-1.5.10-Darwin_i386-64bit/bin/gt bed_to_gff3 /Users/Immuno569/Downloads/hglft_genome_mm9_VJkl.bed -force yes -o lambdamm9
/Users/Immuno569/Downloads/gt-1.5.10-Darwin_i386-64bit/bin/gt bed_to_gff3: error: superfluous argument "-force"
Basically what I would like is for the program to convert my bed file to a gff3 file named lambdamm9. However, it doesn't seem to want to do that. 
Thanks 
    On Tuesday, October 10, 2017, 11:12:55 AM CDT, Daniel Standage <notifications@github.com> wrote:  
 
 
Hmm. So it's not creating a file called Lambda-force? I understand that -force yes is a separate flag, but without the space there the output file would be interpreted as Lambda-force.

Which by the way sounds like a band of villains from a James Bond movie, but probably not what was intended. :-)

**Comment by satta** [comment]
The options (e.g. `-o` etc.) need to come before the input file name. So I would say a more correct invocation would be:
```
/Users/Immuno569/Downloads/gt-1.5.10-Darwin_i386-64bit/bin/gt bed_to_gff3 -force yes -o lambdamm9 /Users/Immuno569/Downloads/hglft_genome_mm9_VJkl.bed 
```
which would also explain the `superfluous argument "-force"` error message.
Does that help?

**Comment by immuno549** [comment]
it did. So did using "<" instead of -o 
Thanks! 
Michael   
    On Tuesday, October 10, 2017, 4:29:20 PM CDT, Sascha Steinbiss <notifications@github.com> wrote:  
 
 
The options (e.g. -o etc.) need to come before the input file name. So I would say a more correct invocation would be:
/Users/Immuno569/Downloads/gt-1.5.10-Darwin_i386-64bit/bin/gt bed_to_gff3 -force yes -o lambdamm9 /Users/Immuno569/Downloads/hglft_genome_mm9_VJkl.bed 

which would also explain the superfluous argument "-force" error message.
Does that help?
