### ISSUE TITLE
cannot malloc(14728584432) memory attempted 

### ISSUE THREAD

**Issue by intirules** [genometools/genometools#884]
## Problem description
Im trying to analize some mammals genomes, im not sure what is the max limit of the archive size i can work with  

## Exact command line call triggering the problem

```
gt suffixerator -db Genoma1.fna -indexname Genoma1.fna -tis -suf -lcp -des -ssp -sds -dna 
```
then i solve it aparently with  
 gt suffixerator -db Genoma1.fna -indexname Genoma1.fna -tis -suf -lcp -des -ssp -sds -dna -memlimit 2GB
but im not sure whats the limit i can work, cause i wanna analize some bigger archives 
## Example minimal input triggering the problem
gt suffixerator -db Genoma1.fna -indexname Genoma1.fna -tis -suf -lcp -des -ssp -sds -dna
cannot malloc(14728584432) memory
attempted on line 145 in file "src/match/sfx-suffixgetset.c"

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

unstable
## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using? 

ubuntu 16.04 lts

**Comment by satta** [comment]
I would say this message is simply a result of not having enough memory to fit all ESA relevant tables into memory (plus swap). As you already found out, using `-memlimit` and/or `-parts` should help here, at the expense of runtime.

**Comment by intirules** [comment]
Thx. I see i gonna try with -parts
