### ISSUE TITLE
genometools-1.5.9 installation problem in Ubuntu 16.04.

### ISSUE THREAD

**Issue by BiodeB** [genometools/genometools#886]
## Problem description
graphics_cairo_api.h:21:19: fatal error: cairo.h: No such file or directory
compilation terminated

## Exact command line call triggering the problem

```
make
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
genometools-1.5.9

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
Ubuntu 16.04

**Comment by satta** [comment]
It looks like you do not have the Cairo library and its development headers installed. Please install them using your distribution's package manager (e.g. `apt install libcairo2-dev`) or use the `cairo=no` make parameter when building. Don't forget to do a `make cleanup` before rebuilding in the latter case!
Also, see the INSTALL file (https://github.com/genometools/genometools/blob/master/INSTALL) for more information about how to build GenomeTools.

**Comment by satta** [comment]
@BiodeB Can you confirm that solved your problem?

**Comment by satta** [comment]
FYI if you just want to run GenomeTools on Ubuntu you can just do a
```
apt-get install genometools
```
