### ISSUE TITLE
Annotate fasta LTR elements with pHMM search option of LTR-digest

### ISSUE THREAD

**Issue by uceleste** [genometools/genometools#887]
Hi All,

I have a multifasta file with examplars LTR elements obtained using LTR-harvest and LTR-digest follwing the "Repeat Library Construction-Advanced" pipeline.

http://weatherby.genetics.utah.edu/MAKER/wiki/index.php/Repeat_Library_Construction-Advanced

I'd like to annotate these fasta LTR elements using the pHMM search option of LTR-digest.
I have installed genometools-1.5.10 including the pHMM search option.

$ make with-hmmer=yes threads=yes cairo=no
$ make install cairo=no prefix=/home/data/genometools-1.5.10/bin

I downloaded all the HMMs from GyDB and converted them in HMMER3.
I created the suffix for my multifasta file:

$ gt suffixerator -tis -des -dna -ssp -db MyLTR.fasta -indexname MyLTR

Finally, I have launched the following command line:

$ gt -j 10 ltrdigest -hmms GyDB/*.hmm -- MyLTR > ltrdigest

The process is running with less than 1 CPU and the output never updates.

Did I miss something in the command line that stuck the process? Or is there something in general that I am missing?

Thank you for any advice

**Comment by satta** [comment]
Hi uceleste,

thanks for getting in touch.

>` $ gt -j 10 ltrdigest -hmms GyDB/*.hmm -- MyLTR > ltrdigest`
> 
> The process is running with less than 1 CPU and the output never updates.
> 
> Did I miss something in the command line that stuck the process? Or is there something in general that I am missing?

Yes, LTRdigest is waiting to read GFF3 annotations of LTR elements in the sequences you provided from standard input, that is most likely why it appears to be hung.  You also need to pass a GFF3 file with LTR retrotransposon candidates to it -- LTRdigest only annotates existing element calls as given in a GFF file. As far as I can see, the solution would be not to use the LTR retrotransposon sequences as sequence input, but the whole original genome, in addition to the original LTRharvest GFF3 output. With both files given to LTRharvest, it will try working on the element annotations one by one, accessing the corresponding DNA sequences at the appropriate places in the original sequence and output augmented GFF3 annotations in the same coordinate space.

Best regards
Sascha

**Comment by uceleste** [comment]
Thank you very much for the explanation, it works now!
