### ISSUE TITLE
Collapse intron coords into just 1 instance?

### ISSUE THREAD

**Issue by anandksrao** [genometools/genometools#888]
## Problem description
Redundancy in  -addintrons step results
Lines reported by 

## Exact command line call triggering the problem
INPUT FILE is at https://ufile.io/f691x (link expires in 30 days)
Permanent link at https://genome.jgi.doe.gov/portal/pages/dynamicOrganismDownload.jsf?organism=Acoerulea#

**Step 1**
-sort -tidy -retainids Acoerulea: Acoerulea_322_v3.1.gene_exons.gff3.gz > Acoerulea_322_v3.1.gene_exons_Sort_Tidy_RetainIDs_gt.gff3
**Step 2**
gt gff3validator Acoerulea_322_v3.1.gene_exons_Sort_Tidy_RetainIDs_gt.gff3 > Acoerulea_322_v3.1.gene_exons_Sort_Tidy_RetainIDs_gt_gff3validator.txt
This step was OK, returned the message "input is valid GFF3"
Note that original GFF3 file from the links above do NOT return this message, hence the sort tody step
**Step 3**
gt gff3 -retainids -addintrons Acoerulea_322_v3.1.gene_exons_Sort_Tidy_RetainIDs_gt.gff3 > Acoerulea_322_v3.1.gene_exons_Sort_Tidy_RetainIDs_gt_INTRONSadded.gff3

## Need to eliminate isoform redundancy
grep -e "32237132" Acoerulea_322_v3.1.gene_exons_Sort_Tidy_RetainIDs_gt_INTRONSadded.gff3
Chr_03	.	intron	32237031	32237132	.	+	.	Parent=Aqcoe3G276000.1.v3.1
Chr_03	.	intron	32237031	32237132	.	+	.	Parent=Aqcoe3G276000.3.v3.1
Chr_03	.	intron	32237031	32237132	.	+	.	Parent=Aqcoe3G276000.2.v3.1

## Problem Definition
I need to extract intron sequences. So when I use these coords, I get the same intron DNA sequence thrice. This happens for several intron regions. How do I extract sequences without redundancy? i.e. the combination of fasta header and sequence should appear just once? Currently I am using gt generated GFF3 file in combination with bedtools getfasta to extract DNA sequences with GFF3+Genome fasta files as inputs

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
gt (GenomeTools) 1.5.8

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
I don't think this is a problem.
make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
uname -a
Linux c11-96 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gordon** [comment]
Please upgrade to the latest version an try again.
