### ISSUE TITLE
src/core/md5_fingerprint.c:20:10: fatal error: md5.h: No such file or directory

### ISSUE THREAD

**Issue by mmokrejs** [genometools/genometools#898]
Hi,
  I am trying to compile genometools-1.5.10 on Gentoo Linux but it somehow fails to find md5.h. Is it the one from openssl/md5.h actually or some lua stuff?

```
src/core/md5_fingerprint.c:20:10: fatal error: md5.h: No such file or directory
 #include "md5.h"
          ^~~~~~~
compilation terminated.
make: *** [Makefile:823: obj/src/core/md5_fingerprint.o] Error 1
```

  Further, I lack section Requirements in the INSTALL file stating what is needed. The listing below is maybe redundant?

```
DEPEND="
    dev-libs/glib
    x11-libs/pango
    cairo? ( x11-libs/cairo )
    sci-biology/samtools:0.1-legacy
    dev-db/sqlite:3
    >=dev-lang/lua-5.1:=
    dev-lua/lpeg
    dev-lua/luafilesystem
    dev-lang/luajit
    dev-libs/tre"
# http://keplerproject.github.io/md5/ ?
# http://keplerproject.org/cgilua ?
RDEPEND="${DEPEND}"
```

  Where do lua-des56 and lua-md5 come from?

**Comment by satta** [comment]
The necessary code should be included in the GenomeTools source itself (https://github.com/genometools/genometools/tree/master/src/external/md5-1.2/src)... these should be used automagically when compiling with default `make` options.

How did you try building the code?

**Comment by mmokrejs** [comment]
With `make useshared=yes 64bit=yes`.

**Comment by satta** [comment]
OK, if you're using `useshared=yes` then you will need to provide the dependency yourself. Unfortunately I don't have any idea if there's anything in Gentoo that provides these.

Are you looking to package GenomeTools for Gentoo or just want to use it? If the latter is the case you might be better off just dropping `useshared=yes`...

**Comment by mmokrejs** [comment]
I am trying to package it for Gentoo. So indeed I cannot accept the default `useshared=no`. Please document in INSTALL file the required packages and their source websites. I can take care of the rest.

**Comment by mmokrejs** [comment]
OK, thank you. I indeed overlooked the listing of dependencies but really, there should be URL what are those packages. Including names of say Debian packages is not a real documentation what one needs.

**Comment by gordon** [comment]
Agreed, I'm happy to merge a corresponding PR.

**Comment by satta** [comment]
Done, see #902.
