### ISSUE TITLE
pip installation

### ISSUE THREAD

**Issue by gonzalezibeas** [genometools/genometools#903]
## Problem description
I am installing genometools with pip on Ubuntu 18.04 and Debian 9.5 (other computer) and at the end, the gt command is not available. After installation with apt-get install genometools it works, so I think is a problem of pip configuration

## Exact command line call triggering the problem
sudo pip install genometools
```
gt ...
```

**Comment by satta** [comment]
I can imagine that the `pip` call only installs the Python bindings for GenomeTools (a pure library module with no executable components). The `gt` command is not part of these, but -- as you have noticed -- available via apt. I wouldn't really expect `pip` to install anything but Python stuff anyway.
