### ISSUE TITLE
New User of Genometools

### ISSUE THREAD

**Issue by APigg0070** [genometools/genometools#914]
## Problem description
I am seeking to utilize genometools LTR Harvest and LTR Digest for ERV annotation purposes. Installing and utilizing genometools requires knowledge outside my current skillset for I have zero experience in coding. Is there a guide available anywhere for beginners? I have downloaded Cygwin following instructions on the genometools.org website for it to be run on Windows. I am unsure of what to do next. I read in other places that some use ubuntu, is this the better way?

**Comment by satta** [comment]
While I haven't used Cygwin and the Windows version of GenomeTools in a while, I don't recommend using it for large runs as I remember the performance on that platform to be worse than on a Unix-like OS.

My recommendation: If you can, use Ubuntu or Debian (in a VM or spare machine if you want), install the packages from there (for the LTR* tools that would be the `genometools` and `hmmer` packages) and you're good to go. If I am not mistaken, GenomeTools is also in Homebrew if you're on a Mac, for example, and can use Homebrew.

**Comment by APigg0070** [comment]
I was able to use Ubuntu to install the packages I needed. Everything is working smoothly so far. Thank you
