### ISSUE TITLE
several compile issues on Fedora 30

### ISSUE THREAD

**Issue by vpbrendel** [genometools/genometools#915]
## Problem description

Compilation errors as follows:

1)
rc/match/eis-bwtseq-context.c: In function \u2018gt_BWTSCRFGet\u2019:
src/match/eis-bwtseq-context.c:291:39: error: \u2018cxm\u2019 directive output may be truncated writing 3 bytes into a region of size between 2 and 6 [-Werror=format-truncation=]
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |                                       ^~~
src/match/eis-bwtseq-context.c:291:7: note: \u2018snprintf\u2019 output between 6 and 10 bytes into a destination of size 8
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/match/eis-bwtseq-context.c: In function \u2018gt_BWTSeqCRLoad\u2019:
src/match/eis-bwtseq-context.c:291:39: error: \u2018cxm\u2019 directive output may be truncated writing 3 bytes into a region of size between 2 and 6 [-Werror=format-truncation=]
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |                                       ^~~
src/match/eis-bwtseq-context.c:291:7: note: \u2018snprintf\u2019 output between 6 and 10 bytes into a destination of size 8
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/match/eis-bwtseq-context.c:291:39: error: \u2018cxm\u2019 directive output may be truncated writing 3 bytes into a region of size between 2 and 6 [-Werror=format-truncation=]
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |                                       ^~~
src/match/eis-bwtseq-context.c:291:7: note: \u2018snprintf\u2019 output between 6 and 10 bytes into a destination of size 8
  291 |       snprintf(buf, sizeof (buf), ".%ucxm", (unsigned)mapIntervalLog2);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:811: obj/src/match/eis-bwtseq-context.o] Error 1

2)
src/ltr/ltr_cluster_prepare_seq_visitor.c: In function \u2018gt_ltr_cluster_prepare_seq_visitor_feature_node\u2019:
src/ltr/ltr_cluster_prepare_seq_visitor.c:146:39: error: \u2018%lu\u2019 directive output may be truncated writing between 1 and 20 bytes into a region of size between 0 and 8191 [-Werror=format-truncation=]
  146 |       (void) snprintf(header, BUFSIZ, "%s_"GT_WU"_"GT_WU"", buffer, range.start,
      |                                       ^~~~~
In file included from /usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/array_api.h:23,
                 from /usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/array.h:21,
                 from src/ltr/ltr_cluster_prepare_seq_visitor.c:19:
/usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/types_api.h:55:16: note: format string is defined here
   55 | #define GT_WU "%lu"
      |                ^~~
src/ltr/ltr_cluster_prepare_seq_visitor.c:146:14: note: \u2018snprintf\u2019 output between 5 and 8234 bytes into a destination of size 8192
  146 |       (void) snprintf(header, BUFSIZ, "%s_"GT_WU"_"GT_WU"", buffer, range.start,
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  147 |                       range.end);
      |                       ~~~~~~~~~~
src/ltr/ltr_cluster_prepare_seq_visitor.c:109:39: error: \u2018%lu\u2019 directive output may be truncated writing between 1 and 20 bytes into a region of size between 0 and 8191 [-Werror=format-truncation=]
  109 |       (void) snprintf(header, BUFSIZ, "%s_"GT_WU"_"GT_WU"", buffer, range.start,
      |                                       ^~~~~
In file included from /usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/array_api.h:23,
                 from /usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/array.h:21,
                 from src/ltr/ltr_cluster_prepare_seq_visitor.c:19:
/usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/types_api.h:55:16: note: format string is defined here
   55 | #define GT_WU "%lu"
      |                ^~~
src/ltr/ltr_cluster_prepare_seq_visitor.c:109:14: note: \u2018snprintf\u2019 output between 5 and 8234 bytes into a destination of size 8192
  109 |       (void) snprintf(header, BUFSIZ, "%s_"GT_WU"_"GT_WU"", buffer, range.start,
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  110 |                       range.end);
      |                       ~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:811: obj/src/ltr/ltr_cluster_prepare_seq_visitor.o] Error 1

3)
src/ltr/ltr_cluster_stream.c: In function \u2018process_feature\u2019:
src/ltr/ltr_cluster_stream.c:352:41: error: \u2018%lu\u2019 directive output may be truncated writing between 1 and 20 bytes into a region of size between 0 and 8191 [-Werror=format-truncation=]
  352 |         (void) snprintf(header, BUFSIZ, "%s_"GT_WU"_"GT_WU"", buffer,
      |                                         ^~~~~
In file included from /usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/array_api.h:23,
                 from /usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/array.h:21,
                 from src/ltr/ltr_cluster_stream.c:19:
/usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/types_api.h:55:16: note: format string is defined here
   55 | #define GT_WU "%lu"
      |                ^~~
src/ltr/ltr_cluster_stream.c:352:16: note: \u2018snprintf\u2019 output between 5 and 8234 bytes into a destination of size 8192
  352 |         (void) snprintf(header, BUFSIZ, "%s_"GT_WU"_"GT_WU"", buffer,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  353 |                         range.start, range.end);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~
src/ltr/ltr_cluster_stream.c:344:41: error: \u2018%lu\u2019 directive output may be truncated writing between 1 and 20 bytes into a region of size between 0 and 8191 [-Werror=format-truncation=]
  344 |         (void) snprintf(header, BUFSIZ, "%s_"GT_WU"_"GT_WU"", buffer,
      |                                         ^~~~~
In file included from /usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/array_api.h:23,
                 from /usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/array.h:21,
                 from src/ltr/ltr_cluster_stream.c:19:
/usr/local/src/GENOMETOOLS/OLD/genometools-1.5.9/src/core/types_api.h:55:16: note: format string is defined here
   55 | #define GT_WU "%lu"
      |                ^~~
src/ltr/ltr_cluster_stream.c:344:16: note: \u2018snprintf\u2019 output between 5 and 8234 bytes into a destination of size 8192
  344 |         (void) snprintf(header, BUFSIZ, "%s_"GT_WU"_"GT_WU"", buffer,
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  345 |                         range.start, range.end);
      |                         ~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:811: obj/src/ltr/ltr_cluster_stream.o] Error 1

NOTE: all issues are easily fixed by increasing the buffers, but I have not looked into what the correct minimum size should be.
## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
make using the following compiler
   gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
Fedora 30, x86_64

**Comment by satta** [comment]
It should be enough to double the `header` buffer size. PR to follow.
