### ISSUE TITLE
LTR_harvest: 'cannot flock: Function not implemented'

### ISSUE THREAD

**Issue by WTarabidopsis** [genometools/genometools#918]
Hi,
Recently, when I was running LTR_harvest, an issue comes up and I have no idea what it means and how to solve this problem.

The genometools was installed by conda 
`conda install -c bioconda genometools-genometools`

The index was generated by following the manual:
`gt suffixerator -db etuer.test.fasta -indexname etuer -tis -suf -lcp -des -ssp -sds -dna`

Then I tried to run LTR_harvest by using the command:
`gt ltrharvest -index etuer -minlenltr 100 -maxlenltr 7000 -mintsd 4 -maxtsd 6 -motif TGCA -motifmis 1 -similar 85 -vic 10 -seed 20 -seqids yes`

However, the software gave a message and ended:
`cannot flock: Function not implemented`

What does this mean? Is there something wrong with the installation or the software setup?
Thanks in advance!

**Comment by gordon** [comment]
You are using a file system which doesn't implement file locking (`flock()`), probably a network file system. If you set the environment variable `GT_NO_FLOCK` to any value `flock()` will be disabled and your calls will work. But then you have to make sure yourself that no two instances try to write the same files.
