### ISSUE TITLE
Multithreaded suffixerator fails to build a working set of files

### ISSUE THREAD

**Issue by rmhubley** [genometools/genometools#922]
## Problem description
Using the multithreaded version of suffixerator does not generate a working set of data files.

## Exact command line call triggering the problem

```
make cleanup
make threads=yes cairo=no


gt -j 10 suffixerator -db seq2.fa -indexname seq2 -tis -suf -lcp -des -ssp -sds -dna
         22 Oct  3 14:23 seq2.des
    2000320 Oct  3 14:23 seq2.esq
    8099926 Oct  3 14:13 seq2.fa
    7999921 Oct  3 14:23 seq2.lcp
          0 Oct  3 14:23 seq2.llv  <---- difference
         33 Oct  3 14:23 seq2.md5
        467 Oct  3 14:23 seq2.prj
          0 Oct  3 14:23 seq2.sds
 63999368 Oct  3 14:23 seq2.suf

gt ltrharvest -index seq2
**no results**


gt 10 suffixerator -db seq2.fa -indexname seq2 -tis -suf -lcp -des -ssp -sds -dna
        22 Oct  3 14:26 seq2.des
   2000320 Oct  3 14:26 seq2.esq 
   8099926 Oct  3 14:13 seq2.fa
   7999921 Oct  3 14:26 seq2.lcp
   2475488 Oct  3 14:26 seq2.llv
        33 Oct  3 14:26 seq2.md5
       476 Oct  3 14:26 seq2.prj
         0 Oct  3 14:26 seq2.sds
63999368 Oct  3 14:26 seq2.suf

gt ltrharvest -index seq2
** 136 results **
```

## Example minimal input triggering the problem
[seq2.fa.gz](https://github.com/genometools/genometools/files/3688167/seq2.fa.gz)

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
gt (GenomeTools) 1.5.10
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -Werror

But also 1.5.9 exhibits the same behavior

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
make cleanup
make threads=yes cairo=no

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

RedHat 7.6 ( 4.1.12-124.24.3.el7uek.x86_64 )

**Comment by satta** [comment]
I can confirm this and also noticed that using `-j 1` does not trigger the problem, it only occurs when j > 1.

**Comment by satta** [comment]
LCP table generation (that the `.llv` files are a part of) is experimental and not fully implemented in a multithreaded `suffixerator` run. After consulting with the original author of the respective code, I have put in a PR to disable the use of the `-lcp` option when `-j`>1.

**Comment by rmhubley** [comment]
Isn't the LCP required for ltrharvest?  If so, then running ltrharvest on a mammalian size genome is really quite slow.

**Comment by satta** [comment]
LTRharvest still works when run with multithreading. It's just the index calculation that needs to run without -- but that only needs to be done once per genome:
```
$ gt -j 1 suffixerator -db seq2.fa -indexname seq2 -tis -suf -lcp -des -ssp -sds -dna
...
$ gt -j 10 ltrharvest -index seq2 -seed 20 -minlenltr 500 -maxlenltr 800 -mindistltr 1000 -maxdistltr 5000 -similar 90 -overlaps no -tabout no -seqids yes -md5 yes > seq2_1.gff3
...
$ gt -j 10 ltrharvest -index seq2 -seed 30 -minlenltr 500 -maxlenltr 1000 -mindistltr 3000 -maxdistltr 10000 -similar 80 -overlaps best -tabout no -seqids yes -md5 yes > seq2_2.gff3
...
```
In this case the latter two calls would then be run with multithreaded LTR detection while the initial index generation is done in a single thread (but is quite fast anyway IMHO).
