### ISSUE TITLE
gt gff3 -sort incorrectly reports Parent not defined

### ISSUE THREAD

**Issue by mcsimenc** [genometools/genometools#928]
## Problem description
The command below reports the following, which can be demonstrated false by examining the test.gff file posted below:
```
gt gff3: error: Parent "LTR_retrotransposon1" on line 14 in file "test.gff" was not defined (via "ID=")
```

## Exact command line call triggering the problem

```
gt gff3 -sort test.gff
```

## Example minimal input triggering the problem
test.gff:
```
##gff-version 3
##sequence-region   lcl|NC_hic_scaffold_01 17352 47215727
lcl|NC_hic_scaffold_01	LTRharvest	repeat_region	17352	22870	.	+	.	ID=repeat_region1
lcl|NC_hic_scaffold_01	LTRharvest	target_site_duplication	17352	17356	.	+	.	Parent=repeat_region1
lcl|NC_hic_scaffold_01	LTRharvest	LTR_retrotransposon	17357	22865	.	+	.	ID=LTR_retrotransposon1;Parent=repeat_region1;ltr_similarity=96.02;seq_number=0;dfamClassification=Copia1-I_DM;repbaseClassification=Copia-45_RC-I
lcl|NC_hic_scaffold_01	LTRharvest	long_terminal_repeat	17357	17833	.	+	.	Parent=LTR_retrotransposon1
lcl|NC_hic_scaffold_01	LTRdigest	protein_match	19935	20142	8.7e-06	+	.	Parent=LTR_retrotransposon1;reading_frame=1;name=Retrotran_gag_2
lcl|NC_hic_scaffold_01	LTRdigest	protein_match	20135	20345	5.1e-13	+	.	Parent=LTR_retrotransposon1;reading_frame=0;name=Retrotran_gag_2
lcl|NC_hic_scaffold_01	LTRdigest	protein_match	21026	21074	7.7e-06	+	.	Parent=LTR_retrotransposon1;reading_frame=0;name=gag_pre-integrs
lcl|NC_hic_scaffold_01	LTRdigest	protein_match	21215	21338	2e-05	+	.	Parent=LTR_retrotransposon1;reading_frame=0;name=RVT_2
lcl|NC_hic_scaffold_01	LTRharvest	long_terminal_repeat	22391	22865	.	+	.	Parent=LTR_retrotransposon1
lcl|NC_hic_scaffold_01	LTRharvest	target_site_duplication	22866	22870	.	+	.	Parent=repeat_region1
###
lcl|NC_hic_scaffold_01	getorf	ORF	17966	18386	.	+	.	ID=LTR_retrotransposon1.ORF.01;Parent=LTR_retrotransposon1
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
1.5.10

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
yes, `make prefix=.`

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
Scientific Linux release 6.8 (Carbon) x86_64

**Comment by satta** [comment]
Try removing the `###` in line 13. It separates features that are part of the same connected component; removing it solves your problem. It seems that the parser mifght be overly strict by disallowing a feature referring to a previously introduced feature to be separated from the referred-to feature. AFAICS the specification (https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) only expects any _forward_ references to be satisfied up to the `###` marker. 
I'm going to flag this as a bug unless someone objects (e.g. @gordon?)

**Comment by gordon** [comment]
I always understood the spec in the way that the parser can flush all all objects when encountering a `###` line:

> After seeing this directive, a program that is processing the file serially can close off any open objects that it has created and return them, thereby allowing iterative access to the file. Otherwise, software cannot know that a feature has been fully populated by its subfeatures until the end of the file has been reached.

If we wouldn't treat it like that we would never been able to flush anything. I think that the term *forward references* is just misleading in the spec.

**Comment by standage** [comment]
> If we wouldn't treat it like that we would never been able to flush anything.

I agree. The directive has no value if we don't treat it as @gordon has described.

**Comment by satta** [comment]
Agreed. Removing the bug flag. I guess the best advice for people running into this issue (e.g. via adding ORFs from EMBOSS's getorf as possibly used in OP's example) then is to remove the markers and run the reslt through `gt gff3 -tidy -retainids`?

**Comment by gordon** [comment]
Yes, that seems reasonable. Maybe also add `-sort` while we are add it.
