### ISSUE TITLE
What does chain2dim do? 

### ISSUE THREAD

**Issue by alexlenail** [genometools/genometools#932]
The documentation for vmatch refers to a manual for chain2dim. However, although http://genometools.org/tools/gt_chain2dim.html describes the options for chain2dim, it does not describe what match chaining is in the first place.

**Comment by satta** [comment]
IIRC, this tool implements the two-dimensional match chaining with gap constraints as outlined, for instance, in http://genomethreader.org/doc/GreBreSpaKur2005.pdf.  Section 5.2 in the paper describes the approach.
