### ISSUE TITLE
1.6.1: src/core/md5_fingerprint.c:20:10: fatal error: md5.h: No such file or directory

### ISSUE THREAD

**Issue by mmokrejs** [genometools/genometools#945]
Hi,
  I wanted to update the package for Gentoo Linux from 1.5.10 to 1.6.1 but now it fails with:

```
[compile md5_encoder.o]
[compile md5_fingerprint.o]
src/core/md5_fingerprint.c:20:10: fatal error: md5.h: No such file or directory
   20 | #include "md5.h"
      |          ^~~~~~~
[compile md5_seqid.o]
compilation terminated.
make: *** [Makefile:822: obj/src/core/md5_fingerprint.o] Error 1
```

I assume I have the right package but in an unexpected location. Please tell me from where is the md5.h supposed to come from and how you detect for its presence automatically.

[build.log](https://github.com/genometools/genometools/files/4521809/build.log)

**Comment by gordon** [comment]
`pkg-config --libs lua5.1-md5` is where md5.h comes from is you use `useshared=yes`.

**Comment by gordon** [comment]
See also issue #898 and PR #902.

**Comment by mmokrejs** [comment]
Thank you, good points, so it maybe never worked, hmm. Anyway, I do have the following installed:

`dev-lang/lua-5.1.5-r4` and `dev-lua/lua-md5-1.2` installed. Seems the package does not install the pkg-config file at all:

```
# equery files dev-lua/lua-md5 
* Searching for lua-md5 in dev-lua ...
 * Contents of dev-lua/lua-md5-1.2:
/usr
/usr/lib
/usr/lib/lua
/usr/lib/lua/5.1
/usr/lib/lua/5.1/des56.so
/usr/lib/lua/5.1/md5
/usr/lib/lua/5.1/md5/core.so
/usr/share
/usr/share/doc
/usr/share/doc/lua-md5-1.2
/usr/share/doc/lua-md5-1.2/README.bz2
/usr/share/lua
/usr/share/lua/5.1
/usr/share/lua/5.1/md5.lua
#
```

**Comment by satta** [comment]
Looks like in Gentoo the package does not contain the source anymore. Debian has a separate `-dev` package for that: https://packages.debian.org/buster/amd64/lua-md5-dev/filelist

**Comment by mmokrejs** [comment]
Right, the `install` target of the Makefile does not install the headers. I can get them copied to a proper place manually but why isn't that a default?

How to register the package into `pkg-config` I will need to figure out yet. I do not have any `*.pc` files in the source tree.

Installing the headers into `/usr/include` helped to overcome the issue and the next-one is missing `<samtools/sam.h>`. So I will need to poke through the deps and ensure tehy instll properly the headers and iseally register into `pkg-config`.
