### ISSUE TITLE
src/match/tagerator.c:237:33: error: ‘gt_fromitv2so’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by onmyojiyys** [genometools/genometools#946]
## Problem description
compile error when I  installed genometools

## Exact command line call triggering the problem

```
make
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

genometools-1.6.1
## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
make

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015

**Comment by satta** [comment]
Thanks for your report! Can you please provide the full error message or build log so we can find out what might have gone wrong?

**Comment by onmyojiyys** [comment]
[compile tagerator.o]
src/match/tagerator.c: In function ‘checkmstats’:
src/match/tagerator.c:237:33: error: ‘gt_fromitv2so’ undeclared (first use in this function)
     GtArrayGtUword *mstatspos = gt_fromitv2so;
                                 ^
src/match/tagerator.c:237:33: note: each undeclared identifier is reported only once for each function it appears in
src/match/tagerator.c:237:5: error: expected declaration or statement at end of input
     GtArrayGtUword *mstatspos = gt_fromitv2so;
     ^
src/match/tagerator.c:237:21: error: unused variable ‘mstatspos’ [-Werror=unused-variable]
     GtArrayGtUword *mstatspos = gt_fromitv2so;
                     ^
src/match/tagerator.c:236:13: error: unused variable ‘idx’ [-Werror=unused-variable]
     GtUword idx;
             ^
src/match/tagerator.c:235:20: error: unused variable ‘witnessposition’ [-Werror=unused-variable]
     GtUword *sptr, witnessposition;
                    ^
src/match/tagerator.c:235:14: error: unused variable ‘sptr’ [-Werror=unused-variable]
     GtUword *sptr, witnessposition;
              ^
src/match/tagerator.c:234:13: error: unused variable ‘cc’ [-Werror=unused-variable]
     GtUchar cc;
             ^
src/match/tagerator.c:237:5: error: expected declaration or statement at end of input
     GtArrayGtUword *mstatspos = gt_fromitv2so;
     ^
src/match/tagerator.c: At top level:
src/match/tagerator.c:81:13: error: ‘tgr_showmatch’ defined but not used [-Werror=unused-function]
 static void tgr_showmatch(void *processinfo,const GtIdxMatch *match)
             ^
src/match/tagerator.c:198:13: error: ‘tgr_storematch’ defined but not used [-Werror=unused-function]
 static void tgr_storematch(void *processinfo,const GtIdxMatch *match)
             ^
src/match/tagerator.c:209:13: error: ‘checkmstats’ defined but not used [-Werror=unused-function]
 static void checkmstats(void *processinfo,
             ^
cc1: all warnings being treated as errors
make: *** [obj/src/match/tagerator.o] Error 1

**Comment by satta** [comment]
Could you please double-check if there hasn't been an accidental newline introduced in the code for `src/match/tagerator.c` or maybe the code has been truncated somehow?
The identifier the compiler complains about (`gt_ftomitv2so`) does not exist in the GenomeTools code like this but rather as a prefix of a proper function name (`gt_fromitv2sortedmatchpositions`):
```
$ git grep gt_fromitv2so
...
src/match/tagerator.c:    GtArrayGtUword *mstatspos = gt_fromitv2sortedmatchpositions(
src/match/tagerator.c:    GtArrayGtUword *mstatspos = gt_fromitv2sortedmatchpositions(
```

It might help here to check out a fresh copy of the source code and verify that it is complete.

**Comment by onmyojiyys** [comment]
Thanks very much！The problem is solved.
src/match/tagerator.c was not complete. An error has occurred when download or gunzip. It`s ok while I re-download it.

**Comment by satta** [comment]
Good news! :)
