### ISSUE TITLE
homopolymer problem in LTRharvest

### ISSUE THREAD

**Issue by wyim-pgl** [genometools/genometools#948]
## Problem description
One of chromosome includes a homopolymer such as A X 18000bp or G X 18000bp. LTRharvest is hanging for 3days without any output.

## Exact command-line call triggering the problem

```bash
gt suffixerator -db test -indexname test -suf -lcp -des -ssp -sds -dna -mirrored -withradixsort -iterscan -showprogress

gt ltrharvest -index test -minlenltr 100 -maxlenltr 7000 -mintsd 4 -maxtsd 6 -motif TGCA -motifmis 1 -similar 85 -vic 10 -seed 20 -seqids yes
```

## Example minimal input triggering the problem

https://www.dropbox.com/t/yTVS4ooKyIXQXoZq

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
Tested two versions
```
   ~/scratch/bin/genometools-1.6.1/bin/gt -version
/data/gpfs/home/wyim/scratch/bin/genometools-1.6.1/bin/gt (GenomeTools) 1.6.1
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: x86_64-conda_cos6-linux-gnu-cc (crosstool-NG 1.24.0.123_1667d2b) 7.5.0
Compile flags: -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data/gpfs/home/wyim/scratch/bin/miniconda3/envs/edta/include -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -W
```
```
/data/gpfs/home/wyim/scratch/bin/gt-1.5.10-Linux_x86_64-64bit-complete/bin/gt (GenomeTools) 1.5.10
Copyright (c) 2003-2016 G. Gremme, S. Steinbiss, S. Kurtz, and CONTRIBUTORS
Copyright (c) 2003-2016 Center for Bioinformatics, University of Hamburg
See LICENSE file or http://genometools.org/license.html for license details.

Used compiler: cc (Ubuntu 4.9.1-16ubuntu6) 4.9.1
Compile flags:  -g -Wall -Wunused-parameter -pipe -fPIC -Wpointer-arith -Wno-unknown-pragmas -O3 -m32 -m64 -Werror
```
## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
I used below. 1.5.10 is binary 
```bash
 make -j 8 cairo=no   threads=yes
```
## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
```
CentOS Linux release 7.6.1810 (Core)
Derived from Red Hat Enterprise Linux 7.6 (Source)
Cluster Manager v8.2
```

**Comment by satta** [comment]
Yes, I can see that being a problem. Have you tried hard-masking these regions with N? In general, I would advise to mask low complexity regions before indexing them for LTRharvest runs -- too much false positive potential due to a high number of uninteresting candidates.

**Comment by wyim-pgl** [comment]
It makes sense. Do you have any making software in mind? Otherwise, I may use TRF and mask by bedtools.

**Comment by satta** [comment]
Not really, just use what you think is the best tool for the job. I'm not an everyday user of these tools.

**Comment by satta** [comment]
Dis you have any success with masking? If so, can we close this?

**Comment by wyim-pgl** [comment]
I masked with TRF and worked well.
