### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by sanvva** [genometools/genometools#950]
## Problem description
[create obj/gt_config.h]
[compile sqlite3.o]
[compile alphabet.o]
[compile array.o]
[compile array2dim.o]
[compile array2dim_sparse.o]
[compile array3dim.o]
[compile basename.o]
[compile bioseq.o]
src/core/bioseq.c: In function 'construct_bioseq_files':
src/core/bioseq.c:121:18: error: ignoring return value of 'fwrite', declared with attribute warn_unused_result [-Werror=unused-result]
       if (i > 0) fwrite(buf, 1, i, tmpfile);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:823: obj/src/core/bioseq.o] Error 1

## Exact command line call triggering the problem

make 64bit=yes universal=yes useshared=no  cairo=no prefix=/ds3200_1/users_root/hezhengshan/bin/08Repeat/genometools1.6.1

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
genometools-1.6.1

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
make 64bit=yes universal=yes useshared=no  cairo=no prefix=/ds3200_1/users_root/hezhengshan/bin/08Repeat/genometools1.6.1

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
x86_64

**Comment by satta** [comment]
Can you please try compiling with:
```
make 64bit=yes useshared=no errorcheck=no cairo=no prefix=/ds3200_1/users_root/hezhengshan/bin/08Repeat/genometools1.6.1
```

FYI there's almost never a reason to use `universal=yes` anymore unless you are using an old PowerPC Mac. The `errorcheck=no` makes the build pass even in the presence of compiler warnings, which might be an indication that you have a newer compiler that checks more or more stringently than the ones we tested with. What is your compiler version?

**Comment by sanvva** [comment]
@satta 
"errorcheck=no" works!  Great!
$ make prefix=/path got the same error! 

my compiler version: **gcc (GCC) 7.2.0**
$ strings /usr/lib64/libc.so.6 | grep GLIBC_ got higest glib version "GLIBC_2.17".

I also downloaded the binary version from here: http://genometools.org/pub/binary_distributions/
gt-1.6.1-Linux_x86_64_x86_64-64bit/bin/gt got error:  "**/usr/lib64/libc.so.6: version `GLIBC_2.27' not found**"
gt-1.5.10-Linux_x86_64-64bit-complete/bin/gt goes well.

**Comment by satta** [comment]
> @satta
> "errorcheck=no" works! Great!

Good to hear.

> $ make prefix=/path got the same error!

Yep, because there's no `errorcheck` in there ;)

> my compiler version: **gcc (GCC) 7.2.0**
> $ strings /usr/lib64/libc.so.6 | grep GLIBC_ got higest glib version "GLIBC_2.17".

OK, this is not the newest one. Interesting that there's still a warning we haven't caught yet...

> I also downloaded the binary version from here: http://genometools.org/pub/binary_distributions/
> gt-1.6.1-Linux_x86_64_x86_64-64bit/bin/gt got error: "**/usr/lib64/libc.so.6: version `GLIBC_2.27' not found**"

This is most likely because your Linux distribution is too different from the one we built the binary on. In that case you would indeed have to build your own, which seems to have worked now, right? If so, can we close the issue?

**Comment by sanvva** [comment]
@satta It works now!
