### ISSUE TITLE
ltrharvest is not finishing in 5 days

### ISSUE THREAD

**Issue by hung-th** [genometools/genometools#962]
## Problem description

I am running ltrharvest on a ~600 Mbp tree genome. It is not finishing in 5 days therefore I wonder whether ltrharvest hangs without any error or output. It is running on 64 Gb RAM with 4 TB diskspace. I would be happy to provide the files via emailing a link.

## Exact command line call triggering the problem

```
gt suffixerator -db Dacoc.fa -indexname esa_index -tis -suf -lcp -des -ssp -sds -dna
gt ltrharvest -index esa_index -out ltrharvest.out > ltrharvest.log 2>&1
```

## Example minimal input triggering the problem

The esa_index* files are generated from the input genome.

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

1.6.1

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.

`make threads=yes`

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Debian 10

Thank you very much for your help.

**Comment by satta** [comment]
Just a hunch: Does your genome contain many and/or long low complexity regions like simple repeats? LTRharvest might call lots of unsuitable candidates there, wasting time in the long run. If so, it might help masking these before building the index.

**Comment by ehrenbentz** [comment]
Same issue here on a mammalian genome. Any solutions to this?

**Comment by satta** [comment]
Probably related to (or duplicate of) #970.

**Comment by satta** [comment]
Did masking simple repeats help?

**Comment by hung-th** [comment]
Deepest apologies I have forgotten about this issue.

Yes I masked the simple repeats with `RepeatMasker -pa 16 -gff -noint -lib consensi.fa.classified ref.fasta`

Then do the LTRharvest:
```
gt suffixerator -db ref.fasta.masked -indexname esa_index -tis -suf -lcp -des -ssp -sds -dna -lossless > suffixerator.log 2>&1
gt ltrharvest -index esa_index -tabout no -seqids -md5 > ref_ltrharvest.gff3
```

LTRharvest does not hang and finish efficiently.

Thank you very much your help. I will close the issue for now.
