### ISSUE TITLE
rc/ltr/ltrdigest_file_out_stream.c:121:32 ... [-Werror=format-truncation=]

### ISSUE THREAD

**Issue by kinestetika** [genometools/genometools#967]
## Problem description
While compiling genometools 1.6.1 on an up-to-date (April 15 2021) Arch Linux system (X86-64) with gcc version 10.2.0, I run into the following: 
...
[compile ltr_refseq_match_stream.o]
[compile ltrdigest_file_out_stream.o]
src/ltr/ltrdigest_file_out_stream.c: In function ‘gt_ltrelement_format_description.constprop.isra’:
src/ltr/ltrdigest_file_out_stream.c:121:32: error: ‘%s’ directive output may be truncated writing up to 8191 bytes into a region of size 255 [-Werror=format-truncation=]
  121 |   ret = snprintf(buf, buflen, "%s_"GT_WU"_"GT_WU"", tmpstr, e->leftLTR_5+1,
      |                                ^~                   ~~~~~~
src/ltr/ltrdigest_file_out_stream.c:121:9: note: ‘snprintf’ output between 5 and 8234 bytes into a destination of size 255
  121 |   ret = snprintf(buf, buflen, "%s_"GT_WU"_"GT_WU"", tmpstr, e->leftLTR_5+1,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  122 |                  e->rightLTR_3+1);
      |                  ~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:823: obj/src/ltr/ltrdigest_file_out_stream.o] Error 1

## Exact command line call triggering the problem
make

Adding "errorcheck=no" circumvents the compilation issue but the code likely needs a permanent fix.

**Comment by satta** [comment]
This should be fixed in the current master (not in a release yet) via commit https://github.com/genometools/genometools/commit/51205942b1f41abdf841771deac4e0e35d7d5016. Could you try that instead if the released version? I have just confirmed it compiles for me with gcc version 10.2.1 20210110 (Debian 10.2.1-6).

**Comment by kinestetika** [comment]
Compiled without errors or warnings, thanks!
