### ISSUE TITLE
#include problems while compiling genometools 1.6.1  

### ISSUE THREAD

**Issue by kinestetika** [genometools/genometools#968]
## Problem description
while compiling genometools 1.61 on an up to date arch linux installation (April 15 2021), compilation fails as follows:
...
[link libsqlite.a]
ar: `u' modifier ignored since `D' is the default (see `U')
ar: creating lib/libsqlite.a
[link libgenometools.a]
ar: creating lib/libgenometools.a
[link libbz2.a]
ar: `u' modifier ignored since `D' is the default (see `U')
ar: creating lib/libbz2.a
[link libz.a]
ar: `u' modifier ignored since `D' is the default (see `U')
ar: creating lib/libz.a
[link libexpat.a]
ar: `u' modifier ignored since `D' is the default (see `U')
ar: creating lib/libexpat.a
[gathering public API symbols to obj/public_symbols.lst]
[link libgenometools.so]
/usr/bin/ld: obj/src/mgth/mg_combinedscore.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: multiple definition of `gt_cstr_nofree_ulp_hashtype'; obj/src/mgth/metagenomethreader.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: first defined here
/usr/bin/ld: obj/src/mgth/mg_compute_gene_prediction.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: multiple definition of `gt_cstr_nofree_ulp_hashtype'; obj/src/mgth/metagenomethreader.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: first defined here
/usr/bin/ld: obj/src/mgth/mg_computepath.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: multiple definition of `gt_cstr_nofree_ulp_hashtype'; obj/src/mgth/metagenomethreader.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: first defined here
/usr/bin/ld: obj/src/mgth/mg_outputwriter.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: multiple definition of `gt_cstr_nofree_ulp_hashtype'; obj/src/mgth/metagenomethreader.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: first defined here
/usr/bin/ld: obj/src/mgth/mg_reverse.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: multiple definition of `gt_cstr_nofree_ulp_hashtype'; obj/src/mgth/metagenomethreader.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: first defined here
/usr/bin/ld: obj/src/mgth/mg_xmlparser.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: multiple definition of `gt_cstr_nofree_ulp_hashtype'; obj/src/mgth/metagenomethreader.o:/home/kinestetika/bin/repeats/genometools-1.6.1/src/mgth/metagenomethreader.h:224: first defined here

## Exact command line call triggering the problem
make errorcheck=no

gcc version 10.2.0

**Comment by satta** [comment]
This should be fixed in the current master (not in a release yet) via commit https://github.com/genometools/genometools/commit/30ae36037228dc4ed174e8462f3489638e6f5e76. Could you try that instead if the released version? I have just confirmed it compiles for me with gcc version 10.2.1 20210110 (Debian 10.2.1-6).

**Comment by kinestetika** [comment]
Compiled without errors or warnings, thanks!
