### ISSUE TITLE
Update the CI platform

### ISSUE THREAD

**Issue by satta** [genometools/genometools#973]
## Problem description

Travis-CI.org is shutting down and we would need to migrate our CI to Travis-CI.com (https://blog.travis-ci.com/2021-05-07-orgshutdown).
Regarding Travis, we have seen that macOS builds take too long because there are no binary packages for the dependencies for the OS version they are running, so they need to be built from source, which exceeds their time limit for runs.

I am wondering whether we might want to migrate the CI to GitHub Actions completely, which appears to be as a well-integrated, feature-rich solution, which will hopefully be supported for a long time. This would also remove dependencies to external services even more.

Any comments? Alternatively we could just move the CI to Travis-CI.com as described and just remove the macOS tests.

**Comment by gordon** [comment]
I agree with @satta that migrating to GitHub Actions completely is the way to go here.

**Comment by satta** [comment]
See new PR #974
