### ISSUE TITLE
FeatureRequest:    Can we add gtpython FeatureNode support for  gtlib.gt_genome_node_set_range() and gt_feature_node_set_attribute()

### ISSUE THREAD

**Issue by maol-corteva** [genometools/genometools#978]
## Problem description
Dear @satta : 

I use GenomeTools python library to fix or modify GFF files provided by external collaborators when these don't match the spec or don't fit our internal systems.   Many times this involves issues with coordinate systems (coordinate translation for just a region of a chromosome or some major re-arrangement) or fixing other items in the object (attributes, intron/exon boundaries, etc).

Sometimes, it would be simpler to modify an existing FeatureNode object in place rather than to make a a new one to copy most of the old node's attributes and fix the one attribute or coordinates that need fixing from "failed" object.

It would be nice to do something like this to the existing FeatureNode class (or one that inherits from it):  

```python
#... as part of class definition ...
def update_range(self, this_start, this_end):
    newrange = Range( this_start, this_end )
    try:
        print(f"Setting range of to : {newrange}")
        gtlib.gt_genome_node_set_range(self.gn, newrange)
    except:
        raise Exception("Unable to update the range")
```

But the code above fails because "newrange" is not the C GtRange object expected..  I am not sure what I should be passing from the Python side.   And actually it would be lovely if the python FeatureNode class would support this.

Another nice to have method  would be if the python existing FN.add_attribute()  method (or  a new one)  used the C library  [gtlib.gt_feature_node_set_attribute()](https://github.com/genometools/genometools/blob/694fe366e92d56d2b70ec7ef5742a75560e9a992/src/extended/feature_node.c#L683)   (which allows override of existing attribute) instead of [gtlib.gt_feature_node_add_attribute](https://github.com/genometools/genometools/blob/694fe366e92d56d2b70ec7ef5742a75560e9a992/gtpython/gt/extended/feature_node.py#L157) (expects attribute to be brand new)

I will be happy to submit pull requests, but need to get familiar with the process first.

Cheers,

Mauricio L.

**Comment by satta** [comment]
I have opened a PR for these additions now.

**Comment by maol-corteva** [comment]
@satta :  I never got back to you, but that PR and release worked !   Thanks for this.
