### ISSUE TITLE
gff file is not sorted after using -sortlines

### ISSUE THREAD

**Issue by canhnd58** [genometools/genometools#985]
## Problem description

I am using `tabix` to index a gff file after calling `gt gff3 --sortlines` but `tabix` complains that the file is not sorted

```
[ti_index_core] the file out of order at line 7
```

## Exact command line call triggering the problem

```
gt gff3 -sortlines -tidy -retainids tmp.gff > tmp.sorted.gff
bgzip tmp.sorted.gff
tabix tmp.sorted.gff.gz
```

## Example minimal input triggering the problem

```
NC_007417.3	iBtemplates_Tcas5	HSP	139165	139365	0	-	.	ID=23971391;Name=iB_05965;Target=iB_05965 16 216
NC_007417.3	iBtemplates_Tcas5	HSP	139411	139425	0	-	.	ID=23971391;Name=iB_05965;Target=iB_05965 1 15
NC_007417.3	iBtemplates_Tcas5	HSP	170645	170738	0	-	.	ID=23980693;Name=iB_09325(2/2);Alias=iB_09325;Target=iB_09325 144 237
NC_007417.3	iBtemplates_Tcas5	HSP	175849	175991	0	-	.	ID=23980693;Name=iB_09325(2/2);Alias=iB_09325;Target=iB_09325 1 143
NC_007417.3	iBtemplates_Tcas5	HSP	172917	173410	0	-	.	ID=23974642;Name=iB_04521(2/4);Alias=iB_04521;Target=iB_04521 1 494
NC_007417.3	iBtemplates_Tcas5	HSP	174782	175306	0	-	.	ID=23972312;Name=iB_05964(1/4);Alias=iB_05964;Target=iB_05964 1 525
NC_007417.3	iBtemplates_Tcas5	HSP	185524	185760	0	-	.	ID=23980547;Name=iB_09325(1/2);Alias=iB_09325;Target=iB_09325 1 237
NC_007417.3	iBtemplates_Tcas5	HSP	203540	204069	0	-	.	ID=23972047;Name=iB_07807;Target=iB_07807 1 530
NC_007417.3	iBtemplates_Tcas5	HSP	206671	207150	0	+	.	ID=23976289;Name=iB_05938(3/3);Alias=iB_05938;Target=iB_05938 1 480
NC_007417.3	iBtemplates_Tcas5	HSP	207450	207552	0	-	.	ID=23977814;Name=iB_07781(1/5);Alias=iB_07781;Target=iB_07781 348 450
NC_007417.3	iBtemplates_Tcas5	HSP	207683	207818	0	-	.	ID=23977814;Name=iB_07781(1/5);Alias=iB_07781;Target=iB_07781 212 347
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

1.6.2

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.

Yes. `-j4 cairo=no`

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Ubuntu 18.04.5 LTS x86_64

**Comment by satta** [comment]
This is indeed a bug, related to pseudonode handling. There are nodes in the input with the same ID but no explicit parent, which are not clustered correctly and hence lead to wrongful merging of clusters sorted separately. Will take a look, thanks!

Your input is not wrong technically, it was just not considered fully.

**Comment by satta** [comment]
This is now fixed in the latest git master.
