### ISSUE TITLE
Improve portability of test usage

### ISSUE THREAD

**Issue by brook-milligan** [genometools/genometools#989]
## Problem description
Two files (scripts/calltestcase.sh and scripts/spmcheck.sh) use test to check equality with the == operator.  This is not portable and should be replaced with =.

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
1.6.2

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

[patch-scripts_calltestcase.sh.txt](https://github.com/genometools/genometools/files/7172794/patch-scripts_calltestcase.sh.txt)
[patch-scripts_spmcheck.sh.txt](https://github.com/genometools/genometools/files/7172795/patch-scripts_spmcheck.sh.txt)

**Comment by satta** [comment]
I  see, thanks! Do you want to open a PR or should we just commit the patches ourself?

**Comment by brook-milligan** [comment]
> On Sep 15, 2021, at 2:01 PM, Sascha Steinbiss ***@***.***> wrote:
> 
> I see, thanks! Do you want to open a PR or should we just commit the patches ourself?

The patches are trivial.  Just commit them.

Thanks.

Cheers,
Brook

**Comment by brook-milligan** [comment]
> On Sep 15, 2021, at 2:09 PM, Sascha Steinbiss ***@***.***> wrote:
> 
> Closed #989 via 6e53f2a.

Super.  Thanks for doing this so quickly.

Cheers,
Brook
