### ISSUE TITLE
Conda installation requires python2.7

### ISSUE THREAD

**Issue by holmrenser** [genometools/genometools#994]
The current bioconda package requires python2.7.*, which is increasingly incompatible with many other tools.

Example: JBrowse2 uses samtools and genometools, but the last samtools version compatible with python 2.7.* is 1.7, whereas the latest samtools version is 1.14.

What would it take to make the switch to python 3.*? I can submit a PR if wanted.

**Comment by satta** [comment]
I don't think there is much to do for the Python bindings, in fact in the Debian package we already use Python 3: https://packages.debian.org/unstable/python3-genometools

The rest of GenomeTools should be completely unaffected, as that is written in other languages.
If you can spot anything we would very much appreciate a PR :)

**Comment by holmrenser** [comment]
Ah, good to know! That would mean just changing the bioconda package to python3 should fix this? Shall I then submit a PR to bioconda for that?

**Comment by holmrenser** [comment]
@satta as a follow-up: it seems the bioconda recipe is using an older version of genome tools (1.2.1) and that it is not making the `gt` executable available but only some python wrappers. Is this recipe maintained by the genometools maintainers or is it an outside contribution?

**Comment by satta** [comment]
AFAIK we do not maintain (or use) the Conda recipe, so it must have been someone else. We (I to be exact) only provide a Debian/Ubuntu package.

Looks like there was some activity beyond 1.2.1 -> https://github.com/bioconda/bioconda-recipes/tree/master/recipes/genometools-genometools but no idea why this did not make it into general availability.

**Comment by holmrenser** [comment]
Ok thanks, I'll dive a bit into the coda recipe then!

**Comment by satta** [comment]
Thanks!

**Comment by innovate-invent** [comment]
Has there been any work on this?
I am in the process of making a contribution to that recipe myself: https://github.com/bioconda/bioconda-recipes/pull/31865

The package fails to compile due to missing glib.h

**Comment by satta** [comment]
Just from my point of view, we as the GenomeTools developers don't package anything for Conda (or use it), as I said.
Looks like commit https://github.com/bioconda/bioconda-recipes/pull/31865/commits/998b7253428b36941cbec46535e125e69afeb074 fixed the build failure, AFAICS.

**Comment by holmrenser** [comment]
@satta You might want to remove the bioconda badge from the readme then ;-)

**Comment by satta** [comment]
> @satta You might want to remove the bioconda badge from the readme then ;-)

The badge -- all the badges, in fact -- are just to inform people that there are packages in these package managers for GenomeTools. I've seen people try to build from source on systems where an install from a package would have been much easier. I would never assume that showing the badge for a package would imply being involved in its maintenance ;)
