### ISSUE TITLE
gt gff3 -sort error

### ISSUE THREAD

**Issue by cassondranewman** [genometools/genometools#998]
## Problem description
An error occurs when issuing the sort command on my gff3 file. It seems like the gt program is classifying a single feature as a multi-feature, which leads to an error. The error is copied below: 

**gt gff3: error: the multi-feature with ID "None" on line 1911 in file "input.gff3" has a different attribute 'Parent' than its counterpart on line 1904 ('mRNA37983' vs. 'mRNA37984')**

I am fairly certain that the ID="None" for the CDS is causing this problem. Please let me know if there is a way within gt to circumvent this issue or if you have a suggestion for manually fixing this naming problem (if you agree that this is the cause of the error).

## Exact command line call triggering the problem

```
gt gff3 -sort input.gff3 > output.gff3
```

## Example minimal input triggering the problem
 sed -n '1898,1920p' input.gff3

arahy.BaileyII.gnm1.Scaffold_001        AUGUSTUS        CDS     891087  891632  0       -       0       ID=IDmodified-cds-105196;Parent=IDmodified-mrna-18254
arahy.BaileyII.gnm1.chr01       .       gene    2       1774    .       +       .       ID=gene35815
arahy.BaileyII.gnm1.chr01       .       mRNA    2       1774    .       +       .       ID=mRNA37984;Parent=gene35815
arahy.BaileyII.gnm1.chr01       AUGUSTUS        exon    2       421     .       +       .       ID=nbis-exon-160631;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01       AUGUSTUS        exon    585     1657    .       +       .       ID=nbis-exon-160632;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01       AUGUSTUS        exon    1747    1774    .       +       .       ID=nbis-exon-160633;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01       AUGUSTUS        CDS     2       421     0       +       0       ID=None;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01       AUGUSTUS        CDS     585     1657    1       +       0       ID=None;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01       AUGUSTUS        CDS     1747    1774    1       +       1       ID=None;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01       .       gene    3559    3924    .       +       .       ID=gene35814
arahy.BaileyII.gnm1.chr01       .       mRNA    3559    3924    .       +       .       ID=mRNA37983;Parent=gene35814
arahy.BaileyII.gnm1.chr01       AUGUSTUS        exon    3559    3714    .       +       .       ID=nbis-exon-160629;Parent=mRNA37983
arahy.BaileyII.gnm1.chr01       AUGUSTUS        exon    3877    3924    .       +       .       ID=nbis-exon-160630;Parent=mRNA37983
arahy.BaileyII.gnm1.chr01       AUGUSTUS        CDS     3559    3714    0       +       0       ID=None;Parent=mRNA37983
arahy.BaileyII.gnm1.chr01       AUGUSTUS        CDS     3877    3924    0       +       0       ID=None;Parent=mRNA37983
arahy.BaileyII.gnm1.chr01       .       gene    19013   20264   .       -       .       ID=gene35817
arahy.BaileyII.gnm1.chr01       .       mRNA    19013   20264   .       -       .       ID=mRNA37986;Parent=gene35817
arahy.BaileyII.gnm1.chr01       AUGUSTUS        exon    19013   19614   .       -       .       ID=nbis-exon-160636;Parent=mRNA37986
arahy.BaileyII.gnm1.chr01       AUGUSTUS        exon    19992   20043   .       -       .       ID=nbis-exon-160637;Parent=mRNA37986
arahy.BaileyII.gnm1.chr01       AUGUSTUS        exon    20127   20264   .       -       .       ID=nbis-exon-160638;Parent=mRNA37986
arahy.BaileyII.gnm1.chr01       AUGUSTUS        CDS     19013   19614   0       -       2       ID=None;Parent=mRNA37986
arahy.BaileyII.gnm1.chr01       AUGUSTUS        CDS     19992   20043   0       -       0       ID=None;Parent=mRNA37986
arahy.BaileyII.gnm1.chr01       AUGUSTUS        CDS     20127   20264   0       -       0       ID=None;Parent=mRNA37986

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
genometools/1.5.9 

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
No- provided as a module in HPC Cluster

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
CentOS

**Comment by satta** [comment]
Your hunch is correct -- features with identical IDs are assumed to be part of a "multi-feature" that is supposed to share a common parent. This is a workaround by itself to support old annotations that use the ID to convey semantic information where a proper parent-child structure is best.
A workaround here would be to remove the IDs for CDS features or simply give them unique IDs (e.g. CDSx where x is an incrementing number).

Example:
```
arahy.BaileyII.gnm1.chr01	.	gene	2	1774	.	+	.	ID=gene35815
arahy.BaileyII.gnm1.chr01	.	mRNA	2	1774	.	+	.	ID=mRNA37984;Parent=gene35815
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	2	421	.	+	.	ID=nbis-exon-160631;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	585	1657	.	+	.	ID=nbis-exon-160632;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	1747	1774	.	+	.	ID=nbis-exon-160633;Parent=mRNA37984
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	2	421	0	+	0	Parent=mRNA37984
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	585	1657	1	+	0	Parent=mRNA37984
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	1747	1774	1	+	1	Parent=mRNA37984
arahy.BaileyII.gnm1.chr01	.	gene	3559	3924	.	+	.	ID=gene35814
arahy.BaileyII.gnm1.chr01	.	mRNA	3559	3924	.	+	.	ID=mRNA37983;Parent=gene35814
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	3559	3714	.	+	.	ID=nbis-exon-160629;Parent=mRNA37983
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	3877	3924	.	+	.	ID=nbis-exon-160630;Parent=mRNA37983
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	3559	3714	0	+	0	Parent=mRNA37983
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	3877	3924	0	+	0	Parent=mRNA37983
arahy.BaileyII.gnm1.chr01	.	gene	19013	20264	.	-	.	ID=gene35817
arahy.BaileyII.gnm1.chr01	.	mRNA	19013	20264	.	-	.	ID=mRNA37986;Parent=gene35817
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	19013	19614	.	-	.	ID=nbis-exon-160636;Parent=mRNA37986
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	19992	20043	.	-	.	ID=nbis-exon-160637;Parent=mRNA37986
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	20127	20264	.	-	.	ID=nbis-exon-160638;Parent=mRNA37986
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	19013	19614	0	-	2	Parent=mRNA37986
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	19992	20043	0	-	0	Parent=mRNA37986
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	20127	20264	0	-	0	Parent=mRNA37986
```
which works:
```
$ gt gff3 -tidy ~/1.gff3                                                                 [1]
warning: line 1 in file "/home/satta/1.gff3" does not begin with "##gff-version" or "##gvf-version", create "##gff-version 3" line automatically
warning: seqid "arahy.BaileyII.gnm1.chr01" on line 1 in file "/home/satta/1.gff3" has not been previously introduced with a "##sequence-region" line, create such a line automatically
##gff-version 3
##sequence-region   arahy.BaileyII.gnm1.chr01 2 20264
arahy.BaileyII.gnm1.chr01	.	gene	2	1774	.	+	.	ID=gene1
arahy.BaileyII.gnm1.chr01	.	mRNA	2	1774	.	+	.	ID=mRNA1;Parent=gene1
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	2	421	.	+	.	Parent=mRNA1
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	2	421	0	+	0	Parent=mRNA1
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	585	1657	.	+	.	Parent=mRNA1
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	585	1657	1	+	0	Parent=mRNA1
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	1747	1774	.	+	.	Parent=mRNA1
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	1747	1774	1	+	1	Parent=mRNA1
###
arahy.BaileyII.gnm1.chr01	.	gene	3559	3924	.	+	.	ID=gene2
arahy.BaileyII.gnm1.chr01	.	mRNA	3559	3924	.	+	.	ID=mRNA2;Parent=gene2
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	3559	3714	.	+	.	Parent=mRNA2
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	3559	3714	0	+	0	Parent=mRNA2
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	3877	3924	.	+	.	Parent=mRNA2
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	3877	3924	0	+	0	Parent=mRNA2
###
arahy.BaileyII.gnm1.chr01	.	gene	19013	20264	.	-	.	ID=gene3
arahy.BaileyII.gnm1.chr01	.	mRNA	19013	20264	.	-	.	ID=mRNA3;Parent=gene3
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	19013	19614	.	-	.	Parent=mRNA3
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	19013	19614	0	-	2	Parent=mRNA3
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	19992	20043	.	-	.	Parent=mRNA3
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	19992	20043	0	-	0	Parent=mRNA3
arahy.BaileyII.gnm1.chr01	AUGUSTUS	exon	20127	20264	.	-	.	Parent=mRNA3
arahy.BaileyII.gnm1.chr01	AUGUSTUS	CDS	20127	20264	0	-	0	Parent=mRNA3
###
```

**Comment by cassondranewman** [comment]
Great! Thank you for your help!
